/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.campaigns.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListFeedbackCampaignsResponse.Builder.class)
public final class ListFeedbackCampaignsResponse {
    private final Optional<List<ListFeedbackCampaignsResponseLinksItem>> links;

    private final Optional<String> campaignId;

    private final Optional<List<ListFeedbackCampaignsResponseFeedbackItem>> feedback;

    private final Optional<Integer> totalItems;

    private final Map<String, Object> additionalProperties;

    private ListFeedbackCampaignsResponse(
            Optional<List<ListFeedbackCampaignsResponseLinksItem>> links,
            Optional<String> campaignId,
            Optional<List<ListFeedbackCampaignsResponseFeedbackItem>> feedback,
            Optional<Integer> totalItems,
            Map<String, Object> additionalProperties) {
        this.links = links;
        this.campaignId = campaignId;
        this.feedback = feedback;
        this.totalItems = totalItems;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A list of link types and descriptions for the API schema documents.
     */
    @JsonProperty("_links")
    public Optional<List<ListFeedbackCampaignsResponseLinksItem>> getLinks() {
        return links;
    }

    /**
     * @return The unique id for the campaign.
     */
    @JsonProperty("campaign_id")
    public Optional<String> getCampaignId() {
        return campaignId;
    }

    /**
     * @return A collection of feedback items for a campaign.
     */
    @JsonProperty("feedback")
    public Optional<List<ListFeedbackCampaignsResponseFeedbackItem>> getFeedback() {
        return feedback;
    }

    /**
     * @return The total number of items matching the query regardless of pagination.
     */
    @JsonProperty("total_items")
    public Optional<Integer> getTotalItems() {
        return totalItems;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListFeedbackCampaignsResponse && equalTo((ListFeedbackCampaignsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListFeedbackCampaignsResponse other) {
        return links.equals(other.links)
                && campaignId.equals(other.campaignId)
                && feedback.equals(other.feedback)
                && totalItems.equals(other.totalItems);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.links, this.campaignId, this.feedback, this.totalItems);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ListFeedbackCampaignsResponseLinksItem>> links = Optional.empty();

        private Optional<String> campaignId = Optional.empty();

        private Optional<List<ListFeedbackCampaignsResponseFeedbackItem>> feedback = Optional.empty();

        private Optional<Integer> totalItems = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListFeedbackCampaignsResponse other) {
            links(other.getLinks());
            campaignId(other.getCampaignId());
            feedback(other.getFeedback());
            totalItems(other.getTotalItems());
            return this;
        }

        /**
         * <p>A list of link types and descriptions for the API schema documents.</p>
         */
        @JsonSetter(value = "_links", nulls = Nulls.SKIP)
        public Builder links(Optional<List<ListFeedbackCampaignsResponseLinksItem>> links) {
            this.links = links;
            return this;
        }

        public Builder links(List<ListFeedbackCampaignsResponseLinksItem> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        /**
         * <p>The unique id for the campaign.</p>
         */
        @JsonSetter(value = "campaign_id", nulls = Nulls.SKIP)
        public Builder campaignId(Optional<String> campaignId) {
            this.campaignId = campaignId;
            return this;
        }

        public Builder campaignId(String campaignId) {
            this.campaignId = Optional.ofNullable(campaignId);
            return this;
        }

        /**
         * <p>A collection of feedback items for a campaign.</p>
         */
        @JsonSetter(value = "feedback", nulls = Nulls.SKIP)
        public Builder feedback(Optional<List<ListFeedbackCampaignsResponseFeedbackItem>> feedback) {
            this.feedback = feedback;
            return this;
        }

        public Builder feedback(List<ListFeedbackCampaignsResponseFeedbackItem> feedback) {
            this.feedback = Optional.ofNullable(feedback);
            return this;
        }

        /**
         * <p>The total number of items matching the query regardless of pagination.</p>
         */
        @JsonSetter(value = "total_items", nulls = Nulls.SKIP)
        public Builder totalItems(Optional<Integer> totalItems) {
            this.totalItems = totalItems;
            return this;
        }

        public Builder totalItems(Integer totalItems) {
            this.totalItems = Optional.ofNullable(totalItems);
            return this;
        }

        public ListFeedbackCampaignsResponse build() {
            return new ListFeedbackCampaignsResponse(links, campaignId, feedback, totalItems, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
