/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.audiences.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PatchAudienceContactRequestDataMode {
    public static final PatchAudienceContactRequestDataMode LIVE =
            new PatchAudienceContactRequestDataMode(Value.LIVE, "live");

    public static final PatchAudienceContactRequestDataMode HISTORICAL =
            new PatchAudienceContactRequestDataMode(Value.HISTORICAL, "historical");

    private final Value value;

    private final String string;

    PatchAudienceContactRequestDataMode(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PatchAudienceContactRequestDataMode
                        && this.string.equals(((PatchAudienceContactRequestDataMode) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LIVE:
                return visitor.visitLive();
            case HISTORICAL:
                return visitor.visitHistorical();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PatchAudienceContactRequestDataMode valueOf(String value) {
        switch (value) {
            case "live":
                return LIVE;
            case "historical":
                return HISTORICAL;
            default:
                return new PatchAudienceContactRequestDataMode(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        HISTORICAL,

        LIVE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitHistorical();

        T visitLive();

        T visitUnknown(String unknownType);
    }
}
