/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.connectedsites;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.mailchimp.marketing.core.ClientOptions;
import com.mailchimp.marketing.core.MailchimpClientApiException;
import com.mailchimp.marketing.core.MailchimpClientException;
import com.mailchimp.marketing.core.MailchimpClientHttpResponse;
import com.mailchimp.marketing.core.MediaTypes;
import com.mailchimp.marketing.core.ObjectMappers;
import com.mailchimp.marketing.core.QueryStringMapper;
import com.mailchimp.marketing.core.RequestOptions;
import com.mailchimp.marketing.core.RetryInterceptor;
import com.mailchimp.marketing.core.pagination.SyncPagingIterable;
import com.mailchimp.marketing.resources.connectedsites.requests.CreateActionVerifyScriptInstallationConnectedSitesRequest;
import com.mailchimp.marketing.resources.connectedsites.requests.CreateConnectedSitesRequest;
import com.mailchimp.marketing.resources.connectedsites.requests.DeleteConnectedSitesRequest;
import com.mailchimp.marketing.resources.connectedsites.requests.GetConnectedSitesRequest;
import com.mailchimp.marketing.resources.connectedsites.requests.ListConnectedSitesRequest;
import com.mailchimp.marketing.resources.connectedsites.types.ListConnectedSitesResponse;
import com.mailchimp.marketing.types.ConnectedSite;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawConnectedSitesClient {
    protected final ClientOptions clientOptions;

    public AsyncRawConnectedSitesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Get all connected sites in an account.
     */
    public CompletableFuture<MailchimpClientHttpResponse<SyncPagingIterable<ConnectedSite>>> list() {
        return list(ListConnectedSitesRequest.builder().build());
    }

    /**
     * Get all connected sites in an account.
     */
    public CompletableFuture<MailchimpClientHttpResponse<SyncPagingIterable<ConnectedSite>>> list(
            RequestOptions requestOptions) {
        return list(ListConnectedSitesRequest.builder().build(), requestOptions);
    }

    /**
     * Get all connected sites in an account.
     */
    public CompletableFuture<MailchimpClientHttpResponse<SyncPagingIterable<ConnectedSite>>> list(
            ListConnectedSitesRequest request) {
        return list(request, null);
    }

    /**
     * Get all connected sites in an account.
     */
    public CompletableFuture<MailchimpClientHttpResponse<SyncPagingIterable<ConnectedSite>>> list(
            ListConnectedSitesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/connected-sites");
        if (request.getCount().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "count", request.getCount().get(), false);
        }
        if (request.getOffset().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "offset", request.getOffset().get(), false);
        }
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MailchimpClientHttpResponse<SyncPagingIterable<ConnectedSite>>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        ListConnectedSitesResponse parsedResponse = ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, ListConnectedSitesResponse.class);
                        int newPageNumber = request.getOffset()
                                .map((Integer page) -> page + 1)
                                .orElse(1);
                        ListConnectedSitesRequest nextRequest = ListConnectedSitesRequest.builder()
                                .from(request)
                                .offset(newPageNumber)
                                .build();
                        List<ConnectedSite> result = parsedResponse.getSites().orElse(Collections.emptyList());
                        future.complete(new MailchimpClientHttpResponse<>(
                                new SyncPagingIterable<ConnectedSite>(true, result, parsedResponse, () -> {
                                    try {
                                        return list(nextRequest, requestOptions)
                                                .get()
                                                .body();
                                    } catch (InterruptedException | ExecutionException e) {
                                        throw new RuntimeException(e);
                                    }
                                }),
                                response));
                        return;
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MailchimpClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(
                            new MailchimpClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MailchimpClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Create a new Mailchimp connected site.
     */
    public CompletableFuture<MailchimpClientHttpResponse<ConnectedSite>> create(CreateConnectedSitesRequest request) {
        return create(request, null);
    }

    /**
     * Create a new Mailchimp connected site.
     */
    public CompletableFuture<MailchimpClientHttpResponse<ConnectedSite>> create(
            CreateConnectedSitesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/connected-sites");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MailchimpClientHttpResponse<ConnectedSite>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MailchimpClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ConnectedSite.class),
                                response));
                        return;
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MailchimpClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(
                            new MailchimpClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MailchimpClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Get information about a specific connected site.
     */
    public CompletableFuture<MailchimpClientHttpResponse<ConnectedSite>> get(String connectedSiteId) {
        return get(connectedSiteId, GetConnectedSitesRequest.builder().build());
    }

    /**
     * Get information about a specific connected site.
     */
    public CompletableFuture<MailchimpClientHttpResponse<ConnectedSite>> get(
            String connectedSiteId, RequestOptions requestOptions) {
        return get(connectedSiteId, GetConnectedSitesRequest.builder().build(), requestOptions);
    }

    /**
     * Get information about a specific connected site.
     */
    public CompletableFuture<MailchimpClientHttpResponse<ConnectedSite>> get(
            String connectedSiteId, GetConnectedSitesRequest request) {
        return get(connectedSiteId, request, null);
    }

    /**
     * Get information about a specific connected site.
     */
    public CompletableFuture<MailchimpClientHttpResponse<ConnectedSite>> get(
            String connectedSiteId, GetConnectedSitesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/connected-sites")
                .addPathSegment(connectedSiteId);
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MailchimpClientHttpResponse<ConnectedSite>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MailchimpClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ConnectedSite.class),
                                response));
                        return;
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MailchimpClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(
                            new MailchimpClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MailchimpClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Remove a connected site from your Mailchimp account.
     */
    public CompletableFuture<MailchimpClientHttpResponse<Void>> delete(String connectedSiteId) {
        return delete(connectedSiteId, DeleteConnectedSitesRequest.builder().build());
    }

    /**
     * Remove a connected site from your Mailchimp account.
     */
    public CompletableFuture<MailchimpClientHttpResponse<Void>> delete(
            String connectedSiteId, RequestOptions requestOptions) {
        return delete(connectedSiteId, DeleteConnectedSitesRequest.builder().build(), requestOptions);
    }

    /**
     * Remove a connected site from your Mailchimp account.
     */
    public CompletableFuture<MailchimpClientHttpResponse<Void>> delete(
            String connectedSiteId, DeleteConnectedSitesRequest request) {
        return delete(connectedSiteId, request, null);
    }

    /**
     * Remove a connected site from your Mailchimp account.
     */
    public CompletableFuture<MailchimpClientHttpResponse<Void>> delete(
            String connectedSiteId, DeleteConnectedSitesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/connected-sites")
                .addPathSegment(connectedSiteId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MailchimpClientHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new MailchimpClientHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MailchimpClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(
                            new MailchimpClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MailchimpClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Verify that the connected sites script has been installed, either via the script URL or fragment.
     */
    public CompletableFuture<MailchimpClientHttpResponse<Void>> createActionVerifyScriptInstallation(
            String connectedSiteId) {
        return createActionVerifyScriptInstallation(
                connectedSiteId,
                CreateActionVerifyScriptInstallationConnectedSitesRequest.builder()
                        .build());
    }

    /**
     * Verify that the connected sites script has been installed, either via the script URL or fragment.
     */
    public CompletableFuture<MailchimpClientHttpResponse<Void>> createActionVerifyScriptInstallation(
            String connectedSiteId, RequestOptions requestOptions) {
        return createActionVerifyScriptInstallation(
                connectedSiteId,
                CreateActionVerifyScriptInstallationConnectedSitesRequest.builder()
                        .build(),
                requestOptions);
    }

    /**
     * Verify that the connected sites script has been installed, either via the script URL or fragment.
     */
    public CompletableFuture<MailchimpClientHttpResponse<Void>> createActionVerifyScriptInstallation(
            String connectedSiteId, CreateActionVerifyScriptInstallationConnectedSitesRequest request) {
        return createActionVerifyScriptInstallation(connectedSiteId, request, null);
    }

    /**
     * Verify that the connected sites script has been installed, either via the script URL or fragment.
     */
    public CompletableFuture<MailchimpClientHttpResponse<Void>> createActionVerifyScriptInstallation(
            String connectedSiteId,
            CreateActionVerifyScriptInstallationConnectedSitesRequest request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/connected-sites")
                .addPathSegment(connectedSiteId)
                .addPathSegments("actions")
                .addPathSegments("verify-script-installation");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MailchimpClientHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new MailchimpClientHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MailchimpClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(
                            new MailchimpClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MailchimpClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
