/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.filemanager;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.mailchimp.marketing.core.ClientOptions;
import com.mailchimp.marketing.core.MailchimpClientApiException;
import com.mailchimp.marketing.core.MailchimpClientException;
import com.mailchimp.marketing.core.MailchimpClientHttpResponse;
import com.mailchimp.marketing.core.MediaTypes;
import com.mailchimp.marketing.core.ObjectMappers;
import com.mailchimp.marketing.core.QueryStringMapper;
import com.mailchimp.marketing.core.RequestOptions;
import com.mailchimp.marketing.core.RetryInterceptor;
import com.mailchimp.marketing.core.pagination.SyncPagingIterable;
import com.mailchimp.marketing.resources.filemanager.requests.CreateFileFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.requests.CreateFolderFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.requests.DeleteFileFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.requests.DeleteFolderFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.requests.GetFileFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.requests.GetFolderFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.requests.ListFilesFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.requests.ListFolderFilesFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.requests.ListFoldersFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.requests.UpdateFileFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.requests.UpdateFolderFileManagerRequest;
import com.mailchimp.marketing.resources.filemanager.types.CreateFolderFileManagerResponse;
import com.mailchimp.marketing.resources.filemanager.types.GetFolderFileManagerResponse;
import com.mailchimp.marketing.resources.filemanager.types.ListFileManagerResponseItem;
import com.mailchimp.marketing.resources.filemanager.types.ListFilesFileManagerResponse;
import com.mailchimp.marketing.resources.filemanager.types.ListFolderFilesFileManagerResponse;
import com.mailchimp.marketing.resources.filemanager.types.ListFoldersFileManagerResponse;
import com.mailchimp.marketing.resources.filemanager.types.ListFoldersFileManagerResponseFoldersItem;
import com.mailchimp.marketing.resources.filemanager.types.UpdateFolderFileManagerResponse;
import com.mailchimp.marketing.types.GalleryFile;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawFileManagerClient {
    protected final ClientOptions clientOptions;

    public RawFileManagerClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Get information about the file-manager endpoint's resources
     */
    public MailchimpClientHttpResponse<List<ListFileManagerResponseItem>> list() {
        return list(null);
    }

    /**
     * Get information about the file-manager endpoint's resources
     */
    public MailchimpClientHttpResponse<List<ListFileManagerResponseItem>> list(RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, new TypeReference<List<ListFileManagerResponseItem>>() {}),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get a list of available images and files stored in the File Manager for the account.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<GalleryFile>> listFiles() {
        return listFiles(ListFilesFileManagerRequest.builder().build());
    }

    /**
     * Get a list of available images and files stored in the File Manager for the account.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<GalleryFile>> listFiles(RequestOptions requestOptions) {
        return listFiles(ListFilesFileManagerRequest.builder().build(), requestOptions);
    }

    /**
     * Get a list of available images and files stored in the File Manager for the account.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<GalleryFile>> listFiles(ListFilesFileManagerRequest request) {
        return listFiles(request, null);
    }

    /**
     * Get a list of available images and files stored in the File Manager for the account.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<GalleryFile>> listFiles(
            ListFilesFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/files");
        if (request.getCount().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "count", request.getCount().get(), false);
        }
        if (request.getOffset().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "offset", request.getOffset().get(), false);
        }
        if (request.getType().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "type", request.getType().get(), false);
        }
        if (request.getCreatedBy().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "created_by", request.getCreatedBy().get(), false);
        }
        if (request.getBeforeCreatedAt().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "before_created_at", request.getBeforeCreatedAt().get(), false);
        }
        if (request.getSinceCreatedAt().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "since_created_at", request.getSinceCreatedAt().get(), false);
        }
        if (request.getSortField().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sort_field", request.getSortField().get(), false);
        }
        if (request.getSortDir().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sort_dir", request.getSortDir().get(), false);
        }
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListFilesFileManagerResponse parsedResponse =
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListFilesFileManagerResponse.class);
                int newPageNumber =
                        request.getOffset().map((Integer page) -> page + 1).orElse(1);
                ListFilesFileManagerRequest nextRequest = ListFilesFileManagerRequest.builder()
                        .from(request)
                        .offset(newPageNumber)
                        .build();
                List<GalleryFile> result = parsedResponse.getFiles().orElse(Collections.emptyList());
                return new MailchimpClientHttpResponse<>(
                        new SyncPagingIterable<GalleryFile>(
                                true, result, parsedResponse, () -> listFiles(nextRequest, requestOptions)
                                        .body()),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Upload a new image or file to the File Manager.
     */
    public MailchimpClientHttpResponse<GalleryFile> createFile(CreateFileFileManagerRequest request) {
        return createFile(request, null);
    }

    /**
     * Upload a new image or file to the File Manager.
     */
    public MailchimpClientHttpResponse<GalleryFile> createFile(
            CreateFileFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/files");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GalleryFile.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get information about a specific file in the File Manager.
     */
    public MailchimpClientHttpResponse<GalleryFile> getFile(String fileId) {
        return getFile(fileId, GetFileFileManagerRequest.builder().build());
    }

    /**
     * Get information about a specific file in the File Manager.
     */
    public MailchimpClientHttpResponse<GalleryFile> getFile(String fileId, RequestOptions requestOptions) {
        return getFile(fileId, GetFileFileManagerRequest.builder().build(), requestOptions);
    }

    /**
     * Get information about a specific file in the File Manager.
     */
    public MailchimpClientHttpResponse<GalleryFile> getFile(String fileId, GetFileFileManagerRequest request) {
        return getFile(fileId, request, null);
    }

    /**
     * Get information about a specific file in the File Manager.
     */
    public MailchimpClientHttpResponse<GalleryFile> getFile(
            String fileId, GetFileFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/files")
                .addPathSegment(fileId);
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GalleryFile.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Remove a specific file from the File Manager.
     */
    public MailchimpClientHttpResponse<Void> deleteFile(String fileId) {
        return deleteFile(fileId, DeleteFileFileManagerRequest.builder().build());
    }

    /**
     * Remove a specific file from the File Manager.
     */
    public MailchimpClientHttpResponse<Void> deleteFile(String fileId, RequestOptions requestOptions) {
        return deleteFile(fileId, DeleteFileFileManagerRequest.builder().build(), requestOptions);
    }

    /**
     * Remove a specific file from the File Manager.
     */
    public MailchimpClientHttpResponse<Void> deleteFile(String fileId, DeleteFileFileManagerRequest request) {
        return deleteFile(fileId, request, null);
    }

    /**
     * Remove a specific file from the File Manager.
     */
    public MailchimpClientHttpResponse<Void> deleteFile(
            String fileId, DeleteFileFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/files")
                .addPathSegment(fileId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Update a file in the File Manager.
     */
    public MailchimpClientHttpResponse<GalleryFile> updateFile(String fileId) {
        return updateFile(fileId, UpdateFileFileManagerRequest.builder().build());
    }

    /**
     * Update a file in the File Manager.
     */
    public MailchimpClientHttpResponse<GalleryFile> updateFile(String fileId, RequestOptions requestOptions) {
        return updateFile(fileId, UpdateFileFileManagerRequest.builder().build(), requestOptions);
    }

    /**
     * Update a file in the File Manager.
     */
    public MailchimpClientHttpResponse<GalleryFile> updateFile(String fileId, UpdateFileFileManagerRequest request) {
        return updateFile(fileId, request, null);
    }

    /**
     * Update a file in the File Manager.
     */
    public MailchimpClientHttpResponse<GalleryFile> updateFile(
            String fileId, UpdateFileFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/files")
                .addPathSegment(fileId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GalleryFile.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get a list of all folders in the File Manager.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ListFoldersFileManagerResponseFoldersItem>> listFolders() {
        return listFolders(ListFoldersFileManagerRequest.builder().build());
    }

    /**
     * Get a list of all folders in the File Manager.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ListFoldersFileManagerResponseFoldersItem>> listFolders(
            RequestOptions requestOptions) {
        return listFolders(ListFoldersFileManagerRequest.builder().build(), requestOptions);
    }

    /**
     * Get a list of all folders in the File Manager.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ListFoldersFileManagerResponseFoldersItem>> listFolders(
            ListFoldersFileManagerRequest request) {
        return listFolders(request, null);
    }

    /**
     * Get a list of all folders in the File Manager.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ListFoldersFileManagerResponseFoldersItem>> listFolders(
            ListFoldersFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/folders");
        if (request.getCount().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "count", request.getCount().get(), false);
        }
        if (request.getOffset().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "offset", request.getOffset().get(), false);
        }
        if (request.getCreatedBy().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "created_by", request.getCreatedBy().get(), false);
        }
        if (request.getBeforeCreatedAt().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "before_created_at", request.getBeforeCreatedAt().get(), false);
        }
        if (request.getSinceCreatedAt().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "since_created_at", request.getSinceCreatedAt().get(), false);
        }
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListFoldersFileManagerResponse parsedResponse =
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListFoldersFileManagerResponse.class);
                int newPageNumber =
                        request.getOffset().map((Integer page) -> page + 1).orElse(1);
                ListFoldersFileManagerRequest nextRequest = ListFoldersFileManagerRequest.builder()
                        .from(request)
                        .offset(newPageNumber)
                        .build();
                List<ListFoldersFileManagerResponseFoldersItem> result =
                        parsedResponse.getFolders().orElse(Collections.emptyList());
                return new MailchimpClientHttpResponse<>(
                        new SyncPagingIterable<ListFoldersFileManagerResponseFoldersItem>(
                                true, result, parsedResponse, () -> listFolders(nextRequest, requestOptions)
                                        .body()),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Create a new folder in the File Manager.
     */
    public MailchimpClientHttpResponse<CreateFolderFileManagerResponse> createFolder(
            CreateFolderFileManagerRequest request) {
        return createFolder(request, null);
    }

    /**
     * Create a new folder in the File Manager.
     */
    public MailchimpClientHttpResponse<CreateFolderFileManagerResponse> createFolder(
            CreateFolderFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/folders");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreateFolderFileManagerResponse.class),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get information about a specific folder in the File Manager.
     */
    public MailchimpClientHttpResponse<GetFolderFileManagerResponse> getFolder(String folderId) {
        return getFolder(folderId, GetFolderFileManagerRequest.builder().build());
    }

    /**
     * Get information about a specific folder in the File Manager.
     */
    public MailchimpClientHttpResponse<GetFolderFileManagerResponse> getFolder(
            String folderId, RequestOptions requestOptions) {
        return getFolder(folderId, GetFolderFileManagerRequest.builder().build(), requestOptions);
    }

    /**
     * Get information about a specific folder in the File Manager.
     */
    public MailchimpClientHttpResponse<GetFolderFileManagerResponse> getFolder(
            String folderId, GetFolderFileManagerRequest request) {
        return getFolder(folderId, request, null);
    }

    /**
     * Get information about a specific folder in the File Manager.
     */
    public MailchimpClientHttpResponse<GetFolderFileManagerResponse> getFolder(
            String folderId, GetFolderFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/folders")
                .addPathSegment(folderId);
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetFolderFileManagerResponse.class),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Delete a specific folder in the File Manager.
     */
    public MailchimpClientHttpResponse<Void> deleteFolder(String folderId) {
        return deleteFolder(folderId, DeleteFolderFileManagerRequest.builder().build());
    }

    /**
     * Delete a specific folder in the File Manager.
     */
    public MailchimpClientHttpResponse<Void> deleteFolder(String folderId, RequestOptions requestOptions) {
        return deleteFolder(folderId, DeleteFolderFileManagerRequest.builder().build(), requestOptions);
    }

    /**
     * Delete a specific folder in the File Manager.
     */
    public MailchimpClientHttpResponse<Void> deleteFolder(String folderId, DeleteFolderFileManagerRequest request) {
        return deleteFolder(folderId, request, null);
    }

    /**
     * Delete a specific folder in the File Manager.
     */
    public MailchimpClientHttpResponse<Void> deleteFolder(
            String folderId, DeleteFolderFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/folders")
                .addPathSegment(folderId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Update a specific File Manager folder.
     */
    public MailchimpClientHttpResponse<UpdateFolderFileManagerResponse> updateFolder(
            String folderId, UpdateFolderFileManagerRequest request) {
        return updateFolder(folderId, request, null);
    }

    /**
     * Update a specific File Manager folder.
     */
    public MailchimpClientHttpResponse<UpdateFolderFileManagerResponse> updateFolder(
            String folderId, UpdateFolderFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/folders")
                .addPathSegment(folderId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateFolderFileManagerResponse.class),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get a list of available images and files stored in this folder.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<GalleryFile>> listFolderFiles(String folderId) {
        return listFolderFiles(
                folderId, ListFolderFilesFileManagerRequest.builder().build());
    }

    /**
     * Get a list of available images and files stored in this folder.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<GalleryFile>> listFolderFiles(
            String folderId, RequestOptions requestOptions) {
        return listFolderFiles(
                folderId, ListFolderFilesFileManagerRequest.builder().build(), requestOptions);
    }

    /**
     * Get a list of available images and files stored in this folder.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<GalleryFile>> listFolderFiles(
            String folderId, ListFolderFilesFileManagerRequest request) {
        return listFolderFiles(folderId, request, null);
    }

    /**
     * Get a list of available images and files stored in this folder.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<GalleryFile>> listFolderFiles(
            String folderId, ListFolderFilesFileManagerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/file-manager/folders")
                .addPathSegment(folderId)
                .addPathSegments("files");
        if (request.getCount().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "count", request.getCount().get(), false);
        }
        if (request.getOffset().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "offset", request.getOffset().get(), false);
        }
        if (request.getType().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "type", request.getType().get(), false);
        }
        if (request.getCreatedBy().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "created_by", request.getCreatedBy().get(), false);
        }
        if (request.getBeforeCreatedAt().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "before_created_at", request.getBeforeCreatedAt().get(), false);
        }
        if (request.getSinceCreatedAt().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "since_created_at", request.getSinceCreatedAt().get(), false);
        }
        if (request.getSortField().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sort_field", request.getSortField().get(), false);
        }
        if (request.getSortDir().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sort_dir", request.getSortDir().get(), false);
        }
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListFolderFilesFileManagerResponse parsedResponse = ObjectMappers.JSON_MAPPER.readValue(
                        responseBodyString, ListFolderFilesFileManagerResponse.class);
                int newPageNumber =
                        request.getOffset().map((Integer page) -> page + 1).orElse(1);
                ListFolderFilesFileManagerRequest nextRequest = ListFolderFilesFileManagerRequest.builder()
                        .from(request)
                        .offset(newPageNumber)
                        .build();
                List<GalleryFile> result = parsedResponse.getFiles().orElse(Collections.emptyList());
                return new MailchimpClientHttpResponse<>(
                        new SyncPagingIterable<GalleryFile>(true, result, parsedResponse, () -> listFolderFiles(
                                        folderId, nextRequest, requestOptions)
                                .body()),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }
}
