/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.audiences;

import com.mailchimp.marketing.core.ClientOptions;
import com.mailchimp.marketing.core.RequestOptions;
import com.mailchimp.marketing.resources.audiences.requests.CreateAudienceContactRequest;
import com.mailchimp.marketing.resources.audiences.requests.GetAudienceContactListRequest;
import com.mailchimp.marketing.resources.audiences.requests.GetAudienceContactRequest;
import com.mailchimp.marketing.resources.audiences.requests.PatchAudienceContactRequest;
import com.mailchimp.marketing.resources.audiences.requests.PostAudiencesContactsActionsArchiveRequest;
import com.mailchimp.marketing.resources.audiences.requests.PostAudiencesContactsActionsForgetRequest;
import com.mailchimp.marketing.resources.audiences.types.GetAudienceContactListResponse;
import com.mailchimp.marketing.types.AudiencesContact;
import java.util.concurrent.CompletableFuture;

public class AsyncAudiencesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawAudiencesClient rawClient;

    public AsyncAudiencesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawAudiencesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawAudiencesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get a list of omni-channel contacts for a given audience.
     */
    public CompletableFuture<GetAudienceContactListResponse> getAudienceContactList(String audienceId) {
        return this.rawClient.getAudienceContactList(audienceId).thenApply(response -> response.body());
    }

    /**
     * Get a list of omni-channel contacts for a given audience.
     */
    public CompletableFuture<GetAudienceContactListResponse> getAudienceContactList(
            String audienceId, RequestOptions requestOptions) {
        return this.rawClient.getAudienceContactList(audienceId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get a list of omni-channel contacts for a given audience.
     */
    public CompletableFuture<GetAudienceContactListResponse> getAudienceContactList(
            String audienceId, GetAudienceContactListRequest request) {
        return this.rawClient.getAudienceContactList(audienceId, request).thenApply(response -> response.body());
    }

    /**
     * Get a list of omni-channel contacts for a given audience.
     */
    public CompletableFuture<GetAudienceContactListResponse> getAudienceContactList(
            String audienceId, GetAudienceContactListRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getAudienceContactList(audienceId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Create a new omni-channel contact for an audience.
     */
    public CompletableFuture<AudiencesContact> createAudienceContact(String audienceId) {
        return this.rawClient.createAudienceContact(audienceId).thenApply(response -> response.body());
    }

    /**
     * Create a new omni-channel contact for an audience.
     */
    public CompletableFuture<AudiencesContact> createAudienceContact(String audienceId, RequestOptions requestOptions) {
        return this.rawClient.createAudienceContact(audienceId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create a new omni-channel contact for an audience.
     */
    public CompletableFuture<AudiencesContact> createAudienceContact(
            String audienceId, CreateAudienceContactRequest request) {
        return this.rawClient.createAudienceContact(audienceId, request).thenApply(response -> response.body());
    }

    /**
     * Create a new omni-channel contact for an audience.
     */
    public CompletableFuture<AudiencesContact> createAudienceContact(
            String audienceId, CreateAudienceContactRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .createAudienceContact(audienceId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Retrieve a specific omni-channel contact in an audience.
     */
    public CompletableFuture<AudiencesContact> getAudienceContact(String audienceId, String contactId) {
        return this.rawClient.getAudienceContact(audienceId, contactId).thenApply(response -> response.body());
    }

    /**
     * Retrieve a specific omni-channel contact in an audience.
     */
    public CompletableFuture<AudiencesContact> getAudienceContact(
            String audienceId, String contactId, RequestOptions requestOptions) {
        return this.rawClient
                .getAudienceContact(audienceId, contactId, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Retrieve a specific omni-channel contact in an audience.
     */
    public CompletableFuture<AudiencesContact> getAudienceContact(
            String audienceId, String contactId, GetAudienceContactRequest request) {
        return this.rawClient.getAudienceContact(audienceId, contactId, request).thenApply(response -> response.body());
    }

    /**
     * Retrieve a specific omni-channel contact in an audience.
     */
    public CompletableFuture<AudiencesContact> getAudienceContact(
            String audienceId, String contactId, GetAudienceContactRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getAudienceContact(audienceId, contactId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Update an existing omni-channel contact.
     */
    public CompletableFuture<AudiencesContact> patchAudienceContact(String audienceId, String contactId) {
        return this.rawClient.patchAudienceContact(audienceId, contactId).thenApply(response -> response.body());
    }

    /**
     * Update an existing omni-channel contact.
     */
    public CompletableFuture<AudiencesContact> patchAudienceContact(
            String audienceId, String contactId, RequestOptions requestOptions) {
        return this.rawClient
                .patchAudienceContact(audienceId, contactId, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Update an existing omni-channel contact.
     */
    public CompletableFuture<AudiencesContact> patchAudienceContact(
            String audienceId, String contactId, PatchAudienceContactRequest request) {
        return this.rawClient
                .patchAudienceContact(audienceId, contactId, request)
                .thenApply(response -> response.body());
    }

    /**
     * Update an existing omni-channel contact.
     */
    public CompletableFuture<AudiencesContact> patchAudienceContact(
            String audienceId, String contactId, PatchAudienceContactRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .patchAudienceContact(audienceId, contactId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Archives a Contact.
     */
    public CompletableFuture<Void> postAudiencesContactsActionsArchive(String audienceId, String contactId) {
        return this.rawClient
                .postAudiencesContactsActionsArchive(audienceId, contactId)
                .thenApply(response -> response.body());
    }

    /**
     * Archives a Contact.
     */
    public CompletableFuture<Void> postAudiencesContactsActionsArchive(
            String audienceId, String contactId, RequestOptions requestOptions) {
        return this.rawClient
                .postAudiencesContactsActionsArchive(audienceId, contactId, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Archives a Contact.
     */
    public CompletableFuture<Void> postAudiencesContactsActionsArchive(
            String audienceId, String contactId, PostAudiencesContactsActionsArchiveRequest request) {
        return this.rawClient
                .postAudiencesContactsActionsArchive(audienceId, contactId, request)
                .thenApply(response -> response.body());
    }

    /**
     * Archives a Contact.
     */
    public CompletableFuture<Void> postAudiencesContactsActionsArchive(
            String audienceId,
            String contactId,
            PostAudiencesContactsActionsArchiveRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .postAudiencesContactsActionsArchive(audienceId, contactId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Forgets a Contact.
     */
    public CompletableFuture<Void> postAudiencesContactsActionsForget(String audienceId, String contactId) {
        return this.rawClient
                .postAudiencesContactsActionsForget(audienceId, contactId)
                .thenApply(response -> response.body());
    }

    /**
     * Forgets a Contact.
     */
    public CompletableFuture<Void> postAudiencesContactsActionsForget(
            String audienceId, String contactId, RequestOptions requestOptions) {
        return this.rawClient
                .postAudiencesContactsActionsForget(audienceId, contactId, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Forgets a Contact.
     */
    public CompletableFuture<Void> postAudiencesContactsActionsForget(
            String audienceId, String contactId, PostAudiencesContactsActionsForgetRequest request) {
        return this.rawClient
                .postAudiencesContactsActionsForget(audienceId, contactId, request)
                .thenApply(response -> response.body());
    }

    /**
     * Forgets a Contact.
     */
    public CompletableFuture<Void> postAudiencesContactsActionsForget(
            String audienceId,
            String contactId,
            PostAudiencesContactsActionsForgetRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .postAudiencesContactsActionsForget(audienceId, contactId, request, requestOptions)
                .thenApply(response -> response.body());
    }
}
