/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.automations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import com.mailchimp.marketing.types.AutomationWorkflow;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListAutomationsResponse.Builder.class)
public final class ListAutomationsResponse {
    private final Optional<List<ListAutomationsResponseLinksItem>> links;

    private final Optional<List<AutomationWorkflow>> automations;

    private final Optional<Integer> totalItems;

    private final Map<String, Object> additionalProperties;

    private ListAutomationsResponse(
            Optional<List<ListAutomationsResponseLinksItem>> links,
            Optional<List<AutomationWorkflow>> automations,
            Optional<Integer> totalItems,
            Map<String, Object> additionalProperties) {
        this.links = links;
        this.automations = automations;
        this.totalItems = totalItems;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A list of link types and descriptions for the API schema documents.
     */
    @JsonProperty("_links")
    public Optional<List<ListAutomationsResponseLinksItem>> getLinks() {
        return links;
    }

    /**
     * @return An array of objects, each representing an Automation workflow.
     */
    @JsonProperty("automations")
    public Optional<List<AutomationWorkflow>> getAutomations() {
        return automations;
    }

    /**
     * @return The total number of items matching the query regardless of pagination.
     */
    @JsonProperty("total_items")
    public Optional<Integer> getTotalItems() {
        return totalItems;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListAutomationsResponse && equalTo((ListAutomationsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListAutomationsResponse other) {
        return links.equals(other.links)
                && automations.equals(other.automations)
                && totalItems.equals(other.totalItems);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.links, this.automations, this.totalItems);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ListAutomationsResponseLinksItem>> links = Optional.empty();

        private Optional<List<AutomationWorkflow>> automations = Optional.empty();

        private Optional<Integer> totalItems = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListAutomationsResponse other) {
            links(other.getLinks());
            automations(other.getAutomations());
            totalItems(other.getTotalItems());
            return this;
        }

        /**
         * <p>A list of link types and descriptions for the API schema documents.</p>
         */
        @JsonSetter(value = "_links", nulls = Nulls.SKIP)
        public Builder links(Optional<List<ListAutomationsResponseLinksItem>> links) {
            this.links = links;
            return this;
        }

        public Builder links(List<ListAutomationsResponseLinksItem> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        /**
         * <p>An array of objects, each representing an Automation workflow.</p>
         */
        @JsonSetter(value = "automations", nulls = Nulls.SKIP)
        public Builder automations(Optional<List<AutomationWorkflow>> automations) {
            this.automations = automations;
            return this;
        }

        public Builder automations(List<AutomationWorkflow> automations) {
            this.automations = Optional.ofNullable(automations);
            return this;
        }

        /**
         * <p>The total number of items matching the query regardless of pagination.</p>
         */
        @JsonSetter(value = "total_items", nulls = Nulls.SKIP)
        public Builder totalItems(Optional<Integer> totalItems) {
            this.totalItems = totalItems;
            return this;
        }

        public Builder totalItems(Integer totalItems) {
            this.totalItems = Optional.ofNullable(totalItems);
            return this;
        }

        public ListAutomationsResponse build() {
            return new ListAutomationsResponse(links, automations, totalItems, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
