/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.reporting;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.mailchimp.marketing.core.ClientOptions;
import com.mailchimp.marketing.core.MailchimpClientApiException;
import com.mailchimp.marketing.core.MailchimpClientException;
import com.mailchimp.marketing.core.MailchimpClientHttpResponse;
import com.mailchimp.marketing.core.ObjectMappers;
import com.mailchimp.marketing.core.QueryStringMapper;
import com.mailchimp.marketing.core.RequestOptions;
import com.mailchimp.marketing.core.RetryInterceptor;
import com.mailchimp.marketing.core.pagination.SyncPagingIterable;
import com.mailchimp.marketing.resources.reporting.requests.GetFacebookAdReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.GetLandingPageReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.GetSurveyQuestionReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.GetSurveyReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.GetSurveyResponsReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.ListFacebookAdEcommerceProductActivityReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.ListFacebookAdsReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.ListLandingPagesReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.ListSurveyQuestionAnswersReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.ListSurveyQuestionsReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.ListSurveyResponsesReportingRequest;
import com.mailchimp.marketing.resources.reporting.requests.ListSurveysReportingRequest;
import com.mailchimp.marketing.resources.reporting.types.GetSurveyReportingResponse;
import com.mailchimp.marketing.resources.reporting.types.GetSurveyResponsReportingResponse;
import com.mailchimp.marketing.resources.reporting.types.ListFacebookAdEcommerceProductActivityReportingResponse;
import com.mailchimp.marketing.resources.reporting.types.ListFacebookAdEcommerceProductActivityReportingResponseProductsItem;
import com.mailchimp.marketing.resources.reporting.types.ListFacebookAdsReportingResponse;
import com.mailchimp.marketing.resources.reporting.types.ListLandingPagesReportingResponse;
import com.mailchimp.marketing.resources.reporting.types.ListReportingResponseItem;
import com.mailchimp.marketing.resources.reporting.types.ListSurveyQuestionAnswersReportingResponse;
import com.mailchimp.marketing.resources.reporting.types.ListSurveyQuestionsReportingResponse;
import com.mailchimp.marketing.resources.reporting.types.ListSurveyResponsesReportingResponse;
import com.mailchimp.marketing.resources.reporting.types.ListSurveysReportingResponse;
import com.mailchimp.marketing.resources.reporting.types.ListSurveysReportingResponseSurveysItem;
import com.mailchimp.marketing.types.LandingPageReport;
import com.mailchimp.marketing.types.ReportingFacebookAd;
import com.mailchimp.marketing.types.SurveyQuestionReport;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawReportingClient {
    protected final ClientOptions clientOptions;

    public RawReportingClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Get information about the reporting endpoint's resources.
     */
    public MailchimpClientHttpResponse<List<ListReportingResponseItem>> list() {
        return list(null);
    }

    /**
     * Get information about the reporting endpoint's resources.
     */
    public MailchimpClientHttpResponse<List<ListReportingResponseItem>> list(RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, new TypeReference<List<ListReportingResponseItem>>() {}),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get reports of Facebook ads.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ReportingFacebookAd>> listFacebookAds() {
        return listFacebookAds(ListFacebookAdsReportingRequest.builder().build());
    }

    /**
     * Get reports of Facebook ads.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ReportingFacebookAd>> listFacebookAds(
            RequestOptions requestOptions) {
        return listFacebookAds(ListFacebookAdsReportingRequest.builder().build(), requestOptions);
    }

    /**
     * Get reports of Facebook ads.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ReportingFacebookAd>> listFacebookAds(
            ListFacebookAdsReportingRequest request) {
        return listFacebookAds(request, null);
    }

    /**
     * Get reports of Facebook ads.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ReportingFacebookAd>> listFacebookAds(
            ListFacebookAdsReportingRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/facebook-ads");
        if (request.getCount().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "count", request.getCount().get(), false);
        }
        if (request.getOffset().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "offset", request.getOffset().get(), false);
        }
        if (request.getSortField().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sort_field", request.getSortField().get(), false);
        }
        if (request.getSortDir().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sort_dir", request.getSortDir().get(), false);
        }
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListFacebookAdsReportingResponse parsedResponse =
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListFacebookAdsReportingResponse.class);
                int newPageNumber =
                        request.getOffset().map((Integer page) -> page + 1).orElse(1);
                ListFacebookAdsReportingRequest nextRequest = ListFacebookAdsReportingRequest.builder()
                        .from(request)
                        .offset(newPageNumber)
                        .build();
                List<ReportingFacebookAd> result =
                        parsedResponse.getFacebookAds().orElse(Collections.emptyList());
                return new MailchimpClientHttpResponse<>(
                        new SyncPagingIterable<ReportingFacebookAd>(
                                true, result, parsedResponse, () -> listFacebookAds(nextRequest, requestOptions)
                                        .body()),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get report of a Facebook ad.
     */
    public MailchimpClientHttpResponse<ReportingFacebookAd> getFacebookAd(String outreachId) {
        return getFacebookAd(outreachId, GetFacebookAdReportingRequest.builder().build());
    }

    /**
     * Get report of a Facebook ad.
     */
    public MailchimpClientHttpResponse<ReportingFacebookAd> getFacebookAd(
            String outreachId, RequestOptions requestOptions) {
        return getFacebookAd(outreachId, GetFacebookAdReportingRequest.builder().build(), requestOptions);
    }

    /**
     * Get report of a Facebook ad.
     */
    public MailchimpClientHttpResponse<ReportingFacebookAd> getFacebookAd(
            String outreachId, GetFacebookAdReportingRequest request) {
        return getFacebookAd(outreachId, request, null);
    }

    /**
     * Get report of a Facebook ad.
     */
    public MailchimpClientHttpResponse<ReportingFacebookAd> getFacebookAd(
            String outreachId, GetFacebookAdReportingRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/facebook-ads")
                .addPathSegment(outreachId);
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ReportingFacebookAd.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get breakdown of product activity for an outreach.
     */
    public MailchimpClientHttpResponse<
                    SyncPagingIterable<ListFacebookAdEcommerceProductActivityReportingResponseProductsItem>>
            listFacebookAdEcommerceProductActivity(String outreachId) {
        return listFacebookAdEcommerceProductActivity(
                outreachId,
                ListFacebookAdEcommerceProductActivityReportingRequest.builder().build());
    }

    /**
     * Get breakdown of product activity for an outreach.
     */
    public MailchimpClientHttpResponse<
                    SyncPagingIterable<ListFacebookAdEcommerceProductActivityReportingResponseProductsItem>>
            listFacebookAdEcommerceProductActivity(String outreachId, RequestOptions requestOptions) {
        return listFacebookAdEcommerceProductActivity(
                outreachId,
                ListFacebookAdEcommerceProductActivityReportingRequest.builder().build(),
                requestOptions);
    }

    /**
     * Get breakdown of product activity for an outreach.
     */
    public MailchimpClientHttpResponse<
                    SyncPagingIterable<ListFacebookAdEcommerceProductActivityReportingResponseProductsItem>>
            listFacebookAdEcommerceProductActivity(
                    String outreachId, ListFacebookAdEcommerceProductActivityReportingRequest request) {
        return listFacebookAdEcommerceProductActivity(outreachId, request, null);
    }

    /**
     * Get breakdown of product activity for an outreach.
     */
    public MailchimpClientHttpResponse<
                    SyncPagingIterable<ListFacebookAdEcommerceProductActivityReportingResponseProductsItem>>
            listFacebookAdEcommerceProductActivity(
                    String outreachId,
                    ListFacebookAdEcommerceProductActivityReportingRequest request,
                    RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/facebook-ads")
                .addPathSegment(outreachId)
                .addPathSegments("ecommerce-product-activity");
        if (request.getCount().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "count", request.getCount().get(), false);
        }
        if (request.getOffset().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "offset", request.getOffset().get(), false);
        }
        if (request.getSortField().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sort_field", request.getSortField().get(), false);
        }
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListFacebookAdEcommerceProductActivityReportingResponse parsedResponse =
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, ListFacebookAdEcommerceProductActivityReportingResponse.class);
                int newPageNumber =
                        request.getOffset().map((Integer page) -> page + 1).orElse(1);
                ListFacebookAdEcommerceProductActivityReportingRequest nextRequest =
                        ListFacebookAdEcommerceProductActivityReportingRequest.builder()
                                .from(request)
                                .offset(newPageNumber)
                                .build();
                List<ListFacebookAdEcommerceProductActivityReportingResponseProductsItem> result =
                        parsedResponse.getProducts().orElse(Collections.emptyList());
                return new MailchimpClientHttpResponse<>(
                        new SyncPagingIterable<ListFacebookAdEcommerceProductActivityReportingResponseProductsItem>(
                                true, result, parsedResponse, () -> listFacebookAdEcommerceProductActivity(
                                                outreachId, nextRequest, requestOptions)
                                        .body()),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get reports of landing pages.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<LandingPageReport>> listLandingPages() {
        return listLandingPages(ListLandingPagesReportingRequest.builder().build());
    }

    /**
     * Get reports of landing pages.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<LandingPageReport>> listLandingPages(
            RequestOptions requestOptions) {
        return listLandingPages(ListLandingPagesReportingRequest.builder().build(), requestOptions);
    }

    /**
     * Get reports of landing pages.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<LandingPageReport>> listLandingPages(
            ListLandingPagesReportingRequest request) {
        return listLandingPages(request, null);
    }

    /**
     * Get reports of landing pages.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<LandingPageReport>> listLandingPages(
            ListLandingPagesReportingRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/landing-pages");
        if (request.getCount().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "count", request.getCount().get(), false);
        }
        if (request.getOffset().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "offset", request.getOffset().get(), false);
        }
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListLandingPagesReportingResponse parsedResponse = ObjectMappers.JSON_MAPPER.readValue(
                        responseBodyString, ListLandingPagesReportingResponse.class);
                int newPageNumber =
                        request.getOffset().map((Integer page) -> page + 1).orElse(1);
                ListLandingPagesReportingRequest nextRequest = ListLandingPagesReportingRequest.builder()
                        .from(request)
                        .offset(newPageNumber)
                        .build();
                List<LandingPageReport> result =
                        parsedResponse.getLandingPages().orElse(Collections.emptyList());
                return new MailchimpClientHttpResponse<>(
                        new SyncPagingIterable<LandingPageReport>(
                                true, result, parsedResponse, () -> listLandingPages(nextRequest, requestOptions)
                                        .body()),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get report of a landing page.
     */
    public MailchimpClientHttpResponse<LandingPageReport> getLandingPage(String outreachId) {
        return getLandingPage(
                outreachId, GetLandingPageReportingRequest.builder().build());
    }

    /**
     * Get report of a landing page.
     */
    public MailchimpClientHttpResponse<LandingPageReport> getLandingPage(
            String outreachId, RequestOptions requestOptions) {
        return getLandingPage(
                outreachId, GetLandingPageReportingRequest.builder().build(), requestOptions);
    }

    /**
     * Get report of a landing page.
     */
    public MailchimpClientHttpResponse<LandingPageReport> getLandingPage(
            String outreachId, GetLandingPageReportingRequest request) {
        return getLandingPage(outreachId, request, null);
    }

    /**
     * Get report of a landing page.
     */
    public MailchimpClientHttpResponse<LandingPageReport> getLandingPage(
            String outreachId, GetLandingPageReportingRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/landing-pages")
                .addPathSegment(outreachId);
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, LandingPageReport.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get reports for surveys.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ListSurveysReportingResponseSurveysItem>> listSurveys() {
        return listSurveys(ListSurveysReportingRequest.builder().build());
    }

    /**
     * Get reports for surveys.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ListSurveysReportingResponseSurveysItem>> listSurveys(
            RequestOptions requestOptions) {
        return listSurveys(ListSurveysReportingRequest.builder().build(), requestOptions);
    }

    /**
     * Get reports for surveys.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ListSurveysReportingResponseSurveysItem>> listSurveys(
            ListSurveysReportingRequest request) {
        return listSurveys(request, null);
    }

    /**
     * Get reports for surveys.
     */
    public MailchimpClientHttpResponse<SyncPagingIterable<ListSurveysReportingResponseSurveysItem>> listSurveys(
            ListSurveysReportingRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/surveys");
        if (request.getCount().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "count", request.getCount().get(), false);
        }
        if (request.getOffset().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "offset", request.getOffset().get(), false);
        }
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListSurveysReportingResponse parsedResponse =
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListSurveysReportingResponse.class);
                int newPageNumber =
                        request.getOffset().map((Integer page) -> page + 1).orElse(1);
                ListSurveysReportingRequest nextRequest = ListSurveysReportingRequest.builder()
                        .from(request)
                        .offset(newPageNumber)
                        .build();
                List<ListSurveysReportingResponseSurveysItem> result =
                        parsedResponse.getSurveys().orElse(Collections.emptyList());
                return new MailchimpClientHttpResponse<>(
                        new SyncPagingIterable<ListSurveysReportingResponseSurveysItem>(
                                true, result, parsedResponse, () -> listSurveys(nextRequest, requestOptions)
                                        .body()),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get report for a survey.
     */
    public MailchimpClientHttpResponse<GetSurveyReportingResponse> getSurvey(String surveyId) {
        return getSurvey(surveyId, GetSurveyReportingRequest.builder().build());
    }

    /**
     * Get report for a survey.
     */
    public MailchimpClientHttpResponse<GetSurveyReportingResponse> getSurvey(
            String surveyId, RequestOptions requestOptions) {
        return getSurvey(surveyId, GetSurveyReportingRequest.builder().build(), requestOptions);
    }

    /**
     * Get report for a survey.
     */
    public MailchimpClientHttpResponse<GetSurveyReportingResponse> getSurvey(
            String surveyId, GetSurveyReportingRequest request) {
        return getSurvey(surveyId, request, null);
    }

    /**
     * Get report for a survey.
     */
    public MailchimpClientHttpResponse<GetSurveyReportingResponse> getSurvey(
            String surveyId, GetSurveyReportingRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/surveys")
                .addPathSegment(surveyId);
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetSurveyReportingResponse.class),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get reports for survey questions.
     */
    public MailchimpClientHttpResponse<ListSurveyQuestionsReportingResponse> listSurveyQuestions(String surveyId) {
        return listSurveyQuestions(
                surveyId, ListSurveyQuestionsReportingRequest.builder().build());
    }

    /**
     * Get reports for survey questions.
     */
    public MailchimpClientHttpResponse<ListSurveyQuestionsReportingResponse> listSurveyQuestions(
            String surveyId, RequestOptions requestOptions) {
        return listSurveyQuestions(
                surveyId, ListSurveyQuestionsReportingRequest.builder().build(), requestOptions);
    }

    /**
     * Get reports for survey questions.
     */
    public MailchimpClientHttpResponse<ListSurveyQuestionsReportingResponse> listSurveyQuestions(
            String surveyId, ListSurveyQuestionsReportingRequest request) {
        return listSurveyQuestions(surveyId, request, null);
    }

    /**
     * Get reports for survey questions.
     */
    public MailchimpClientHttpResponse<ListSurveyQuestionsReportingResponse> listSurveyQuestions(
            String surveyId, ListSurveyQuestionsReportingRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/surveys")
                .addPathSegment(surveyId)
                .addPathSegments("questions");
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, ListSurveyQuestionsReportingResponse.class),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get report for a survey question.
     */
    public MailchimpClientHttpResponse<SurveyQuestionReport> getSurveyQuestion(String surveyId, String questionId) {
        return getSurveyQuestion(
                surveyId,
                questionId,
                GetSurveyQuestionReportingRequest.builder().build());
    }

    /**
     * Get report for a survey question.
     */
    public MailchimpClientHttpResponse<SurveyQuestionReport> getSurveyQuestion(
            String surveyId, String questionId, RequestOptions requestOptions) {
        return getSurveyQuestion(
                surveyId,
                questionId,
                GetSurveyQuestionReportingRequest.builder().build(),
                requestOptions);
    }

    /**
     * Get report for a survey question.
     */
    public MailchimpClientHttpResponse<SurveyQuestionReport> getSurveyQuestion(
            String surveyId, String questionId, GetSurveyQuestionReportingRequest request) {
        return getSurveyQuestion(surveyId, questionId, request, null);
    }

    /**
     * Get report for a survey question.
     */
    public MailchimpClientHttpResponse<SurveyQuestionReport> getSurveyQuestion(
            String surveyId,
            String questionId,
            GetSurveyQuestionReportingRequest request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/surveys")
                .addPathSegment(surveyId)
                .addPathSegments("questions")
                .addPathSegment(questionId);
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SurveyQuestionReport.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get answers for a survey question.
     */
    public MailchimpClientHttpResponse<ListSurveyQuestionAnswersReportingResponse> listSurveyQuestionAnswers(
            String surveyId, String questionId) {
        return listSurveyQuestionAnswers(
                surveyId,
                questionId,
                ListSurveyQuestionAnswersReportingRequest.builder().build());
    }

    /**
     * Get answers for a survey question.
     */
    public MailchimpClientHttpResponse<ListSurveyQuestionAnswersReportingResponse> listSurveyQuestionAnswers(
            String surveyId, String questionId, RequestOptions requestOptions) {
        return listSurveyQuestionAnswers(
                surveyId,
                questionId,
                ListSurveyQuestionAnswersReportingRequest.builder().build(),
                requestOptions);
    }

    /**
     * Get answers for a survey question.
     */
    public MailchimpClientHttpResponse<ListSurveyQuestionAnswersReportingResponse> listSurveyQuestionAnswers(
            String surveyId, String questionId, ListSurveyQuestionAnswersReportingRequest request) {
        return listSurveyQuestionAnswers(surveyId, questionId, request, null);
    }

    /**
     * Get answers for a survey question.
     */
    public MailchimpClientHttpResponse<ListSurveyQuestionAnswersReportingResponse> listSurveyQuestionAnswers(
            String surveyId,
            String questionId,
            ListSurveyQuestionAnswersReportingRequest request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/surveys")
                .addPathSegment(surveyId)
                .addPathSegments("questions")
                .addPathSegment(questionId)
                .addPathSegments("answers");
        if (request.getRespondentFamiliarityIs().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "respondent_familiarity_is",
                    request.getRespondentFamiliarityIs().get(),
                    false);
        }
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, ListSurveyQuestionAnswersReportingResponse.class),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get responses to a survey.
     */
    public MailchimpClientHttpResponse<ListSurveyResponsesReportingResponse> listSurveyResponses(String surveyId) {
        return listSurveyResponses(
                surveyId, ListSurveyResponsesReportingRequest.builder().build());
    }

    /**
     * Get responses to a survey.
     */
    public MailchimpClientHttpResponse<ListSurveyResponsesReportingResponse> listSurveyResponses(
            String surveyId, RequestOptions requestOptions) {
        return listSurveyResponses(
                surveyId, ListSurveyResponsesReportingRequest.builder().build(), requestOptions);
    }

    /**
     * Get responses to a survey.
     */
    public MailchimpClientHttpResponse<ListSurveyResponsesReportingResponse> listSurveyResponses(
            String surveyId, ListSurveyResponsesReportingRequest request) {
        return listSurveyResponses(surveyId, request, null);
    }

    /**
     * Get responses to a survey.
     */
    public MailchimpClientHttpResponse<ListSurveyResponsesReportingResponse> listSurveyResponses(
            String surveyId, ListSurveyResponsesReportingRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/surveys")
                .addPathSegment(surveyId)
                .addPathSegments("responses");
        if (request.getAnsweredQuestion().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "answered_question", request.getAnsweredQuestion().get(), false);
        }
        if (request.getChoseAnswer().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "chose_answer", request.getChoseAnswer().get(), false);
        }
        if (request.getRespondentFamiliarityIs().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "respondent_familiarity_is",
                    request.getRespondentFamiliarityIs().get(),
                    false);
        }
        if (request.getFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "fields", request.getFields().get(), true);
        }
        if (request.getExcludeFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "exclude_fields", request.getExcludeFields().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, ListSurveyResponsesReportingResponse.class),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get a single survey response.
     */
    public MailchimpClientHttpResponse<GetSurveyResponsReportingResponse> getSurveyRespons(
            String surveyId, String responseId) {
        return getSurveyRespons(
                surveyId, responseId, GetSurveyResponsReportingRequest.builder().build());
    }

    /**
     * Get a single survey response.
     */
    public MailchimpClientHttpResponse<GetSurveyResponsReportingResponse> getSurveyRespons(
            String surveyId, String responseId, RequestOptions requestOptions) {
        return getSurveyRespons(
                surveyId, responseId, GetSurveyResponsReportingRequest.builder().build(), requestOptions);
    }

    /**
     * Get a single survey response.
     */
    public MailchimpClientHttpResponse<GetSurveyResponsReportingResponse> getSurveyRespons(
            String surveyId, String responseId, GetSurveyResponsReportingRequest request) {
        return getSurveyRespons(surveyId, responseId, request, null);
    }

    /**
     * Get a single survey response.
     */
    public MailchimpClientHttpResponse<GetSurveyResponsReportingResponse> getSurveyRespons(
            String surveyId,
            String responseId,
            GetSurveyResponsReportingRequest request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("3.0/reporting/surveys")
                .addPathSegment(surveyId)
                .addPathSegments("responses")
                .addPathSegment(responseId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MailchimpClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, GetSurveyResponsReportingResponse.class),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MailchimpClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MailchimpClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MailchimpClientException("Network error executing HTTP request", e);
        }
    }
}
