/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.lists.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateSignupFormListsRequestStylesItem.Builder.class)
public final class CreateSignupFormListsRequestStylesItem {
    private final Optional<List<CreateSignupFormListsRequestStylesItemOptionsItem>> options;

    private final Optional<CreateSignupFormListsRequestStylesItemSelector> selector;

    private final Map<String, Object> additionalProperties;

    private CreateSignupFormListsRequestStylesItem(
            Optional<List<CreateSignupFormListsRequestStylesItemOptionsItem>> options,
            Optional<CreateSignupFormListsRequestStylesItemSelector> selector,
            Map<String, Object> additionalProperties) {
        this.options = options;
        this.selector = selector;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A collection of options for a selector.
     */
    @JsonProperty("options")
    public Optional<List<CreateSignupFormListsRequestStylesItemOptionsItem>> getOptions() {
        return options;
    }

    /**
     * @return A string that identifies the element selector.
     */
    @JsonProperty("selector")
    public Optional<CreateSignupFormListsRequestStylesItemSelector> getSelector() {
        return selector;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateSignupFormListsRequestStylesItem
                && equalTo((CreateSignupFormListsRequestStylesItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateSignupFormListsRequestStylesItem other) {
        return options.equals(other.options) && selector.equals(other.selector);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.options, this.selector);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<CreateSignupFormListsRequestStylesItemOptionsItem>> options = Optional.empty();

        private Optional<CreateSignupFormListsRequestStylesItemSelector> selector = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateSignupFormListsRequestStylesItem other) {
            options(other.getOptions());
            selector(other.getSelector());
            return this;
        }

        /**
         * <p>A collection of options for a selector.</p>
         */
        @JsonSetter(value = "options", nulls = Nulls.SKIP)
        public Builder options(Optional<List<CreateSignupFormListsRequestStylesItemOptionsItem>> options) {
            this.options = options;
            return this;
        }

        public Builder options(List<CreateSignupFormListsRequestStylesItemOptionsItem> options) {
            this.options = Optional.ofNullable(options);
            return this;
        }

        /**
         * <p>A string that identifies the element selector.</p>
         */
        @JsonSetter(value = "selector", nulls = Nulls.SKIP)
        public Builder selector(Optional<CreateSignupFormListsRequestStylesItemSelector> selector) {
            this.selector = selector;
            return this;
        }

        public Builder selector(CreateSignupFormListsRequestStylesItemSelector selector) {
            this.selector = Optional.ofNullable(selector);
            return this;
        }

        public CreateSignupFormListsRequestStylesItem build() {
            return new CreateSignupFormListsRequestStylesItem(options, selector, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
