/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.lists.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListLocationsListsResponse.Builder.class)
public final class ListLocationsListsResponse {
    private final Optional<List<ListLocationsListsResponseLinksItem>> links;

    private final Optional<String> listId;

    private final Optional<List<ListLocationsListsResponseLocationsItem>> locations;

    private final Optional<Integer> totalItems;

    private final Map<String, Object> additionalProperties;

    private ListLocationsListsResponse(
            Optional<List<ListLocationsListsResponseLinksItem>> links,
            Optional<String> listId,
            Optional<List<ListLocationsListsResponseLocationsItem>> locations,
            Optional<Integer> totalItems,
            Map<String, Object> additionalProperties) {
        this.links = links;
        this.listId = listId;
        this.locations = locations;
        this.totalItems = totalItems;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A list of link types and descriptions for the API schema documents.
     */
    @JsonProperty("_links")
    public Optional<List<ListLocationsListsResponseLinksItem>> getLinks() {
        return links;
    }

    /**
     * @return The unique id for the list.
     */
    @JsonProperty("list_id")
    public Optional<String> getListId() {
        return listId;
    }

    /**
     * @return An array of objects, each representing a list's top subscriber locations.
     */
    @JsonProperty("locations")
    public Optional<List<ListLocationsListsResponseLocationsItem>> getLocations() {
        return locations;
    }

    /**
     * @return The total number of items matching the query regardless of pagination.
     */
    @JsonProperty("total_items")
    public Optional<Integer> getTotalItems() {
        return totalItems;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListLocationsListsResponse && equalTo((ListLocationsListsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListLocationsListsResponse other) {
        return links.equals(other.links)
                && listId.equals(other.listId)
                && locations.equals(other.locations)
                && totalItems.equals(other.totalItems);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.links, this.listId, this.locations, this.totalItems);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ListLocationsListsResponseLinksItem>> links = Optional.empty();

        private Optional<String> listId = Optional.empty();

        private Optional<List<ListLocationsListsResponseLocationsItem>> locations = Optional.empty();

        private Optional<Integer> totalItems = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListLocationsListsResponse other) {
            links(other.getLinks());
            listId(other.getListId());
            locations(other.getLocations());
            totalItems(other.getTotalItems());
            return this;
        }

        /**
         * <p>A list of link types and descriptions for the API schema documents.</p>
         */
        @JsonSetter(value = "_links", nulls = Nulls.SKIP)
        public Builder links(Optional<List<ListLocationsListsResponseLinksItem>> links) {
            this.links = links;
            return this;
        }

        public Builder links(List<ListLocationsListsResponseLinksItem> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        /**
         * <p>The unique id for the list.</p>
         */
        @JsonSetter(value = "list_id", nulls = Nulls.SKIP)
        public Builder listId(Optional<String> listId) {
            this.listId = listId;
            return this;
        }

        public Builder listId(String listId) {
            this.listId = Optional.ofNullable(listId);
            return this;
        }

        /**
         * <p>An array of objects, each representing a list's top subscriber locations.</p>
         */
        @JsonSetter(value = "locations", nulls = Nulls.SKIP)
        public Builder locations(Optional<List<ListLocationsListsResponseLocationsItem>> locations) {
            this.locations = locations;
            return this;
        }

        public Builder locations(List<ListLocationsListsResponseLocationsItem> locations) {
            this.locations = Optional.ofNullable(locations);
            return this;
        }

        /**
         * <p>The total number of items matching the query regardless of pagination.</p>
         */
        @JsonSetter(value = "total_items", nulls = Nulls.SKIP)
        public Builder totalItems(Optional<Integer> totalItems) {
            this.totalItems = totalItems;
            return this;
        }

        public Builder totalItems(Integer totalItems) {
            this.totalItems = Optional.ofNullable(totalItems);
            return this;
        }

        public ListLocationsListsResponse build() {
            return new ListLocationsListsResponse(links, listId, locations, totalItems, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
