/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.lists.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ListMemberNotesListsRequestSortDir {
    public static final ListMemberNotesListsRequestSortDir DESC =
            new ListMemberNotesListsRequestSortDir(Value.DESC, "DESC");

    public static final ListMemberNotesListsRequestSortDir ASC =
            new ListMemberNotesListsRequestSortDir(Value.ASC, "ASC");

    private final Value value;

    private final String string;

    ListMemberNotesListsRequestSortDir(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ListMemberNotesListsRequestSortDir
                        && this.string.equals(((ListMemberNotesListsRequestSortDir) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DESC:
                return visitor.visitDesc();
            case ASC:
                return visitor.visitAsc();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListMemberNotesListsRequestSortDir valueOf(String value) {
        switch (value) {
            case "DESC":
                return DESC;
            case "ASC":
                return ASC;
            default:
                return new ListMemberNotesListsRequestSortDir(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ASC,

        DESC,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAsc();

        T visitDesc();

        T visitUnknown(String unknownType);
    }
}
