/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.lists.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListMemberActivityListsResponseActivityItem.Builder.class)
public final class ListMemberActivityListsResponseActivityItem {
    private final Optional<String> action;

    private final Optional<String> campaignId;

    private final Optional<String> parentCampaign;

    private final Optional<OffsetDateTime> timestamp;

    private final Optional<String> title;

    private final Optional<String> type;

    private final Optional<String> url;

    private final Map<String, Object> additionalProperties;

    private ListMemberActivityListsResponseActivityItem(
            Optional<String> action,
            Optional<String> campaignId,
            Optional<String> parentCampaign,
            Optional<OffsetDateTime> timestamp,
            Optional<String> title,
            Optional<String> type,
            Optional<String> url,
            Map<String, Object> additionalProperties) {
        this.action = action;
        this.campaignId = campaignId;
        this.parentCampaign = parentCampaign;
        this.timestamp = timestamp;
        this.title = title;
        this.type = type;
        this.url = url;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The type of action recorded for the subscriber.
     */
    @JsonProperty("action")
    public Optional<String> getAction() {
        return action;
    }

    /**
     * @return The web-based ID for the campaign.
     */
    @JsonProperty("campaign_id")
    public Optional<String> getCampaignId() {
        return campaignId;
    }

    /**
     * @return The ID of the parent campaign.
     */
    @JsonProperty("parent_campaign")
    public Optional<String> getParentCampaign() {
        return parentCampaign;
    }

    /**
     * @return The date and time recorded for the action.
     */
    @JsonProperty("timestamp")
    public Optional<OffsetDateTime> getTimestamp() {
        return timestamp;
    }

    /**
     * @return If set, the campaign's title.
     */
    @JsonProperty("title")
    public Optional<String> getTitle() {
        return title;
    }

    /**
     * @return The type of campaign that was sent.
     */
    @JsonProperty("type")
    public Optional<String> getType() {
        return type;
    }

    /**
     * @return For clicks, the URL the subscriber clicked on.
     */
    @JsonProperty("url")
    public Optional<String> getUrl() {
        return url;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListMemberActivityListsResponseActivityItem
                && equalTo((ListMemberActivityListsResponseActivityItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListMemberActivityListsResponseActivityItem other) {
        return action.equals(other.action)
                && campaignId.equals(other.campaignId)
                && parentCampaign.equals(other.parentCampaign)
                && timestamp.equals(other.timestamp)
                && title.equals(other.title)
                && type.equals(other.type)
                && url.equals(other.url);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.action, this.campaignId, this.parentCampaign, this.timestamp, this.title, this.type, this.url);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> action = Optional.empty();

        private Optional<String> campaignId = Optional.empty();

        private Optional<String> parentCampaign = Optional.empty();

        private Optional<OffsetDateTime> timestamp = Optional.empty();

        private Optional<String> title = Optional.empty();

        private Optional<String> type = Optional.empty();

        private Optional<String> url = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListMemberActivityListsResponseActivityItem other) {
            action(other.getAction());
            campaignId(other.getCampaignId());
            parentCampaign(other.getParentCampaign());
            timestamp(other.getTimestamp());
            title(other.getTitle());
            type(other.getType());
            url(other.getUrl());
            return this;
        }

        /**
         * <p>The type of action recorded for the subscriber.</p>
         */
        @JsonSetter(value = "action", nulls = Nulls.SKIP)
        public Builder action(Optional<String> action) {
            this.action = action;
            return this;
        }

        public Builder action(String action) {
            this.action = Optional.ofNullable(action);
            return this;
        }

        /**
         * <p>The web-based ID for the campaign.</p>
         */
        @JsonSetter(value = "campaign_id", nulls = Nulls.SKIP)
        public Builder campaignId(Optional<String> campaignId) {
            this.campaignId = campaignId;
            return this;
        }

        public Builder campaignId(String campaignId) {
            this.campaignId = Optional.ofNullable(campaignId);
            return this;
        }

        /**
         * <p>The ID of the parent campaign.</p>
         */
        @JsonSetter(value = "parent_campaign", nulls = Nulls.SKIP)
        public Builder parentCampaign(Optional<String> parentCampaign) {
            this.parentCampaign = parentCampaign;
            return this;
        }

        public Builder parentCampaign(String parentCampaign) {
            this.parentCampaign = Optional.ofNullable(parentCampaign);
            return this;
        }

        /**
         * <p>The date and time recorded for the action.</p>
         */
        @JsonSetter(value = "timestamp", nulls = Nulls.SKIP)
        public Builder timestamp(Optional<OffsetDateTime> timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        public Builder timestamp(OffsetDateTime timestamp) {
            this.timestamp = Optional.ofNullable(timestamp);
            return this;
        }

        /**
         * <p>If set, the campaign's title.</p>
         */
        @JsonSetter(value = "title", nulls = Nulls.SKIP)
        public Builder title(Optional<String> title) {
            this.title = title;
            return this;
        }

        public Builder title(String title) {
            this.title = Optional.ofNullable(title);
            return this;
        }

        /**
         * <p>The type of campaign that was sent.</p>
         */
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<String> type) {
            this.type = type;
            return this;
        }

        public Builder type(String type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * <p>For clicks, the URL the subscriber clicked on.</p>
         */
        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public Builder url(Optional<String> url) {
            this.url = url;
            return this;
        }

        public Builder url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        public ListMemberActivityListsResponseActivityItem build() {
            return new ListMemberActivityListsResponseActivityItem(
                    action, campaignId, parentCampaign, timestamp, title, type, url, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
