/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.lists.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import com.mailchimp.marketing.types.SegmentTypeItem;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateSegmentListsRequestOptions.Builder.class)
public final class UpdateSegmentListsRequestOptions {
    private final Optional<List<SegmentTypeItem>> conditions;

    private final Optional<UpdateSegmentListsRequestOptionsMatch> match;

    private final Map<String, Object> additionalProperties;

    private UpdateSegmentListsRequestOptions(
            Optional<List<SegmentTypeItem>> conditions,
            Optional<UpdateSegmentListsRequestOptionsMatch> match,
            Map<String, Object> additionalProperties) {
        this.conditions = conditions;
        this.match = match;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("conditions")
    public Optional<List<SegmentTypeItem>> getConditions() {
        return conditions;
    }

    /**
     * @return Match type.
     */
    @JsonProperty("match")
    public Optional<UpdateSegmentListsRequestOptionsMatch> getMatch() {
        return match;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateSegmentListsRequestOptions && equalTo((UpdateSegmentListsRequestOptions) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateSegmentListsRequestOptions other) {
        return conditions.equals(other.conditions) && match.equals(other.match);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.conditions, this.match);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<SegmentTypeItem>> conditions = Optional.empty();

        private Optional<UpdateSegmentListsRequestOptionsMatch> match = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateSegmentListsRequestOptions other) {
            conditions(other.getConditions());
            match(other.getMatch());
            return this;
        }

        @JsonSetter(value = "conditions", nulls = Nulls.SKIP)
        public Builder conditions(Optional<List<SegmentTypeItem>> conditions) {
            this.conditions = conditions;
            return this;
        }

        public Builder conditions(List<SegmentTypeItem> conditions) {
            this.conditions = Optional.ofNullable(conditions);
            return this;
        }

        /**
         * <p>Match type.</p>
         */
        @JsonSetter(value = "match", nulls = Nulls.SKIP)
        public Builder match(Optional<UpdateSegmentListsRequestOptionsMatch> match) {
            this.match = match;
            return this;
        }

        public Builder match(UpdateSegmentListsRequestOptionsMatch match) {
            this.match = Optional.ofNullable(match);
            return this;
        }

        public UpdateSegmentListsRequestOptions build() {
            return new UpdateSegmentListsRequestOptions(conditions, match, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
