/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.lists.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class UpsertMemberListsRequestTimestampOptOne {
    public static final UpsertMemberListsRequestTimestampOptOne EMPTY =
            new UpsertMemberListsRequestTimestampOptOne(Value.EMPTY, "");

    private final Value value;

    private final String string;

    UpsertMemberListsRequestTimestampOptOne(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof UpsertMemberListsRequestTimestampOptOne
                        && this.string.equals(((UpsertMemberListsRequestTimestampOptOne) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case EMPTY:
                return visitor.visitEmpty();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static UpsertMemberListsRequestTimestampOptOne valueOf(String value) {
        switch (value) {
            case "":
                return EMPTY;
            default:
                return new UpsertMemberListsRequestTimestampOptOne(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        EMPTY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitEmpty();

        T visitUnknown(String unknownType);
    }
}
