/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.lists.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpsertMemberListsRequestLocation.Builder.class)
public final class UpsertMemberListsRequestLocation {
    private final Optional<UpsertMemberListsRequestLocationLatitude> latitude;

    private final Optional<UpsertMemberListsRequestLocationLongitude> longitude;

    private final Map<String, Object> additionalProperties;

    private UpsertMemberListsRequestLocation(
            Optional<UpsertMemberListsRequestLocationLatitude> latitude,
            Optional<UpsertMemberListsRequestLocationLongitude> longitude,
            Map<String, Object> additionalProperties) {
        this.latitude = latitude;
        this.longitude = longitude;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("latitude")
    public Optional<UpsertMemberListsRequestLocationLatitude> getLatitude() {
        return latitude;
    }

    @JsonProperty("longitude")
    public Optional<UpsertMemberListsRequestLocationLongitude> getLongitude() {
        return longitude;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpsertMemberListsRequestLocation && equalTo((UpsertMemberListsRequestLocation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpsertMemberListsRequestLocation other) {
        return latitude.equals(other.latitude) && longitude.equals(other.longitude);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.latitude, this.longitude);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<UpsertMemberListsRequestLocationLatitude> latitude = Optional.empty();

        private Optional<UpsertMemberListsRequestLocationLongitude> longitude = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpsertMemberListsRequestLocation other) {
            latitude(other.getLatitude());
            longitude(other.getLongitude());
            return this;
        }

        @JsonSetter(value = "latitude", nulls = Nulls.SKIP)
        public Builder latitude(Optional<UpsertMemberListsRequestLocationLatitude> latitude) {
            this.latitude = latitude;
            return this;
        }

        public Builder latitude(UpsertMemberListsRequestLocationLatitude latitude) {
            this.latitude = Optional.ofNullable(latitude);
            return this;
        }

        @JsonSetter(value = "longitude", nulls = Nulls.SKIP)
        public Builder longitude(Optional<UpsertMemberListsRequestLocationLongitude> longitude) {
            this.longitude = longitude;
            return this;
        }

        public Builder longitude(UpsertMemberListsRequestLocationLongitude longitude) {
            this.longitude = Optional.ofNullable(longitude);
            return this;
        }

        public UpsertMemberListsRequestLocation build() {
            return new UpsertMemberListsRequestLocation(latitude, longitude, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
