/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.templatefolders;

import com.mailchimp.marketing.core.ClientOptions;
import com.mailchimp.marketing.core.RequestOptions;
import com.mailchimp.marketing.core.pagination.SyncPagingIterable;
import com.mailchimp.marketing.resources.templatefolders.requests.CreateTemplateFoldersRequest;
import com.mailchimp.marketing.resources.templatefolders.requests.DeleteTemplateFoldersRequest;
import com.mailchimp.marketing.resources.templatefolders.requests.GetTemplateFoldersRequest;
import com.mailchimp.marketing.resources.templatefolders.requests.ListTemplateFoldersRequest;
import com.mailchimp.marketing.resources.templatefolders.requests.UpdateTemplateFoldersRequest;
import com.mailchimp.marketing.resources.templatefolders.types.CreateTemplateFoldersResponse;
import com.mailchimp.marketing.resources.templatefolders.types.GetTemplateFoldersResponse;
import com.mailchimp.marketing.resources.templatefolders.types.ListTemplateFoldersResponseFoldersItem;
import com.mailchimp.marketing.resources.templatefolders.types.UpdateTemplateFoldersResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncTemplateFoldersClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawTemplateFoldersClient rawClient;

    public AsyncTemplateFoldersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawTemplateFoldersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawTemplateFoldersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get all folders used to organize templates.
     */
    public CompletableFuture<SyncPagingIterable<ListTemplateFoldersResponseFoldersItem>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Get all folders used to organize templates.
     */
    public CompletableFuture<SyncPagingIterable<ListTemplateFoldersResponseFoldersItem>> list(
            RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get all folders used to organize templates.
     */
    public CompletableFuture<SyncPagingIterable<ListTemplateFoldersResponseFoldersItem>> list(
            ListTemplateFoldersRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Get all folders used to organize templates.
     */
    public CompletableFuture<SyncPagingIterable<ListTemplateFoldersResponseFoldersItem>> list(
            ListTemplateFoldersRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create a new template folder.
     */
    public CompletableFuture<CreateTemplateFoldersResponse> create(CreateTemplateFoldersRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Create a new template folder.
     */
    public CompletableFuture<CreateTemplateFoldersResponse> create(
            CreateTemplateFoldersRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get information about a specific folder used to organize templates.
     */
    public CompletableFuture<GetTemplateFoldersResponse> get(String folderId) {
        return this.rawClient.get(folderId).thenApply(response -> response.body());
    }

    /**
     * Get information about a specific folder used to organize templates.
     */
    public CompletableFuture<GetTemplateFoldersResponse> get(String folderId, RequestOptions requestOptions) {
        return this.rawClient.get(folderId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get information about a specific folder used to organize templates.
     */
    public CompletableFuture<GetTemplateFoldersResponse> get(String folderId, GetTemplateFoldersRequest request) {
        return this.rawClient.get(folderId, request).thenApply(response -> response.body());
    }

    /**
     * Get information about a specific folder used to organize templates.
     */
    public CompletableFuture<GetTemplateFoldersResponse> get(
            String folderId, GetTemplateFoldersRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(folderId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Delete a specific template folder, and mark all the templates in the folder as 'unfiled'.
     */
    public CompletableFuture<Void> delete(String folderId) {
        return this.rawClient.delete(folderId).thenApply(response -> response.body());
    }

    /**
     * Delete a specific template folder, and mark all the templates in the folder as 'unfiled'.
     */
    public CompletableFuture<Void> delete(String folderId, RequestOptions requestOptions) {
        return this.rawClient.delete(folderId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Delete a specific template folder, and mark all the templates in the folder as 'unfiled'.
     */
    public CompletableFuture<Void> delete(String folderId, DeleteTemplateFoldersRequest request) {
        return this.rawClient.delete(folderId, request).thenApply(response -> response.body());
    }

    /**
     * Delete a specific template folder, and mark all the templates in the folder as 'unfiled'.
     */
    public CompletableFuture<Void> delete(
            String folderId, DeleteTemplateFoldersRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(folderId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Update a specific folder used to organize templates.
     */
    public CompletableFuture<UpdateTemplateFoldersResponse> update(
            String folderId, UpdateTemplateFoldersRequest request) {
        return this.rawClient.update(folderId, request).thenApply(response -> response.body());
    }

    /**
     * Update a specific folder used to organize templates.
     */
    public CompletableFuture<UpdateTemplateFoldersResponse> update(
            String folderId, UpdateTemplateFoldersRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(folderId, request, requestOptions).thenApply(response -> response.body());
    }
}
