/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.reporting.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import com.mailchimp.marketing.types.ReportingFacebookAd;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListFacebookAdsReportingResponse.Builder.class)
public final class ListFacebookAdsReportingResponse {
    private final Optional<List<ListFacebookAdsReportingResponseLinksItem>> links;

    private final Optional<List<ReportingFacebookAd>> facebookAds;

    private final Optional<Integer> totalItems;

    private final Map<String, Object> additionalProperties;

    private ListFacebookAdsReportingResponse(
            Optional<List<ListFacebookAdsReportingResponseLinksItem>> links,
            Optional<List<ReportingFacebookAd>> facebookAds,
            Optional<Integer> totalItems,
            Map<String, Object> additionalProperties) {
        this.links = links;
        this.facebookAds = facebookAds;
        this.totalItems = totalItems;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A list of link types and descriptions for the API schema documents.
     */
    @JsonProperty("_links")
    public Optional<List<ListFacebookAdsReportingResponseLinksItem>> getLinks() {
        return links;
    }

    @JsonProperty("facebook_ads")
    public Optional<List<ReportingFacebookAd>> getFacebookAds() {
        return facebookAds;
    }

    /**
     * @return The total number of items matching the query regardless of pagination.
     */
    @JsonProperty("total_items")
    public Optional<Integer> getTotalItems() {
        return totalItems;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListFacebookAdsReportingResponse && equalTo((ListFacebookAdsReportingResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListFacebookAdsReportingResponse other) {
        return links.equals(other.links)
                && facebookAds.equals(other.facebookAds)
                && totalItems.equals(other.totalItems);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.links, this.facebookAds, this.totalItems);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ListFacebookAdsReportingResponseLinksItem>> links = Optional.empty();

        private Optional<List<ReportingFacebookAd>> facebookAds = Optional.empty();

        private Optional<Integer> totalItems = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListFacebookAdsReportingResponse other) {
            links(other.getLinks());
            facebookAds(other.getFacebookAds());
            totalItems(other.getTotalItems());
            return this;
        }

        /**
         * <p>A list of link types and descriptions for the API schema documents.</p>
         */
        @JsonSetter(value = "_links", nulls = Nulls.SKIP)
        public Builder links(Optional<List<ListFacebookAdsReportingResponseLinksItem>> links) {
            this.links = links;
            return this;
        }

        public Builder links(List<ListFacebookAdsReportingResponseLinksItem> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        @JsonSetter(value = "facebook_ads", nulls = Nulls.SKIP)
        public Builder facebookAds(Optional<List<ReportingFacebookAd>> facebookAds) {
            this.facebookAds = facebookAds;
            return this;
        }

        public Builder facebookAds(List<ReportingFacebookAd> facebookAds) {
            this.facebookAds = Optional.ofNullable(facebookAds);
            return this;
        }

        /**
         * <p>The total number of items matching the query regardless of pagination.</p>
         */
        @JsonSetter(value = "total_items", nulls = Nulls.SKIP)
        public Builder totalItems(Optional<Integer> totalItems) {
            this.totalItems = totalItems;
            return this;
        }

        public Builder totalItems(Integer totalItems) {
            this.totalItems = Optional.ofNullable(totalItems);
            return this;
        }

        public ListFacebookAdsReportingResponse build() {
            return new ListFacebookAdsReportingResponse(links, facebookAds, totalItems, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
