/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.authorizedapps;

import com.mailchimp.marketing.core.ClientOptions;
import com.mailchimp.marketing.core.RequestOptions;
import com.mailchimp.marketing.core.pagination.SyncPagingIterable;
import com.mailchimp.marketing.resources.authorizedapps.requests.GetAuthorizedAppsRequest;
import com.mailchimp.marketing.resources.authorizedapps.requests.ListAuthorizedAppsRequest;
import com.mailchimp.marketing.resources.authorizedapps.types.GetAuthorizedAppsResponse;
import com.mailchimp.marketing.resources.authorizedapps.types.ListAuthorizedAppsResponseAppsItem;

public class AuthorizedAppsClient {
    protected final ClientOptions clientOptions;

    private final RawAuthorizedAppsClient rawClient;

    public AuthorizedAppsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAuthorizedAppsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAuthorizedAppsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get a list of an account's registered, connected applications.
     */
    public SyncPagingIterable<ListAuthorizedAppsResponseAppsItem> list() {
        return this.rawClient.list().body();
    }

    /**
     * Get a list of an account's registered, connected applications.
     */
    public SyncPagingIterable<ListAuthorizedAppsResponseAppsItem> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Get a list of an account's registered, connected applications.
     */
    public SyncPagingIterable<ListAuthorizedAppsResponseAppsItem> list(ListAuthorizedAppsRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Get a list of an account's registered, connected applications.
     */
    public SyncPagingIterable<ListAuthorizedAppsResponseAppsItem> list(
            ListAuthorizedAppsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Get information about a specific authorized application.
     */
    public GetAuthorizedAppsResponse get(String appId) {
        return this.rawClient.get(appId).body();
    }

    /**
     * Get information about a specific authorized application.
     */
    public GetAuthorizedAppsResponse get(String appId, RequestOptions requestOptions) {
        return this.rawClient.get(appId, requestOptions).body();
    }

    /**
     * Get information about a specific authorized application.
     */
    public GetAuthorizedAppsResponse get(String appId, GetAuthorizedAppsRequest request) {
        return this.rawClient.get(appId, request).body();
    }

    /**
     * Get information about a specific authorized application.
     */
    public GetAuthorizedAppsResponse get(
            String appId, GetAuthorizedAppsRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(appId, request, requestOptions).body();
    }
}
