/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.reports.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ListClickDetailMembersReportsResponseLinksItemMethod {
    public static final ListClickDetailMembersReportsResponseLinksItemMethod OPTIONS =
            new ListClickDetailMembersReportsResponseLinksItemMethod(Value.OPTIONS, "OPTIONS");

    public static final ListClickDetailMembersReportsResponseLinksItemMethod GET =
            new ListClickDetailMembersReportsResponseLinksItemMethod(Value.GET, "GET");

    public static final ListClickDetailMembersReportsResponseLinksItemMethod PUT =
            new ListClickDetailMembersReportsResponseLinksItemMethod(Value.PUT, "PUT");

    public static final ListClickDetailMembersReportsResponseLinksItemMethod PATCH =
            new ListClickDetailMembersReportsResponseLinksItemMethod(Value.PATCH, "PATCH");

    public static final ListClickDetailMembersReportsResponseLinksItemMethod DELETE =
            new ListClickDetailMembersReportsResponseLinksItemMethod(Value.DELETE, "DELETE");

    public static final ListClickDetailMembersReportsResponseLinksItemMethod HEAD =
            new ListClickDetailMembersReportsResponseLinksItemMethod(Value.HEAD, "HEAD");

    public static final ListClickDetailMembersReportsResponseLinksItemMethod POST =
            new ListClickDetailMembersReportsResponseLinksItemMethod(Value.POST, "POST");

    private final Value value;

    private final String string;

    ListClickDetailMembersReportsResponseLinksItemMethod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ListClickDetailMembersReportsResponseLinksItemMethod
                        && this.string.equals(((ListClickDetailMembersReportsResponseLinksItemMethod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OPTIONS:
                return visitor.visitOptions();
            case GET:
                return visitor.visitGet();
            case PUT:
                return visitor.visitPut();
            case PATCH:
                return visitor.visitPatch();
            case DELETE:
                return visitor.visitDelete();
            case HEAD:
                return visitor.visitHead();
            case POST:
                return visitor.visitPost();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListClickDetailMembersReportsResponseLinksItemMethod valueOf(String value) {
        switch (value) {
            case "OPTIONS":
                return OPTIONS;
            case "GET":
                return GET;
            case "PUT":
                return PUT;
            case "PATCH":
                return PATCH;
            case "DELETE":
                return DELETE;
            case "HEAD":
                return HEAD;
            case "POST":
                return POST;
            default:
                return new ListClickDetailMembersReportsResponseLinksItemMethod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        GET,

        POST,

        PUT,

        PATCH,

        DELETE,

        OPTIONS,

        HEAD,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitGet();

        T visitPost();

        T visitPut();

        T visitPatch();

        T visitDelete();

        T visitOptions();

        T visitHead();

        T visitUnknown(String unknownType);
    }
}
