/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.reports.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ListClickDetailsReportsRequestSortField {
    public static final ListClickDetailsReportsRequestSortField TOTAL_CLICKS =
            new ListClickDetailsReportsRequestSortField(Value.TOTAL_CLICKS, "total_clicks");

    public static final ListClickDetailsReportsRequestSortField UNIQUE_CLICKS =
            new ListClickDetailsReportsRequestSortField(Value.UNIQUE_CLICKS, "unique_clicks");

    private final Value value;

    private final String string;

    ListClickDetailsReportsRequestSortField(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ListClickDetailsReportsRequestSortField
                        && this.string.equals(((ListClickDetailsReportsRequestSortField) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TOTAL_CLICKS:
                return visitor.visitTotalClicks();
            case UNIQUE_CLICKS:
                return visitor.visitUniqueClicks();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListClickDetailsReportsRequestSortField valueOf(String value) {
        switch (value) {
            case "total_clicks":
                return TOTAL_CLICKS;
            case "unique_clicks":
                return UNIQUE_CLICKS;
            default:
                return new ListClickDetailsReportsRequestSortField(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        TOTAL_CLICKS,

        UNIQUE_CLICKS,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitTotalClicks();

        T visitUniqueClicks();

        T visitUnknown(String unknownType);
    }
}
