/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.lists.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import com.mailchimp.marketing.resources.lists.types.UpdateMergeFieldListsRequestOptions;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateMergeFieldListsRequest.Builder.class)
public final class UpdateMergeFieldListsRequest {
    private final Optional<String> defaultValue;

    private final Optional<Integer> displayOrder;

    private final Optional<String> helpText;

    private final Optional<String> name;

    private final Optional<UpdateMergeFieldListsRequestOptions> options;

    private final Optional<Boolean> public_;

    private final Optional<Boolean> required;

    private final Optional<String> tag;

    private final Map<String, Object> additionalProperties;

    private UpdateMergeFieldListsRequest(
            Optional<String> defaultValue,
            Optional<Integer> displayOrder,
            Optional<String> helpText,
            Optional<String> name,
            Optional<UpdateMergeFieldListsRequestOptions> options,
            Optional<Boolean> public_,
            Optional<Boolean> required,
            Optional<String> tag,
            Map<String, Object> additionalProperties) {
        this.defaultValue = defaultValue;
        this.displayOrder = displayOrder;
        this.helpText = helpText;
        this.name = name;
        this.options = options;
        this.public_ = public_;
        this.required = required;
        this.tag = tag;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The default value for the merge field if <code>null</code>.
     */
    @JsonProperty("default_value")
    public Optional<String> getDefaultValue() {
        return defaultValue;
    }

    /**
     * @return The order that the merge field displays on the list signup form.
     */
    @JsonProperty("display_order")
    public Optional<Integer> getDisplayOrder() {
        return displayOrder;
    }

    /**
     * @return Extra text to help the subscriber fill out the form.
     */
    @JsonProperty("help_text")
    public Optional<String> getHelpText() {
        return helpText;
    }

    /**
     * @return The name of the merge field (audience field).
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Extra options for some merge field types.
     */
    @JsonProperty("options")
    public Optional<UpdateMergeFieldListsRequestOptions> getOptions() {
        return options;
    }

    /**
     * @return Whether the merge field is displayed on the signup form.
     */
    @JsonProperty("public")
    public Optional<Boolean> getPublic() {
        return public_;
    }

    /**
     * @return Whether the merge field is required to import a contact.
     */
    @JsonProperty("required")
    public Optional<Boolean> getRequired() {
        return required;
    }

    /**
     * @return The merge tag used for Mailchimp campaigns and <a href="https://mailchimp.com/developer/marketing/docs/merge-fields/#add-merge-data-to-contacts">adding contact information</a>.
     */
    @JsonProperty("tag")
    public Optional<String> getTag() {
        return tag;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateMergeFieldListsRequest && equalTo((UpdateMergeFieldListsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateMergeFieldListsRequest other) {
        return defaultValue.equals(other.defaultValue)
                && displayOrder.equals(other.displayOrder)
                && helpText.equals(other.helpText)
                && name.equals(other.name)
                && options.equals(other.options)
                && public_.equals(other.public_)
                && required.equals(other.required)
                && tag.equals(other.tag);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.defaultValue,
                this.displayOrder,
                this.helpText,
                this.name,
                this.options,
                this.public_,
                this.required,
                this.tag);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> defaultValue = Optional.empty();

        private Optional<Integer> displayOrder = Optional.empty();

        private Optional<String> helpText = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<UpdateMergeFieldListsRequestOptions> options = Optional.empty();

        private Optional<Boolean> public_ = Optional.empty();

        private Optional<Boolean> required = Optional.empty();

        private Optional<String> tag = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateMergeFieldListsRequest other) {
            defaultValue(other.getDefaultValue());
            displayOrder(other.getDisplayOrder());
            helpText(other.getHelpText());
            name(other.getName());
            options(other.getOptions());
            public_(other.getPublic());
            required(other.getRequired());
            tag(other.getTag());
            return this;
        }

        /**
         * <p>The default value for the merge field if <code>null</code>.</p>
         */
        @JsonSetter(value = "default_value", nulls = Nulls.SKIP)
        public Builder defaultValue(Optional<String> defaultValue) {
            this.defaultValue = defaultValue;
            return this;
        }

        public Builder defaultValue(String defaultValue) {
            this.defaultValue = Optional.ofNullable(defaultValue);
            return this;
        }

        /**
         * <p>The order that the merge field displays on the list signup form.</p>
         */
        @JsonSetter(value = "display_order", nulls = Nulls.SKIP)
        public Builder displayOrder(Optional<Integer> displayOrder) {
            this.displayOrder = displayOrder;
            return this;
        }

        public Builder displayOrder(Integer displayOrder) {
            this.displayOrder = Optional.ofNullable(displayOrder);
            return this;
        }

        /**
         * <p>Extra text to help the subscriber fill out the form.</p>
         */
        @JsonSetter(value = "help_text", nulls = Nulls.SKIP)
        public Builder helpText(Optional<String> helpText) {
            this.helpText = helpText;
            return this;
        }

        public Builder helpText(String helpText) {
            this.helpText = Optional.ofNullable(helpText);
            return this;
        }

        /**
         * <p>The name of the merge field (audience field).</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Extra options for some merge field types.</p>
         */
        @JsonSetter(value = "options", nulls = Nulls.SKIP)
        public Builder options(Optional<UpdateMergeFieldListsRequestOptions> options) {
            this.options = options;
            return this;
        }

        public Builder options(UpdateMergeFieldListsRequestOptions options) {
            this.options = Optional.ofNullable(options);
            return this;
        }

        /**
         * <p>Whether the merge field is displayed on the signup form.</p>
         */
        @JsonSetter(value = "public", nulls = Nulls.SKIP)
        public Builder public_(Optional<Boolean> public_) {
            this.public_ = public_;
            return this;
        }

        public Builder public_(Boolean public_) {
            this.public_ = Optional.ofNullable(public_);
            return this;
        }

        /**
         * <p>Whether the merge field is required to import a contact.</p>
         */
        @JsonSetter(value = "required", nulls = Nulls.SKIP)
        public Builder required(Optional<Boolean> required) {
            this.required = required;
            return this;
        }

        public Builder required(Boolean required) {
            this.required = Optional.ofNullable(required);
            return this;
        }

        /**
         * <p>The merge tag used for Mailchimp campaigns and <a href="https://mailchimp.com/developer/marketing/docs/merge-fields/#add-merge-data-to-contacts">adding contact information</a>.</p>
         */
        @JsonSetter(value = "tag", nulls = Nulls.SKIP)
        public Builder tag(Optional<String> tag) {
            this.tag = tag;
            return this;
        }

        public Builder tag(String tag) {
            this.tag = Optional.ofNullable(tag);
            return this;
        }

        public UpdateMergeFieldListsRequest build() {
            return new UpdateMergeFieldListsRequest(
                    defaultValue, displayOrder, helpText, name, options, public_, required, tag, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
