/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AddWebhook.Builder.class)
public final class AddWebhook {
    private final Optional<AddWebhookEvents> events;

    private final Optional<AddWebhookSources> sources;

    private final Optional<String> url;

    private final Map<String, Object> additionalProperties;

    private AddWebhook(
            Optional<AddWebhookEvents> events,
            Optional<AddWebhookSources> sources,
            Optional<String> url,
            Map<String, Object> additionalProperties) {
        this.events = events;
        this.sources = sources;
        this.url = url;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The events that can trigger the webhook and whether they are enabled.
     */
    @JsonProperty("events")
    public Optional<AddWebhookEvents> getEvents() {
        return events;
    }

    /**
     * @return The possible sources of any events that can trigger the webhook and whether they are enabled.
     */
    @JsonProperty("sources")
    public Optional<AddWebhookSources> getSources() {
        return sources;
    }

    /**
     * @return A valid URL for the Webhook.
     */
    @JsonProperty("url")
    public Optional<String> getUrl() {
        return url;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AddWebhook && equalTo((AddWebhook) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AddWebhook other) {
        return events.equals(other.events) && sources.equals(other.sources) && url.equals(other.url);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.events, this.sources, this.url);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<AddWebhookEvents> events = Optional.empty();

        private Optional<AddWebhookSources> sources = Optional.empty();

        private Optional<String> url = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(AddWebhook other) {
            events(other.getEvents());
            sources(other.getSources());
            url(other.getUrl());
            return this;
        }

        /**
         * <p>The events that can trigger the webhook and whether they are enabled.</p>
         */
        @JsonSetter(value = "events", nulls = Nulls.SKIP)
        public Builder events(Optional<AddWebhookEvents> events) {
            this.events = events;
            return this;
        }

        public Builder events(AddWebhookEvents events) {
            this.events = Optional.ofNullable(events);
            return this;
        }

        /**
         * <p>The possible sources of any events that can trigger the webhook and whether they are enabled.</p>
         */
        @JsonSetter(value = "sources", nulls = Nulls.SKIP)
        public Builder sources(Optional<AddWebhookSources> sources) {
            this.sources = sources;
            return this;
        }

        public Builder sources(AddWebhookSources sources) {
            this.sources = Optional.ofNullable(sources);
            return this;
        }

        /**
         * <p>A valid URL for the Webhook.</p>
         */
        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public Builder url(Optional<String> url) {
            this.url = url;
            return this;
        }

        public Builder url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        public AddWebhook build() {
            return new AddWebhook(events, sources, url, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
