/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AutomationWorkflow.Builder.class)
public final class AutomationWorkflow {
    private final Optional<List<AutomationWorkflowLinksItem>> links;

    private final Optional<OffsetDateTime> createTime;

    private final Optional<Integer> emailsSent;

    private final Optional<String> id;

    private final Optional<AutomationWorkflowRecipients> recipients;

    private final Optional<AutomationWorkflowReportSummary> reportSummary;

    private final Optional<AutomationWorkflowSettings> settings;

    private final Optional<OffsetDateTime> startTime;

    private final Optional<AutomationWorkflowStatus> status;

    private final Optional<AutomationWorkflowTracking> tracking;

    private final Optional<AutomationWorkflowTriggerSettings> triggerSettings;

    private final Map<String, Object> additionalProperties;

    private AutomationWorkflow(
            Optional<List<AutomationWorkflowLinksItem>> links,
            Optional<OffsetDateTime> createTime,
            Optional<Integer> emailsSent,
            Optional<String> id,
            Optional<AutomationWorkflowRecipients> recipients,
            Optional<AutomationWorkflowReportSummary> reportSummary,
            Optional<AutomationWorkflowSettings> settings,
            Optional<OffsetDateTime> startTime,
            Optional<AutomationWorkflowStatus> status,
            Optional<AutomationWorkflowTracking> tracking,
            Optional<AutomationWorkflowTriggerSettings> triggerSettings,
            Map<String, Object> additionalProperties) {
        this.links = links;
        this.createTime = createTime;
        this.emailsSent = emailsSent;
        this.id = id;
        this.recipients = recipients;
        this.reportSummary = reportSummary;
        this.settings = settings;
        this.startTime = startTime;
        this.status = status;
        this.tracking = tracking;
        this.triggerSettings = triggerSettings;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A list of link types and descriptions for the API schema documents.
     */
    @JsonProperty("_links")
    public Optional<List<AutomationWorkflowLinksItem>> getLinks() {
        return links;
    }

    /**
     * @return The date and time the Automation was created in ISO 8601 format.
     */
    @JsonProperty("create_time")
    public Optional<OffsetDateTime> getCreateTime() {
        return createTime;
    }

    /**
     * @return The total number of emails sent for the Automation.
     */
    @JsonProperty("emails_sent")
    public Optional<Integer> getEmailsSent() {
        return emailsSent;
    }

    /**
     * @return A string that identifies the Automation.
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return List settings for the Automation.
     */
    @JsonProperty("recipients")
    public Optional<AutomationWorkflowRecipients> getRecipients() {
        return recipients;
    }

    /**
     * @return A summary of opens and clicks for sent campaigns.
     */
    @JsonProperty("report_summary")
    public Optional<AutomationWorkflowReportSummary> getReportSummary() {
        return reportSummary;
    }

    /**
     * @return The settings for the Automation workflow.
     */
    @JsonProperty("settings")
    public Optional<AutomationWorkflowSettings> getSettings() {
        return settings;
    }

    /**
     * @return The date and time the Automation was started in ISO 8601 format.
     */
    @JsonProperty("start_time")
    public Optional<OffsetDateTime> getStartTime() {
        return startTime;
    }

    /**
     * @return The current status of the Automation.
     */
    @JsonProperty("status")
    public Optional<AutomationWorkflowStatus> getStatus() {
        return status;
    }

    /**
     * @return The tracking options for the Automation.
     */
    @JsonProperty("tracking")
    public Optional<AutomationWorkflowTracking> getTracking() {
        return tracking;
    }

    /**
     * @return Available triggers for Automation workflows.
     */
    @JsonProperty("trigger_settings")
    public Optional<AutomationWorkflowTriggerSettings> getTriggerSettings() {
        return triggerSettings;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AutomationWorkflow && equalTo((AutomationWorkflow) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AutomationWorkflow other) {
        return links.equals(other.links)
                && createTime.equals(other.createTime)
                && emailsSent.equals(other.emailsSent)
                && id.equals(other.id)
                && recipients.equals(other.recipients)
                && reportSummary.equals(other.reportSummary)
                && settings.equals(other.settings)
                && startTime.equals(other.startTime)
                && status.equals(other.status)
                && tracking.equals(other.tracking)
                && triggerSettings.equals(other.triggerSettings);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.links,
                this.createTime,
                this.emailsSent,
                this.id,
                this.recipients,
                this.reportSummary,
                this.settings,
                this.startTime,
                this.status,
                this.tracking,
                this.triggerSettings);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<AutomationWorkflowLinksItem>> links = Optional.empty();

        private Optional<OffsetDateTime> createTime = Optional.empty();

        private Optional<Integer> emailsSent = Optional.empty();

        private Optional<String> id = Optional.empty();

        private Optional<AutomationWorkflowRecipients> recipients = Optional.empty();

        private Optional<AutomationWorkflowReportSummary> reportSummary = Optional.empty();

        private Optional<AutomationWorkflowSettings> settings = Optional.empty();

        private Optional<OffsetDateTime> startTime = Optional.empty();

        private Optional<AutomationWorkflowStatus> status = Optional.empty();

        private Optional<AutomationWorkflowTracking> tracking = Optional.empty();

        private Optional<AutomationWorkflowTriggerSettings> triggerSettings = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(AutomationWorkflow other) {
            links(other.getLinks());
            createTime(other.getCreateTime());
            emailsSent(other.getEmailsSent());
            id(other.getId());
            recipients(other.getRecipients());
            reportSummary(other.getReportSummary());
            settings(other.getSettings());
            startTime(other.getStartTime());
            status(other.getStatus());
            tracking(other.getTracking());
            triggerSettings(other.getTriggerSettings());
            return this;
        }

        /**
         * <p>A list of link types and descriptions for the API schema documents.</p>
         */
        @JsonSetter(value = "_links", nulls = Nulls.SKIP)
        public Builder links(Optional<List<AutomationWorkflowLinksItem>> links) {
            this.links = links;
            return this;
        }

        public Builder links(List<AutomationWorkflowLinksItem> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        /**
         * <p>The date and time the Automation was created in ISO 8601 format.</p>
         */
        @JsonSetter(value = "create_time", nulls = Nulls.SKIP)
        public Builder createTime(Optional<OffsetDateTime> createTime) {
            this.createTime = createTime;
            return this;
        }

        public Builder createTime(OffsetDateTime createTime) {
            this.createTime = Optional.ofNullable(createTime);
            return this;
        }

        /**
         * <p>The total number of emails sent for the Automation.</p>
         */
        @JsonSetter(value = "emails_sent", nulls = Nulls.SKIP)
        public Builder emailsSent(Optional<Integer> emailsSent) {
            this.emailsSent = emailsSent;
            return this;
        }

        public Builder emailsSent(Integer emailsSent) {
            this.emailsSent = Optional.ofNullable(emailsSent);
            return this;
        }

        /**
         * <p>A string that identifies the Automation.</p>
         */
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>List settings for the Automation.</p>
         */
        @JsonSetter(value = "recipients", nulls = Nulls.SKIP)
        public Builder recipients(Optional<AutomationWorkflowRecipients> recipients) {
            this.recipients = recipients;
            return this;
        }

        public Builder recipients(AutomationWorkflowRecipients recipients) {
            this.recipients = Optional.ofNullable(recipients);
            return this;
        }

        /**
         * <p>A summary of opens and clicks for sent campaigns.</p>
         */
        @JsonSetter(value = "report_summary", nulls = Nulls.SKIP)
        public Builder reportSummary(Optional<AutomationWorkflowReportSummary> reportSummary) {
            this.reportSummary = reportSummary;
            return this;
        }

        public Builder reportSummary(AutomationWorkflowReportSummary reportSummary) {
            this.reportSummary = Optional.ofNullable(reportSummary);
            return this;
        }

        /**
         * <p>The settings for the Automation workflow.</p>
         */
        @JsonSetter(value = "settings", nulls = Nulls.SKIP)
        public Builder settings(Optional<AutomationWorkflowSettings> settings) {
            this.settings = settings;
            return this;
        }

        public Builder settings(AutomationWorkflowSettings settings) {
            this.settings = Optional.ofNullable(settings);
            return this;
        }

        /**
         * <p>The date and time the Automation was started in ISO 8601 format.</p>
         */
        @JsonSetter(value = "start_time", nulls = Nulls.SKIP)
        public Builder startTime(Optional<OffsetDateTime> startTime) {
            this.startTime = startTime;
            return this;
        }

        public Builder startTime(OffsetDateTime startTime) {
            this.startTime = Optional.ofNullable(startTime);
            return this;
        }

        /**
         * <p>The current status of the Automation.</p>
         */
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<AutomationWorkflowStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(AutomationWorkflowStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>The tracking options for the Automation.</p>
         */
        @JsonSetter(value = "tracking", nulls = Nulls.SKIP)
        public Builder tracking(Optional<AutomationWorkflowTracking> tracking) {
            this.tracking = tracking;
            return this;
        }

        public Builder tracking(AutomationWorkflowTracking tracking) {
            this.tracking = Optional.ofNullable(tracking);
            return this;
        }

        /**
         * <p>Available triggers for Automation workflows.</p>
         */
        @JsonSetter(value = "trigger_settings", nulls = Nulls.SKIP)
        public Builder triggerSettings(Optional<AutomationWorkflowTriggerSettings> triggerSettings) {
            this.triggerSettings = triggerSettings;
            return this;
        }

        public Builder triggerSettings(AutomationWorkflowTriggerSettings triggerSettings) {
            this.triggerSettings = Optional.ofNullable(triggerSettings);
            return this;
        }

        public AutomationWorkflow build() {
            return new AutomationWorkflow(
                    links,
                    createTime,
                    emailsSent,
                    id,
                    recipients,
                    reportSummary,
                    settings,
                    startTime,
                    status,
                    tracking,
                    triggerSettings,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
