/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BatchWebhook.Builder.class)
public final class BatchWebhook {
    private final Optional<List<List<BatchWebhookLinksItemItem>>> links;

    private final Optional<Boolean> enabled;

    private final Optional<String> id;

    private final Optional<Boolean> signingEnabled;

    private final Optional<String> signingSecret;

    private final Optional<String> url;

    private final Map<String, Object> additionalProperties;

    private BatchWebhook(
            Optional<List<List<BatchWebhookLinksItemItem>>> links,
            Optional<Boolean> enabled,
            Optional<String> id,
            Optional<Boolean> signingEnabled,
            Optional<String> signingSecret,
            Optional<String> url,
            Map<String, Object> additionalProperties) {
        this.links = links;
        this.enabled = enabled;
        this.id = id;
        this.signingEnabled = signingEnabled;
        this.signingSecret = signingSecret;
        this.url = url;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A list of link types and descriptions for the API schema documents.
     */
    @JsonProperty("_links")
    public Optional<List<List<BatchWebhookLinksItemItem>>> getLinks() {
        return links;
    }

    /**
     * @return Whether the webhook receives requests or not.
     */
    @JsonProperty("enabled")
    public Optional<Boolean> getEnabled() {
        return enabled;
    }

    /**
     * @return A string that uniquely identifies this Batch Webhook.
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return Whether outbound deliveries are HMAC-signed.
     */
    @JsonProperty("signing_enabled")
    public Optional<Boolean> getSigningEnabled() {
        return signingEnabled;
    }

    /**
     * @return The HMAC signing secret. Returned exactly once at creation. This should be stored securely; if lost, delete and recreate the webhook to obtain a new secret.
     */
    @JsonProperty("signing_secret")
    public Optional<String> getSigningSecret() {
        return signingSecret;
    }

    /**
     * @return A valid URL for the Webhook.
     */
    @JsonProperty("url")
    public Optional<String> getUrl() {
        return url;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BatchWebhook && equalTo((BatchWebhook) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BatchWebhook other) {
        return links.equals(other.links)
                && enabled.equals(other.enabled)
                && id.equals(other.id)
                && signingEnabled.equals(other.signingEnabled)
                && signingSecret.equals(other.signingSecret)
                && url.equals(other.url);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.links, this.enabled, this.id, this.signingEnabled, this.signingSecret, this.url);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<List<BatchWebhookLinksItemItem>>> links = Optional.empty();

        private Optional<Boolean> enabled = Optional.empty();

        private Optional<String> id = Optional.empty();

        private Optional<Boolean> signingEnabled = Optional.empty();

        private Optional<String> signingSecret = Optional.empty();

        private Optional<String> url = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BatchWebhook other) {
            links(other.getLinks());
            enabled(other.getEnabled());
            id(other.getId());
            signingEnabled(other.getSigningEnabled());
            signingSecret(other.getSigningSecret());
            url(other.getUrl());
            return this;
        }

        /**
         * <p>A list of link types and descriptions for the API schema documents.</p>
         */
        @JsonSetter(value = "_links", nulls = Nulls.SKIP)
        public Builder links(Optional<List<List<BatchWebhookLinksItemItem>>> links) {
            this.links = links;
            return this;
        }

        public Builder links(List<List<BatchWebhookLinksItemItem>> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        /**
         * <p>Whether the webhook receives requests or not.</p>
         */
        @JsonSetter(value = "enabled", nulls = Nulls.SKIP)
        public Builder enabled(Optional<Boolean> enabled) {
            this.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            this.enabled = Optional.ofNullable(enabled);
            return this;
        }

        /**
         * <p>A string that uniquely identifies this Batch Webhook.</p>
         */
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>Whether outbound deliveries are HMAC-signed.</p>
         */
        @JsonSetter(value = "signing_enabled", nulls = Nulls.SKIP)
        public Builder signingEnabled(Optional<Boolean> signingEnabled) {
            this.signingEnabled = signingEnabled;
            return this;
        }

        public Builder signingEnabled(Boolean signingEnabled) {
            this.signingEnabled = Optional.ofNullable(signingEnabled);
            return this;
        }

        /**
         * <p>The HMAC signing secret. Returned exactly once at creation. This should be stored securely; if lost, delete and recreate the webhook to obtain a new secret.</p>
         */
        @JsonSetter(value = "signing_secret", nulls = Nulls.SKIP)
        public Builder signingSecret(Optional<String> signingSecret) {
            this.signingSecret = signingSecret;
            return this;
        }

        public Builder signingSecret(String signingSecret) {
            this.signingSecret = Optional.ofNullable(signingSecret);
            return this;
        }

        /**
         * <p>A valid URL for the Webhook.</p>
         */
        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public Builder url(Optional<String> url) {
            this.url = url;
            return this;
        }

        public Builder url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        public BatchWebhook build() {
            return new BatchWebhook(links, enabled, id, signingEnabled, signingSecret, url, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
