/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CampaignReportEcommerce.Builder.class)
public final class CampaignReportEcommerce {
    private final Optional<String> currencyCode;

    private final Optional<Integer> totalOrders;

    private final Optional<Double> totalRevenue;

    private final Optional<Double> totalSpent;

    private final Map<String, Object> additionalProperties;

    private CampaignReportEcommerce(
            Optional<String> currencyCode,
            Optional<Integer> totalOrders,
            Optional<Double> totalRevenue,
            Optional<Double> totalSpent,
            Map<String, Object> additionalProperties) {
        this.currencyCode = currencyCode;
        this.totalOrders = totalOrders;
        this.totalRevenue = totalRevenue;
        this.totalSpent = totalSpent;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("currency_code")
    public Optional<String> getCurrencyCode() {
        return currencyCode;
    }

    /**
     * @return The total orders for a campaign.
     */
    @JsonProperty("total_orders")
    public Optional<Integer> getTotalOrders() {
        return totalOrders;
    }

    /**
     * @return The total revenue for a campaign. Calculated as the sum of all order totals minus shipping and tax totals.
     */
    @JsonProperty("total_revenue")
    public Optional<Double> getTotalRevenue() {
        return totalRevenue;
    }

    /**
     * @return The total spent for a campaign. Calculated as the sum of all order totals with no deductions.
     */
    @JsonProperty("total_spent")
    public Optional<Double> getTotalSpent() {
        return totalSpent;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CampaignReportEcommerce && equalTo((CampaignReportEcommerce) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CampaignReportEcommerce other) {
        return currencyCode.equals(other.currencyCode)
                && totalOrders.equals(other.totalOrders)
                && totalRevenue.equals(other.totalRevenue)
                && totalSpent.equals(other.totalSpent);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.currencyCode, this.totalOrders, this.totalRevenue, this.totalSpent);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> currencyCode = Optional.empty();

        private Optional<Integer> totalOrders = Optional.empty();

        private Optional<Double> totalRevenue = Optional.empty();

        private Optional<Double> totalSpent = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CampaignReportEcommerce other) {
            currencyCode(other.getCurrencyCode());
            totalOrders(other.getTotalOrders());
            totalRevenue(other.getTotalRevenue());
            totalSpent(other.getTotalSpent());
            return this;
        }

        @JsonSetter(value = "currency_code", nulls = Nulls.SKIP)
        public Builder currencyCode(Optional<String> currencyCode) {
            this.currencyCode = currencyCode;
            return this;
        }

        public Builder currencyCode(String currencyCode) {
            this.currencyCode = Optional.ofNullable(currencyCode);
            return this;
        }

        /**
         * <p>The total orders for a campaign.</p>
         */
        @JsonSetter(value = "total_orders", nulls = Nulls.SKIP)
        public Builder totalOrders(Optional<Integer> totalOrders) {
            this.totalOrders = totalOrders;
            return this;
        }

        public Builder totalOrders(Integer totalOrders) {
            this.totalOrders = Optional.ofNullable(totalOrders);
            return this;
        }

        /**
         * <p>The total revenue for a campaign. Calculated as the sum of all order totals minus shipping and tax totals.</p>
         */
        @JsonSetter(value = "total_revenue", nulls = Nulls.SKIP)
        public Builder totalRevenue(Optional<Double> totalRevenue) {
            this.totalRevenue = totalRevenue;
            return this;
        }

        public Builder totalRevenue(Double totalRevenue) {
            this.totalRevenue = Optional.ofNullable(totalRevenue);
            return this;
        }

        /**
         * <p>The total spent for a campaign. Calculated as the sum of all order totals with no deductions.</p>
         */
        @JsonSetter(value = "total_spent", nulls = Nulls.SKIP)
        public Builder totalSpent(Optional<Double> totalSpent) {
            this.totalSpent = totalSpent;
            return this;
        }

        public Builder totalSpent(Double totalSpent) {
            this.totalSpent = Optional.ofNullable(totalSpent);
            return this;
        }

        public CampaignReportEcommerce build() {
            return new CampaignReportEcommerce(
                    currencyCode, totalOrders, totalRevenue, totalSpent, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
