/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CampaignsResendShortcutUsageShortcutCampaignsItemStatus {
    public static final CampaignsResendShortcutUsageShortcutCampaignsItemStatus SCHEDULE =
            new CampaignsResendShortcutUsageShortcutCampaignsItemStatus(Value.SCHEDULE, "schedule");

    public static final CampaignsResendShortcutUsageShortcutCampaignsItemStatus CANCELED =
            new CampaignsResendShortcutUsageShortcutCampaignsItemStatus(Value.CANCELED, "canceled");

    public static final CampaignsResendShortcutUsageShortcutCampaignsItemStatus SAVE =
            new CampaignsResendShortcutUsageShortcutCampaignsItemStatus(Value.SAVE, "save");

    public static final CampaignsResendShortcutUsageShortcutCampaignsItemStatus SENDING =
            new CampaignsResendShortcutUsageShortcutCampaignsItemStatus(Value.SENDING, "sending");

    public static final CampaignsResendShortcutUsageShortcutCampaignsItemStatus PAUSED =
            new CampaignsResendShortcutUsageShortcutCampaignsItemStatus(Value.PAUSED, "paused");

    public static final CampaignsResendShortcutUsageShortcutCampaignsItemStatus CANCELING =
            new CampaignsResendShortcutUsageShortcutCampaignsItemStatus(Value.CANCELING, "canceling");

    public static final CampaignsResendShortcutUsageShortcutCampaignsItemStatus ARCHIVED =
            new CampaignsResendShortcutUsageShortcutCampaignsItemStatus(Value.ARCHIVED, "archived");

    public static final CampaignsResendShortcutUsageShortcutCampaignsItemStatus SENT =
            new CampaignsResendShortcutUsageShortcutCampaignsItemStatus(Value.SENT, "sent");

    private final Value value;

    private final String string;

    CampaignsResendShortcutUsageShortcutCampaignsItemStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CampaignsResendShortcutUsageShortcutCampaignsItemStatus
                        && this.string.equals(
                                ((CampaignsResendShortcutUsageShortcutCampaignsItemStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SCHEDULE:
                return visitor.visitSchedule();
            case CANCELED:
                return visitor.visitCanceled();
            case SAVE:
                return visitor.visitSave();
            case SENDING:
                return visitor.visitSending();
            case PAUSED:
                return visitor.visitPaused();
            case CANCELING:
                return visitor.visitCanceling();
            case ARCHIVED:
                return visitor.visitArchived();
            case SENT:
                return visitor.visitSent();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CampaignsResendShortcutUsageShortcutCampaignsItemStatus valueOf(String value) {
        switch (value) {
            case "schedule":
                return SCHEDULE;
            case "canceled":
                return CANCELED;
            case "save":
                return SAVE;
            case "sending":
                return SENDING;
            case "paused":
                return PAUSED;
            case "canceling":
                return CANCELING;
            case "archived":
                return ARCHIVED;
            case "sent":
                return SENT;
            default:
                return new CampaignsResendShortcutUsageShortcutCampaignsItemStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SAVE,

        PAUSED,

        SCHEDULE,

        SENDING,

        SENT,

        CANCELED,

        CANCELING,

        ARCHIVED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSave();

        T visitPaused();

        T visitSchedule();

        T visitSending();

        T visitSent();

        T visitCanceled();

        T visitCanceling();

        T visitArchived();

        T visitUnknown(String unknownType);
    }
}
