/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CampaignsRssOpts.Builder.class)
public final class CampaignsRssOpts {
    private final Optional<Boolean> constrainRssImg;

    private final Optional<String> feedUrl;

    private final Optional<CampaignsRssOptsFrequency> frequency;

    private final Optional<OffsetDateTime> lastSent;

    private final Optional<CampaignsRssOptsSchedule> schedule;

    private final Map<String, Object> additionalProperties;

    private CampaignsRssOpts(
            Optional<Boolean> constrainRssImg,
            Optional<String> feedUrl,
            Optional<CampaignsRssOptsFrequency> frequency,
            Optional<OffsetDateTime> lastSent,
            Optional<CampaignsRssOptsSchedule> schedule,
            Map<String, Object> additionalProperties) {
        this.constrainRssImg = constrainRssImg;
        this.feedUrl = feedUrl;
        this.frequency = frequency;
        this.lastSent = lastSent;
        this.schedule = schedule;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether to add CSS to images in the RSS feed to constrain their width in campaigns.
     */
    @JsonProperty("constrain_rss_img")
    public Optional<Boolean> getConstrainRssImg() {
        return constrainRssImg;
    }

    /**
     * @return The URL for the RSS feed.
     */
    @JsonProperty("feed_url")
    public Optional<String> getFeedUrl() {
        return feedUrl;
    }

    /**
     * @return The frequency of the RSS Campaign.
     */
    @JsonProperty("frequency")
    public Optional<CampaignsRssOptsFrequency> getFrequency() {
        return frequency;
    }

    /**
     * @return The date the campaign was last sent.
     */
    @JsonProperty("last_sent")
    public Optional<OffsetDateTime> getLastSent() {
        return lastSent;
    }

    /**
     * @return The schedule for sending the RSS Campaign.
     */
    @JsonProperty("schedule")
    public Optional<CampaignsRssOptsSchedule> getSchedule() {
        return schedule;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CampaignsRssOpts && equalTo((CampaignsRssOpts) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CampaignsRssOpts other) {
        return constrainRssImg.equals(other.constrainRssImg)
                && feedUrl.equals(other.feedUrl)
                && frequency.equals(other.frequency)
                && lastSent.equals(other.lastSent)
                && schedule.equals(other.schedule);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.constrainRssImg, this.feedUrl, this.frequency, this.lastSent, this.schedule);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> constrainRssImg = Optional.empty();

        private Optional<String> feedUrl = Optional.empty();

        private Optional<CampaignsRssOptsFrequency> frequency = Optional.empty();

        private Optional<OffsetDateTime> lastSent = Optional.empty();

        private Optional<CampaignsRssOptsSchedule> schedule = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CampaignsRssOpts other) {
            constrainRssImg(other.getConstrainRssImg());
            feedUrl(other.getFeedUrl());
            frequency(other.getFrequency());
            lastSent(other.getLastSent());
            schedule(other.getSchedule());
            return this;
        }

        /**
         * <p>Whether to add CSS to images in the RSS feed to constrain their width in campaigns.</p>
         */
        @JsonSetter(value = "constrain_rss_img", nulls = Nulls.SKIP)
        public Builder constrainRssImg(Optional<Boolean> constrainRssImg) {
            this.constrainRssImg = constrainRssImg;
            return this;
        }

        public Builder constrainRssImg(Boolean constrainRssImg) {
            this.constrainRssImg = Optional.ofNullable(constrainRssImg);
            return this;
        }

        /**
         * <p>The URL for the RSS feed.</p>
         */
        @JsonSetter(value = "feed_url", nulls = Nulls.SKIP)
        public Builder feedUrl(Optional<String> feedUrl) {
            this.feedUrl = feedUrl;
            return this;
        }

        public Builder feedUrl(String feedUrl) {
            this.feedUrl = Optional.ofNullable(feedUrl);
            return this;
        }

        /**
         * <p>The frequency of the RSS Campaign.</p>
         */
        @JsonSetter(value = "frequency", nulls = Nulls.SKIP)
        public Builder frequency(Optional<CampaignsRssOptsFrequency> frequency) {
            this.frequency = frequency;
            return this;
        }

        public Builder frequency(CampaignsRssOptsFrequency frequency) {
            this.frequency = Optional.ofNullable(frequency);
            return this;
        }

        /**
         * <p>The date the campaign was last sent.</p>
         */
        @JsonSetter(value = "last_sent", nulls = Nulls.SKIP)
        public Builder lastSent(Optional<OffsetDateTime> lastSent) {
            this.lastSent = lastSent;
            return this;
        }

        public Builder lastSent(OffsetDateTime lastSent) {
            this.lastSent = Optional.ofNullable(lastSent);
            return this;
        }

        /**
         * <p>The schedule for sending the RSS Campaign.</p>
         */
        @JsonSetter(value = "schedule", nulls = Nulls.SKIP)
        public Builder schedule(Optional<CampaignsRssOptsSchedule> schedule) {
            this.schedule = schedule;
            return this;
        }

        public Builder schedule(CampaignsRssOptsSchedule schedule) {
            this.schedule = Optional.ofNullable(schedule);
            return this;
        }

        public CampaignsRssOpts build() {
            return new CampaignsRssOpts(constrainRssImg, feedUrl, frequency, lastSent, schedule, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
