/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ClickDetailReportAbSplitB.Builder.class)
public final class ClickDetailReportAbSplitB {
    private final Optional<Double> clickPercentageB;

    private final Optional<Integer> totalClicksB;

    private final Optional<Double> uniqueClickPercentageB;

    private final Optional<Integer> uniqueClicksB;

    private final Map<String, Object> additionalProperties;

    private ClickDetailReportAbSplitB(
            Optional<Double> clickPercentageB,
            Optional<Integer> totalClicksB,
            Optional<Double> uniqueClickPercentageB,
            Optional<Integer> uniqueClicksB,
            Map<String, Object> additionalProperties) {
        this.clickPercentageB = clickPercentageB;
        this.totalClicksB = totalClicksB;
        this.uniqueClickPercentageB = uniqueClickPercentageB;
        this.uniqueClicksB = uniqueClicksB;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The percentage of total clicks for Group B.
     */
    @JsonProperty("click_percentage_b")
    public Optional<Double> getClickPercentageB() {
        return clickPercentageB;
    }

    /**
     * @return The total number of clicks for Group B.
     */
    @JsonProperty("total_clicks_b")
    public Optional<Integer> getTotalClicksB() {
        return totalClicksB;
    }

    /**
     * @return The percentage of unique clicks for Group B.
     */
    @JsonProperty("unique_click_percentage_b")
    public Optional<Double> getUniqueClickPercentageB() {
        return uniqueClickPercentageB;
    }

    /**
     * @return The number of unique clicks for Group B.
     */
    @JsonProperty("unique_clicks_b")
    public Optional<Integer> getUniqueClicksB() {
        return uniqueClicksB;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClickDetailReportAbSplitB && equalTo((ClickDetailReportAbSplitB) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ClickDetailReportAbSplitB other) {
        return clickPercentageB.equals(other.clickPercentageB)
                && totalClicksB.equals(other.totalClicksB)
                && uniqueClickPercentageB.equals(other.uniqueClickPercentageB)
                && uniqueClicksB.equals(other.uniqueClicksB);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.clickPercentageB, this.totalClicksB, this.uniqueClickPercentageB, this.uniqueClicksB);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Double> clickPercentageB = Optional.empty();

        private Optional<Integer> totalClicksB = Optional.empty();

        private Optional<Double> uniqueClickPercentageB = Optional.empty();

        private Optional<Integer> uniqueClicksB = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ClickDetailReportAbSplitB other) {
            clickPercentageB(other.getClickPercentageB());
            totalClicksB(other.getTotalClicksB());
            uniqueClickPercentageB(other.getUniqueClickPercentageB());
            uniqueClicksB(other.getUniqueClicksB());
            return this;
        }

        /**
         * <p>The percentage of total clicks for Group B.</p>
         */
        @JsonSetter(value = "click_percentage_b", nulls = Nulls.SKIP)
        public Builder clickPercentageB(Optional<Double> clickPercentageB) {
            this.clickPercentageB = clickPercentageB;
            return this;
        }

        public Builder clickPercentageB(Double clickPercentageB) {
            this.clickPercentageB = Optional.ofNullable(clickPercentageB);
            return this;
        }

        /**
         * <p>The total number of clicks for Group B.</p>
         */
        @JsonSetter(value = "total_clicks_b", nulls = Nulls.SKIP)
        public Builder totalClicksB(Optional<Integer> totalClicksB) {
            this.totalClicksB = totalClicksB;
            return this;
        }

        public Builder totalClicksB(Integer totalClicksB) {
            this.totalClicksB = Optional.ofNullable(totalClicksB);
            return this;
        }

        /**
         * <p>The percentage of unique clicks for Group B.</p>
         */
        @JsonSetter(value = "unique_click_percentage_b", nulls = Nulls.SKIP)
        public Builder uniqueClickPercentageB(Optional<Double> uniqueClickPercentageB) {
            this.uniqueClickPercentageB = uniqueClickPercentageB;
            return this;
        }

        public Builder uniqueClickPercentageB(Double uniqueClickPercentageB) {
            this.uniqueClickPercentageB = Optional.ofNullable(uniqueClickPercentageB);
            return this;
        }

        /**
         * <p>The number of unique clicks for Group B.</p>
         */
        @JsonSetter(value = "unique_clicks_b", nulls = Nulls.SKIP)
        public Builder uniqueClicksB(Optional<Integer> uniqueClicksB) {
            this.uniqueClicksB = uniqueClicksB;
            return this;
        }

        public Builder uniqueClicksB(Integer uniqueClicksB) {
            this.uniqueClicksB = Optional.ofNullable(uniqueClicksB);
            return this;
        }

        public ClickDetailReportAbSplitB build() {
            return new ClickDetailReportAbSplitB(
                    clickPercentageB, totalClicksB, uniqueClickPercentageB, uniqueClicksB, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
