/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ECommerceStoreAutomationsAbandonedBrowse.Builder.class)
public final class ECommerceStoreAutomationsAbandonedBrowse {
    private final Optional<String> id;

    private final Optional<Boolean> isSupported;

    private final Optional<ECommerceStoreAutomationsAbandonedBrowseStatus> status;

    private final Map<String, Object> additionalProperties;

    private ECommerceStoreAutomationsAbandonedBrowse(
            Optional<String> id,
            Optional<Boolean> isSupported,
            Optional<ECommerceStoreAutomationsAbandonedBrowseStatus> status,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.isSupported = isSupported;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique ID of automation parent campaign.
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return Whether this store supports the abandonedBrowse automation.
     */
    @JsonProperty("is_supported")
    public Optional<Boolean> getIsSupported() {
        return isSupported;
    }

    /**
     * @return Status of the abandonedBrowse automation.
     */
    @JsonProperty("status")
    public Optional<ECommerceStoreAutomationsAbandonedBrowseStatus> getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ECommerceStoreAutomationsAbandonedBrowse
                && equalTo((ECommerceStoreAutomationsAbandonedBrowse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ECommerceStoreAutomationsAbandonedBrowse other) {
        return id.equals(other.id) && isSupported.equals(other.isSupported) && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.isSupported, this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<Boolean> isSupported = Optional.empty();

        private Optional<ECommerceStoreAutomationsAbandonedBrowseStatus> status = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ECommerceStoreAutomationsAbandonedBrowse other) {
            id(other.getId());
            isSupported(other.getIsSupported());
            status(other.getStatus());
            return this;
        }

        /**
         * <p>Unique ID of automation parent campaign.</p>
         */
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>Whether this store supports the abandonedBrowse automation.</p>
         */
        @JsonSetter(value = "is_supported", nulls = Nulls.SKIP)
        public Builder isSupported(Optional<Boolean> isSupported) {
            this.isSupported = isSupported;
            return this;
        }

        public Builder isSupported(Boolean isSupported) {
            this.isSupported = Optional.ofNullable(isSupported);
            return this;
        }

        /**
         * <p>Status of the abandonedBrowse automation.</p>
         */
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<ECommerceStoreAutomationsAbandonedBrowseStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(ECommerceStoreAutomationsAbandonedBrowseStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        public ECommerceStoreAutomationsAbandonedBrowse build() {
            return new ECommerceStoreAutomationsAbandonedBrowse(id, isSupported, status, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
