/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ECommerceOrderTrackingCode {
    public static final ECommerceOrderTrackingCode PREC = new ECommerceOrderTrackingCode(Value.PREC, "prec");

    private final Value value;

    private final String string;

    ECommerceOrderTrackingCode(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ECommerceOrderTrackingCode
                        && this.string.equals(((ECommerceOrderTrackingCode) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PREC:
                return visitor.visitPrec();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ECommerceOrderTrackingCode valueOf(String value) {
        switch (value) {
            case "prec":
                return PREC;
            default:
                return new ECommerceOrderTrackingCode(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PREC,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPrec();

        T visitUnknown(String unknownType);
    }
}
