/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ECommerceOrderLineItemLinksItemMethod {
    public static final ECommerceOrderLineItemLinksItemMethod OPTIONS =
            new ECommerceOrderLineItemLinksItemMethod(Value.OPTIONS, "OPTIONS");

    public static final ECommerceOrderLineItemLinksItemMethod GET =
            new ECommerceOrderLineItemLinksItemMethod(Value.GET, "GET");

    public static final ECommerceOrderLineItemLinksItemMethod PUT =
            new ECommerceOrderLineItemLinksItemMethod(Value.PUT, "PUT");

    public static final ECommerceOrderLineItemLinksItemMethod PATCH =
            new ECommerceOrderLineItemLinksItemMethod(Value.PATCH, "PATCH");

    public static final ECommerceOrderLineItemLinksItemMethod DELETE =
            new ECommerceOrderLineItemLinksItemMethod(Value.DELETE, "DELETE");

    public static final ECommerceOrderLineItemLinksItemMethod HEAD =
            new ECommerceOrderLineItemLinksItemMethod(Value.HEAD, "HEAD");

    public static final ECommerceOrderLineItemLinksItemMethod POST =
            new ECommerceOrderLineItemLinksItemMethod(Value.POST, "POST");

    private final Value value;

    private final String string;

    ECommerceOrderLineItemLinksItemMethod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ECommerceOrderLineItemLinksItemMethod
                        && this.string.equals(((ECommerceOrderLineItemLinksItemMethod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OPTIONS:
                return visitor.visitOptions();
            case GET:
                return visitor.visitGet();
            case PUT:
                return visitor.visitPut();
            case PATCH:
                return visitor.visitPatch();
            case DELETE:
                return visitor.visitDelete();
            case HEAD:
                return visitor.visitHead();
            case POST:
                return visitor.visitPost();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ECommerceOrderLineItemLinksItemMethod valueOf(String value) {
        switch (value) {
            case "OPTIONS":
                return OPTIONS;
            case "GET":
                return GET;
            case "PUT":
                return PUT;
            case "PATCH":
                return PATCH;
            case "DELETE":
                return DELETE;
            case "HEAD":
                return HEAD;
            case "POST":
                return POST;
            default:
                return new ECommerceOrderLineItemLinksItemMethod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        GET,

        POST,

        PUT,

        PATCH,

        DELETE,

        OPTIONS,

        HEAD,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitGet();

        T visitPost();

        T visitPut();

        T visitPatch();

        T visitDelete();

        T visitOptions();

        T visitHead();

        T visitUnknown(String unknownType);
    }
}
