/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FacebookAdRecipientsSegmentOptsMatch {
    public static final FacebookAdRecipientsSegmentOptsMatch ALL =
            new FacebookAdRecipientsSegmentOptsMatch(Value.ALL, "all");

    public static final FacebookAdRecipientsSegmentOptsMatch ANY =
            new FacebookAdRecipientsSegmentOptsMatch(Value.ANY, "any");

    private final Value value;

    private final String string;

    FacebookAdRecipientsSegmentOptsMatch(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof FacebookAdRecipientsSegmentOptsMatch
                        && this.string.equals(((FacebookAdRecipientsSegmentOptsMatch) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ALL:
                return visitor.visitAll();
            case ANY:
                return visitor.visitAny();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FacebookAdRecipientsSegmentOptsMatch valueOf(String value) {
        switch (value) {
            case "all":
                return ALL;
            case "any":
                return ANY;
            default:
                return new FacebookAdRecipientsSegmentOptsMatch(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ANY,

        ALL,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAny();

        T visitAll();

        T visitUnknown(String unknownType);
    }
}
