/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ListMembersStatus {
    public static final ListMembersStatus TRANSACTIONAL = new ListMembersStatus(Value.TRANSACTIONAL, "transactional");

    public static final ListMembersStatus PENDING = new ListMembersStatus(Value.PENDING, "pending");

    public static final ListMembersStatus CLEANED = new ListMembersStatus(Value.CLEANED, "cleaned");

    public static final ListMembersStatus UNSUBSCRIBED = new ListMembersStatus(Value.UNSUBSCRIBED, "unsubscribed");

    public static final ListMembersStatus SUBSCRIBED = new ListMembersStatus(Value.SUBSCRIBED, "subscribed");

    public static final ListMembersStatus ARCHIVED = new ListMembersStatus(Value.ARCHIVED, "archived");

    private final Value value;

    private final String string;

    ListMembersStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ListMembersStatus && this.string.equals(((ListMembersStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TRANSACTIONAL:
                return visitor.visitTransactional();
            case PENDING:
                return visitor.visitPending();
            case CLEANED:
                return visitor.visitCleaned();
            case UNSUBSCRIBED:
                return visitor.visitUnsubscribed();
            case SUBSCRIBED:
                return visitor.visitSubscribed();
            case ARCHIVED:
                return visitor.visitArchived();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListMembersStatus valueOf(String value) {
        switch (value) {
            case "transactional":
                return TRANSACTIONAL;
            case "pending":
                return PENDING;
            case "cleaned":
                return CLEANED;
            case "unsubscribed":
                return UNSUBSCRIBED;
            case "subscribed":
                return SUBSCRIBED;
            case "archived":
                return ARCHIVED;
            default:
                return new ListMembersStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SUBSCRIBED,

        UNSUBSCRIBED,

        CLEANED,

        PENDING,

        TRANSACTIONAL,

        ARCHIVED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSubscribed();

        T visitUnsubscribed();

        T visitCleaned();

        T visitPending();

        T visitTransactional();

        T visitArchived();

        T visitUnknown(String unknownType);
    }
}
