/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ReportingFacebookAdAudienceActivityImpressionsItem.Builder.class)
public final class ReportingFacebookAdAudienceActivityImpressionsItem {
    private final Optional<String> date;

    private final Optional<Integer> impressions;

    private final Map<String, Object> additionalProperties;

    private ReportingFacebookAdAudienceActivityImpressionsItem(
            Optional<String> date, Optional<Integer> impressions, Map<String, Object> additionalProperties) {
        this.date = date;
        this.impressions = impressions;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("date")
    public Optional<String> getDate() {
        return date;
    }

    @JsonProperty("impressions")
    public Optional<Integer> getImpressions() {
        return impressions;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ReportingFacebookAdAudienceActivityImpressionsItem
                && equalTo((ReportingFacebookAdAudienceActivityImpressionsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ReportingFacebookAdAudienceActivityImpressionsItem other) {
        return date.equals(other.date) && impressions.equals(other.impressions);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.date, this.impressions);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> date = Optional.empty();

        private Optional<Integer> impressions = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ReportingFacebookAdAudienceActivityImpressionsItem other) {
            date(other.getDate());
            impressions(other.getImpressions());
            return this;
        }

        @JsonSetter(value = "date", nulls = Nulls.SKIP)
        public Builder date(Optional<String> date) {
            this.date = date;
            return this;
        }

        public Builder date(String date) {
            this.date = Optional.ofNullable(date);
            return this;
        }

        @JsonSetter(value = "impressions", nulls = Nulls.SKIP)
        public Builder impressions(Optional<Integer> impressions) {
            this.impressions = impressions;
            return this;
        }

        public Builder impressions(Integer impressions) {
            this.impressions = Optional.ofNullable(impressions);
            return this;
        }

        public ReportingFacebookAdAudienceActivityImpressionsItem build() {
            return new ReportingFacebookAdAudienceActivityImpressionsItem(date, impressions, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
