/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ReportingFacebookAdReportSummaryAverageDailyBudget.Builder.class)
public final class ReportingFacebookAdReportSummaryAverageDailyBudget {
    private final Optional<Double> amount;

    private final Optional<String> currencyCode;

    private final Map<String, Object> additionalProperties;

    private ReportingFacebookAdReportSummaryAverageDailyBudget(
            Optional<Double> amount, Optional<String> currencyCode, Map<String, Object> additionalProperties) {
        this.amount = amount;
        this.currencyCode = currencyCode;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("amount")
    public Optional<Double> getAmount() {
        return amount;
    }

    @JsonProperty("currency_code")
    public Optional<String> getCurrencyCode() {
        return currencyCode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ReportingFacebookAdReportSummaryAverageDailyBudget
                && equalTo((ReportingFacebookAdReportSummaryAverageDailyBudget) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ReportingFacebookAdReportSummaryAverageDailyBudget other) {
        return amount.equals(other.amount) && currencyCode.equals(other.currencyCode);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.amount, this.currencyCode);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Double> amount = Optional.empty();

        private Optional<String> currencyCode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ReportingFacebookAdReportSummaryAverageDailyBudget other) {
            amount(other.getAmount());
            currencyCode(other.getCurrencyCode());
            return this;
        }

        @JsonSetter(value = "amount", nulls = Nulls.SKIP)
        public Builder amount(Optional<Double> amount) {
            this.amount = amount;
            return this;
        }

        public Builder amount(Double amount) {
            this.amount = Optional.ofNullable(amount);
            return this;
        }

        @JsonSetter(value = "currency_code", nulls = Nulls.SKIP)
        public Builder currencyCode(Optional<String> currencyCode) {
            this.currencyCode = currencyCode;
            return this;
        }

        public Builder currencyCode(String currencyCode) {
            this.currencyCode = Optional.ofNullable(currencyCode);
            return this;
        }

        public ReportingFacebookAdReportSummaryAverageDailyBudget build() {
            return new ReportingFacebookAdReportSummaryAverageDailyBudget(amount, currencyCode, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
