/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SegmentTypeItemLanguage.Builder.class)
public final class SegmentTypeItemLanguage {
    private final SegmentTypeItemLanguageField field;

    private final SegmentTypeItemLanguageOp op;

    private final String value;

    private final Map<String, Object> additionalProperties;

    private SegmentTypeItemLanguage(
            SegmentTypeItemLanguageField field,
            SegmentTypeItemLanguageOp op,
            String value,
            Map<String, Object> additionalProperties) {
        this.field = field;
        this.op = op;
        this.value = value;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Segmenting based off of a subscriber's language.
     */
    @JsonProperty("field")
    public SegmentTypeItemLanguageField getField() {
        return field;
    }

    /**
     * @return Whether the member's language is or is not set to a specific language.
     */
    @JsonProperty("op")
    public SegmentTypeItemLanguageOp getOp() {
        return op;
    }

    /**
     * @return A two-letter language identifier.
     */
    @JsonProperty("value")
    public String getValue() {
        return value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SegmentTypeItemLanguage && equalTo((SegmentTypeItemLanguage) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SegmentTypeItemLanguage other) {
        return field.equals(other.field) && op.equals(other.op) && value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.field, this.op, this.value);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FieldStage builder() {
        return new Builder();
    }

    public interface FieldStage {
        /**
         * <p>Segmenting based off of a subscriber's language.</p>
         */
        OpStage field(@NotNull SegmentTypeItemLanguageField field);

        Builder from(SegmentTypeItemLanguage other);
    }

    public interface OpStage {
        /**
         * <p>Whether the member's language is or is not set to a specific language.</p>
         */
        ValueStage op(@NotNull SegmentTypeItemLanguageOp op);
    }

    public interface ValueStage {
        /**
         * <p>A two-letter language identifier.</p>
         */
        _FinalStage value(@NotNull String value);
    }

    public interface _FinalStage {
        SegmentTypeItemLanguage build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FieldStage, OpStage, ValueStage, _FinalStage {
        private SegmentTypeItemLanguageField field;

        private SegmentTypeItemLanguageOp op;

        private String value;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SegmentTypeItemLanguage other) {
            field(other.getField());
            op(other.getOp());
            value(other.getValue());
            return this;
        }

        /**
         * <p>Segmenting based off of a subscriber's language.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("field")
        public OpStage field(@NotNull SegmentTypeItemLanguageField field) {
            this.field = Objects.requireNonNull(field, "field must not be null");
            return this;
        }

        /**
         * <p>Whether the member's language is or is not set to a specific language.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("op")
        public ValueStage op(@NotNull SegmentTypeItemLanguageOp op) {
            this.op = Objects.requireNonNull(op, "op must not be null");
            return this;
        }

        /**
         * <p>A two-letter language identifier.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("value")
        public _FinalStage value(@NotNull String value) {
            this.value = Objects.requireNonNull(value, "value must not be null");
            return this;
        }

        @java.lang.Override
        public SegmentTypeItemLanguage build() {
            return new SegmentTypeItemLanguage(field, op, value, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
