/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SegmentTypeItemEcommNumberOp {
    public static final SegmentTypeItemEcommNumberOp NOT = new SegmentTypeItemEcommNumberOp(Value.NOT, "not");

    public static final SegmentTypeItemEcommNumberOp IS = new SegmentTypeItemEcommNumberOp(Value.IS, "is");

    public static final SegmentTypeItemEcommNumberOp GREATER =
            new SegmentTypeItemEcommNumberOp(Value.GREATER, "greater");

    public static final SegmentTypeItemEcommNumberOp LESS = new SegmentTypeItemEcommNumberOp(Value.LESS, "less");

    private final Value value;

    private final String string;

    SegmentTypeItemEcommNumberOp(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SegmentTypeItemEcommNumberOp
                        && this.string.equals(((SegmentTypeItemEcommNumberOp) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case NOT:
                return visitor.visitNot();
            case IS:
                return visitor.visitIs();
            case GREATER:
                return visitor.visitGreater();
            case LESS:
                return visitor.visitLess();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SegmentTypeItemEcommNumberOp valueOf(String value) {
        switch (value) {
            case "not":
                return NOT;
            case "is":
                return IS;
            case "greater":
                return GREATER;
            case "less":
                return LESS;
            default:
                return new SegmentTypeItemEcommNumberOp(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        IS,

        NOT,

        GREATER,

        LESS,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitIs();

        T visitNot();

        T visitGreater();

        T visitLess();

        T visitUnknown(String unknownType);
    }
}
