/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SegmentTypeItemInterests.Builder.class)
public final class SegmentTypeItemInterests {
    private final Optional<String> field;

    private final Optional<SegmentTypeItemInterestsOp> op;

    private final Optional<List<String>> value;

    private final Map<String, Object> additionalProperties;

    private SegmentTypeItemInterests(
            Optional<String> field,
            Optional<SegmentTypeItemInterestsOp> op,
            Optional<List<String>> value,
            Map<String, Object> additionalProperties) {
        this.field = field;
        this.op = op;
        this.value = value;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Segmenting based on interest group information. This should start with 'interests-' followed by the grouping id. Ex. 'interests-123'.
     */
    @JsonProperty("field")
    public Optional<String> getField() {
        return field;
    }

    /**
     * @return Whether the member is a part of one, all, or none of the groups.
     */
    @JsonProperty("op")
    public Optional<SegmentTypeItemInterestsOp> getOp() {
        return op;
    }

    /**
     * @return An array containing strings, each representing a group id.
     */
    @JsonProperty("value")
    public Optional<List<String>> getValue() {
        return value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SegmentTypeItemInterests && equalTo((SegmentTypeItemInterests) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SegmentTypeItemInterests other) {
        return field.equals(other.field) && op.equals(other.op) && value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.field, this.op, this.value);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> field = Optional.empty();

        private Optional<SegmentTypeItemInterestsOp> op = Optional.empty();

        private Optional<List<String>> value = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SegmentTypeItemInterests other) {
            field(other.getField());
            op(other.getOp());
            value(other.getValue());
            return this;
        }

        /**
         * <p>Segmenting based on interest group information. This should start with 'interests-' followed by the grouping id. Ex. 'interests-123'.</p>
         */
        @JsonSetter(value = "field", nulls = Nulls.SKIP)
        public Builder field(Optional<String> field) {
            this.field = field;
            return this;
        }

        public Builder field(String field) {
            this.field = Optional.ofNullable(field);
            return this;
        }

        /**
         * <p>Whether the member is a part of one, all, or none of the groups.</p>
         */
        @JsonSetter(value = "op", nulls = Nulls.SKIP)
        public Builder op(Optional<SegmentTypeItemInterestsOp> op) {
            this.op = op;
            return this;
        }

        public Builder op(SegmentTypeItemInterestsOp op) {
            this.op = Optional.ofNullable(op);
            return this;
        }

        /**
         * <p>An array containing strings, each representing a group id.</p>
         */
        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public Builder value(Optional<List<String>> value) {
            this.value = value;
            return this;
        }

        public Builder value(List<String> value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        public SegmentTypeItemInterests build() {
            return new SegmentTypeItemInterests(field, op, value, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
