/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SegmentTypeItemPredictedAgeValue {
    public static final SegmentTypeItemPredictedAgeValue EIGHTEEN24 =
            new SegmentTypeItemPredictedAgeValue(Value.EIGHTEEN24, "18-24");

    public static final SegmentTypeItemPredictedAgeValue FIFTY_FIVE64 =
            new SegmentTypeItemPredictedAgeValue(Value.FIFTY_FIVE64, "55-64");

    public static final SegmentTypeItemPredictedAgeValue FORTY_FIVE54 =
            new SegmentTypeItemPredictedAgeValue(Value.FORTY_FIVE54, "45-54");

    public static final SegmentTypeItemPredictedAgeValue SIXTY_FIVE =
            new SegmentTypeItemPredictedAgeValue(Value.SIXTY_FIVE, "65+");

    public static final SegmentTypeItemPredictedAgeValue TWENTY_FIVE34 =
            new SegmentTypeItemPredictedAgeValue(Value.TWENTY_FIVE34, "25-34");

    public static final SegmentTypeItemPredictedAgeValue THIRTY_FIVE44 =
            new SegmentTypeItemPredictedAgeValue(Value.THIRTY_FIVE44, "35-44");

    private final Value value;

    private final String string;

    SegmentTypeItemPredictedAgeValue(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SegmentTypeItemPredictedAgeValue
                        && this.string.equals(((SegmentTypeItemPredictedAgeValue) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case EIGHTEEN24:
                return visitor.visitEighteen24();
            case FIFTY_FIVE64:
                return visitor.visitFiftyFive64();
            case FORTY_FIVE54:
                return visitor.visitFortyFive54();
            case SIXTY_FIVE:
                return visitor.visitSixtyFive();
            case TWENTY_FIVE34:
                return visitor.visitTwentyFive34();
            case THIRTY_FIVE44:
                return visitor.visitThirtyFive44();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SegmentTypeItemPredictedAgeValue valueOf(String value) {
        switch (value) {
            case "18-24":
                return EIGHTEEN24;
            case "55-64":
                return FIFTY_FIVE64;
            case "45-54":
                return FORTY_FIVE54;
            case "65+":
                return SIXTY_FIVE;
            case "25-34":
                return TWENTY_FIVE34;
            case "35-44":
                return THIRTY_FIVE44;
            default:
                return new SegmentTypeItemPredictedAgeValue(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        EIGHTEEN24,

        TWENTY_FIVE34,

        THIRTY_FIVE44,

        FORTY_FIVE54,

        FIFTY_FIVE64,

        SIXTY_FIVE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitEighteen24();

        T visitTwentyFive34();

        T visitThirtyFive44();

        T visitFortyFive54();

        T visitFiftyFive64();

        T visitSixtyFive();

        T visitUnknown(String unknownType);
    }
}
