/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SegmentTypeItemDateOp {
    public static final SegmentTypeItemDateOp NOT = new SegmentTypeItemDateOp(Value.NOT, "not");

    public static final SegmentTypeItemDateOp IS = new SegmentTypeItemDateOp(Value.IS, "is");

    public static final SegmentTypeItemDateOp BLANK = new SegmentTypeItemDateOp(Value.BLANK, "blank");

    public static final SegmentTypeItemDateOp BLANK_NOT = new SegmentTypeItemDateOp(Value.BLANK_NOT, "blank_not");

    public static final SegmentTypeItemDateOp NOTWITHIN = new SegmentTypeItemDateOp(Value.NOTWITHIN, "notwithin");

    public static final SegmentTypeItemDateOp GREATER = new SegmentTypeItemDateOp(Value.GREATER, "greater");

    public static final SegmentTypeItemDateOp LESS = new SegmentTypeItemDateOp(Value.LESS, "less");

    public static final SegmentTypeItemDateOp WITHIN = new SegmentTypeItemDateOp(Value.WITHIN, "within");

    private final Value value;

    private final String string;

    SegmentTypeItemDateOp(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SegmentTypeItemDateOp
                        && this.string.equals(((SegmentTypeItemDateOp) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case NOT:
                return visitor.visitNot();
            case IS:
                return visitor.visitIs();
            case BLANK:
                return visitor.visitBlank();
            case BLANK_NOT:
                return visitor.visitBlankNot();
            case NOTWITHIN:
                return visitor.visitNotwithin();
            case GREATER:
                return visitor.visitGreater();
            case LESS:
                return visitor.visitLess();
            case WITHIN:
                return visitor.visitWithin();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SegmentTypeItemDateOp valueOf(String value) {
        switch (value) {
            case "not":
                return NOT;
            case "is":
                return IS;
            case "blank":
                return BLANK;
            case "blank_not":
                return BLANK_NOT;
            case "notwithin":
                return NOTWITHIN;
            case "greater":
                return GREATER;
            case "less":
                return LESS;
            case "within":
                return WITHIN;
            default:
                return new SegmentTypeItemDateOp(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        GREATER,

        LESS,

        IS,

        NOT,

        BLANK,

        BLANK_NOT,

        WITHIN,

        NOTWITHIN,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitGreater();

        T visitLess();

        T visitIs();

        T visitNot();

        T visitBlank();

        T visitBlankNot();

        T visitWithin();

        T visitNotwithin();

        T visitUnknown(String unknownType);
    }
}
