/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SegmentTypeItemNewSubscribers.Builder.class)
public final class SegmentTypeItemNewSubscribers {
    private final Optional<SegmentTypeItemNewSubscribersField> field;

    private final Optional<SegmentTypeItemNewSubscribersOp> op;

    private final Optional<String> value;

    private final Map<String, Object> additionalProperties;

    private SegmentTypeItemNewSubscribers(
            Optional<SegmentTypeItemNewSubscribersField> field,
            Optional<SegmentTypeItemNewSubscribersOp> op,
            Optional<String> value,
            Map<String, Object> additionalProperties) {
        this.field = field;
        this.op = op;
        this.value = value;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Segment by when people subscribed.
     */
    @JsonProperty("field")
    public Optional<SegmentTypeItemNewSubscribersField> getField() {
        return field;
    }

    /**
     * @return Whe the event took place, namely within a time frame.
     */
    @JsonProperty("op")
    public Optional<SegmentTypeItemNewSubscribersOp> getOp() {
        return op;
    }

    /**
     * @return What type of data to segment on: a specific date, a specific campaign, or the last campaign sent.
     */
    @JsonProperty("value")
    public Optional<String> getValue() {
        return value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SegmentTypeItemNewSubscribers && equalTo((SegmentTypeItemNewSubscribers) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SegmentTypeItemNewSubscribers other) {
        return field.equals(other.field) && op.equals(other.op) && value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.field, this.op, this.value);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<SegmentTypeItemNewSubscribersField> field = Optional.empty();

        private Optional<SegmentTypeItemNewSubscribersOp> op = Optional.empty();

        private Optional<String> value = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SegmentTypeItemNewSubscribers other) {
            field(other.getField());
            op(other.getOp());
            value(other.getValue());
            return this;
        }

        /**
         * <p>Segment by when people subscribed.</p>
         */
        @JsonSetter(value = "field", nulls = Nulls.SKIP)
        public Builder field(Optional<SegmentTypeItemNewSubscribersField> field) {
            this.field = field;
            return this;
        }

        public Builder field(SegmentTypeItemNewSubscribersField field) {
            this.field = Optional.ofNullable(field);
            return this;
        }

        /**
         * <p>Whe the event took place, namely within a time frame.</p>
         */
        @JsonSetter(value = "op", nulls = Nulls.SKIP)
        public Builder op(Optional<SegmentTypeItemNewSubscribersOp> op) {
            this.op = op;
            return this;
        }

        public Builder op(SegmentTypeItemNewSubscribersOp op) {
            this.op = Optional.ofNullable(op);
            return this;
        }

        /**
         * <p>What type of data to segment on: a specific date, a specific campaign, or the last campaign sent.</p>
         */
        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public Builder value(Optional<String> value) {
            this.value = value;
            return this;
        }

        public Builder value(String value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        public SegmentTypeItemNewSubscribers build() {
            return new SegmentTypeItemNewSubscribers(field, op, value, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
