/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SegmentTypeItemSignupSource.Builder.class)
public final class SegmentTypeItemSignupSource {
    private final SegmentTypeItemSignupSourceField field;

    private final SegmentTypeItemSignupSourceOp op;

    private final Optional<String> value;

    private final Map<String, Object> additionalProperties;

    private SegmentTypeItemSignupSource(
            SegmentTypeItemSignupSourceField field,
            SegmentTypeItemSignupSourceOp op,
            Optional<String> value,
            Map<String, Object> additionalProperties) {
        this.field = field;
        this.op = op;
        this.value = value;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("field")
    public SegmentTypeItemSignupSourceField getField() {
        return field;
    }

    /**
     * @return Whether the member's signup source was/was not a particular value.
     */
    @JsonProperty("op")
    public SegmentTypeItemSignupSourceOp getOp() {
        return op;
    }

    /**
     * @return The signup source.
     */
    @JsonProperty("value")
    public Optional<String> getValue() {
        return value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SegmentTypeItemSignupSource && equalTo((SegmentTypeItemSignupSource) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SegmentTypeItemSignupSource other) {
        return field.equals(other.field) && op.equals(other.op) && value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.field, this.op, this.value);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FieldStage builder() {
        return new Builder();
    }

    public interface FieldStage {
        OpStage field(@NotNull SegmentTypeItemSignupSourceField field);

        Builder from(SegmentTypeItemSignupSource other);
    }

    public interface OpStage {
        /**
         * <p>Whether the member's signup source was/was not a particular value.</p>
         */
        _FinalStage op(@NotNull SegmentTypeItemSignupSourceOp op);
    }

    public interface _FinalStage {
        SegmentTypeItemSignupSource build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The signup source.</p>
         */
        _FinalStage value(Optional<String> value);

        _FinalStage value(String value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FieldStage, OpStage, _FinalStage {
        private SegmentTypeItemSignupSourceField field;

        private SegmentTypeItemSignupSourceOp op;

        private Optional<String> value = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SegmentTypeItemSignupSource other) {
            field(other.getField());
            op(other.getOp());
            value(other.getValue());
            return this;
        }

        @java.lang.Override
        @JsonSetter("field")
        public OpStage field(@NotNull SegmentTypeItemSignupSourceField field) {
            this.field = Objects.requireNonNull(field, "field must not be null");
            return this;
        }

        /**
         * <p>Whether the member's signup source was/was not a particular value.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("op")
        public _FinalStage op(@NotNull SegmentTypeItemSignupSourceOp op) {
            this.op = Objects.requireNonNull(op, "op must not be null");
            return this;
        }

        /**
         * <p>The signup source.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage value(String value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        /**
         * <p>The signup source.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public _FinalStage value(Optional<String> value) {
            this.value = value;
            return this;
        }

        @java.lang.Override
        public SegmentTypeItemSignupSource build() {
            return new SegmentTypeItemSignupSource(field, op, value, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
