/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SignupForm.Builder.class)
public final class SignupForm {
    private final Optional<List<SignupFormLinksItem>> links;

    private final Optional<List<SignupFormContentsItem>> contents;

    private final Optional<SignupFormHeader> header;

    private final Optional<String> listId;

    private final Optional<String> signupFormUrl;

    private final Optional<List<SignupFormStylesItem>> styles;

    private final Map<String, Object> additionalProperties;

    private SignupForm(
            Optional<List<SignupFormLinksItem>> links,
            Optional<List<SignupFormContentsItem>> contents,
            Optional<SignupFormHeader> header,
            Optional<String> listId,
            Optional<String> signupFormUrl,
            Optional<List<SignupFormStylesItem>> styles,
            Map<String, Object> additionalProperties) {
        this.links = links;
        this.contents = contents;
        this.header = header;
        this.listId = listId;
        this.signupFormUrl = signupFormUrl;
        this.styles = styles;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A list of link types and descriptions for the API schema documents.
     */
    @JsonProperty("_links")
    public Optional<List<SignupFormLinksItem>> getLinks() {
        return links;
    }

    /**
     * @return The signup form body content.
     */
    @JsonProperty("contents")
    public Optional<List<SignupFormContentsItem>> getContents() {
        return contents;
    }

    /**
     * @return Options for customizing your signup form header.
     */
    @JsonProperty("header")
    public Optional<SignupFormHeader> getHeader() {
        return header;
    }

    /**
     * @return The signup form's list id.
     */
    @JsonProperty("list_id")
    public Optional<String> getListId() {
        return listId;
    }

    /**
     * @return Signup form URL.
     */
    @JsonProperty("signup_form_url")
    public Optional<String> getSignupFormUrl() {
        return signupFormUrl;
    }

    /**
     * @return An array of objects, each representing an element style for the signup form.
     */
    @JsonProperty("styles")
    public Optional<List<SignupFormStylesItem>> getStyles() {
        return styles;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SignupForm && equalTo((SignupForm) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SignupForm other) {
        return links.equals(other.links)
                && contents.equals(other.contents)
                && header.equals(other.header)
                && listId.equals(other.listId)
                && signupFormUrl.equals(other.signupFormUrl)
                && styles.equals(other.styles);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.links, this.contents, this.header, this.listId, this.signupFormUrl, this.styles);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<SignupFormLinksItem>> links = Optional.empty();

        private Optional<List<SignupFormContentsItem>> contents = Optional.empty();

        private Optional<SignupFormHeader> header = Optional.empty();

        private Optional<String> listId = Optional.empty();

        private Optional<String> signupFormUrl = Optional.empty();

        private Optional<List<SignupFormStylesItem>> styles = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SignupForm other) {
            links(other.getLinks());
            contents(other.getContents());
            header(other.getHeader());
            listId(other.getListId());
            signupFormUrl(other.getSignupFormUrl());
            styles(other.getStyles());
            return this;
        }

        /**
         * <p>A list of link types and descriptions for the API schema documents.</p>
         */
        @JsonSetter(value = "_links", nulls = Nulls.SKIP)
        public Builder links(Optional<List<SignupFormLinksItem>> links) {
            this.links = links;
            return this;
        }

        public Builder links(List<SignupFormLinksItem> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        /**
         * <p>The signup form body content.</p>
         */
        @JsonSetter(value = "contents", nulls = Nulls.SKIP)
        public Builder contents(Optional<List<SignupFormContentsItem>> contents) {
            this.contents = contents;
            return this;
        }

        public Builder contents(List<SignupFormContentsItem> contents) {
            this.contents = Optional.ofNullable(contents);
            return this;
        }

        /**
         * <p>Options for customizing your signup form header.</p>
         */
        @JsonSetter(value = "header", nulls = Nulls.SKIP)
        public Builder header(Optional<SignupFormHeader> header) {
            this.header = header;
            return this;
        }

        public Builder header(SignupFormHeader header) {
            this.header = Optional.ofNullable(header);
            return this;
        }

        /**
         * <p>The signup form's list id.</p>
         */
        @JsonSetter(value = "list_id", nulls = Nulls.SKIP)
        public Builder listId(Optional<String> listId) {
            this.listId = listId;
            return this;
        }

        public Builder listId(String listId) {
            this.listId = Optional.ofNullable(listId);
            return this;
        }

        /**
         * <p>Signup form URL.</p>
         */
        @JsonSetter(value = "signup_form_url", nulls = Nulls.SKIP)
        public Builder signupFormUrl(Optional<String> signupFormUrl) {
            this.signupFormUrl = signupFormUrl;
            return this;
        }

        public Builder signupFormUrl(String signupFormUrl) {
            this.signupFormUrl = Optional.ofNullable(signupFormUrl);
            return this;
        }

        /**
         * <p>An array of objects, each representing an element style for the signup form.</p>
         */
        @JsonSetter(value = "styles", nulls = Nulls.SKIP)
        public Builder styles(Optional<List<SignupFormStylesItem>> styles) {
            this.styles = styles;
            return this;
        }

        public Builder styles(List<SignupFormStylesItem> styles) {
            this.styles = Optional.ofNullable(styles);
            return this;
        }

        public SignupForm build() {
            return new SignupForm(links, contents, header, listId, signupFormUrl, styles, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
