/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TemplateInstanceContentType {
    public static final TemplateInstanceContentType MULTICHANNEL =
            new TemplateInstanceContentType(Value.MULTICHANNEL, "multichannel");

    public static final TemplateInstanceContentType TEMPLATE =
            new TemplateInstanceContentType(Value.TEMPLATE, "template");

    public static final TemplateInstanceContentType HTML = new TemplateInstanceContentType(Value.HTML, "html");

    private final Value value;

    private final String string;

    TemplateInstanceContentType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof TemplateInstanceContentType
                        && this.string.equals(((TemplateInstanceContentType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case MULTICHANNEL:
                return visitor.visitMultichannel();
            case TEMPLATE:
                return visitor.visitTemplate();
            case HTML:
                return visitor.visitHtml();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TemplateInstanceContentType valueOf(String value) {
        switch (value) {
            case "multichannel":
                return MULTICHANNEL;
            case "template":
                return TEMPLATE;
            case "html":
                return HTML;
            default:
                return new TemplateInstanceContentType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        TEMPLATE,

        MULTICHANNEL,

        HTML,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitTemplate();

        T visitMultichannel();

        T visitHtml();

        T visitUnknown(String unknownType);
    }
}
