/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.searchcampaigns.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mailchimp.marketing.core.ObjectMappers;
import com.mailchimp.marketing.types.Campaigns;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListSearchCampaignsResponseResultsItem.Builder.class)
public final class ListSearchCampaignsResponseResultsItem {
    private final Optional<Campaigns> campaign;

    private final Optional<String> snippet;

    private final Map<String, Object> additionalProperties;

    private ListSearchCampaignsResponseResultsItem(
            Optional<Campaigns> campaign, Optional<String> snippet, Map<String, Object> additionalProperties) {
        this.campaign = campaign;
        this.snippet = snippet;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("campaign")
    public Optional<Campaigns> getCampaign() {
        return campaign;
    }

    @JsonProperty("snippet")
    public Optional<String> getSnippet() {
        return snippet;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListSearchCampaignsResponseResultsItem
                && equalTo((ListSearchCampaignsResponseResultsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListSearchCampaignsResponseResultsItem other) {
        return campaign.equals(other.campaign) && snippet.equals(other.snippet);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.campaign, this.snippet);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Campaigns> campaign = Optional.empty();

        private Optional<String> snippet = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListSearchCampaignsResponseResultsItem other) {
            campaign(other.getCampaign());
            snippet(other.getSnippet());
            return this;
        }

        @JsonSetter(value = "campaign", nulls = Nulls.SKIP)
        public Builder campaign(Optional<Campaigns> campaign) {
            this.campaign = campaign;
            return this;
        }

        public Builder campaign(Campaigns campaign) {
            this.campaign = Optional.ofNullable(campaign);
            return this;
        }

        @JsonSetter(value = "snippet", nulls = Nulls.SKIP)
        public Builder snippet(Optional<String> snippet) {
            this.snippet = snippet;
            return this;
        }

        public Builder snippet(String snippet) {
            this.snippet = Optional.ofNullable(snippet);
            return this;
        }

        public ListSearchCampaignsResponseResultsItem build() {
            return new ListSearchCampaignsResponseResultsItem(campaign, snippet, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
