/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mailchimp.marketing.resources.ecommerce;

import com.mailchimp.marketing.core.ClientOptions;
import com.mailchimp.marketing.core.RequestOptions;
import com.mailchimp.marketing.core.pagination.SyncPagingIterable;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStoreCartEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStoreCartLineEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStoreCustomerEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStoreEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStoreOrderEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStoreOrderLineEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStoreProductEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStoreProductImageEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStoreProductVariantEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStorePromoRuleEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.CreateStorePromoRulePromoCodeEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStoreCartEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStoreCartLineEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStoreCustomerEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStoreEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStoreOrderEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStoreOrderLineEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStoreProductEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStoreProductImageEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStoreProductVariantEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStorePromoRuleEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.DeleteStorePromoRulePromoCodeEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStoreCartEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStoreCartLineEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStoreCustomerEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStoreEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStoreOrderEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStoreOrderLineEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStoreProductEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStoreProductImageEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStoreProductVariantEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStorePromoRuleEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.GetStorePromoRulePromoCodeEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListOrdersEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStoreCartLinesEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStoreCartsEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStoreCustomersEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStoreOrderLinesEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStoreOrdersEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStoreProductImagesEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStoreProductVariantsEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStoreProductsEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStorePromoRulePromoCodesEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStorePromoRulesEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.ListStoresEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStoreCartEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStoreCartLineEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStoreCustomerEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStoreEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStoreOrderEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStoreOrderLineEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStoreProductEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStoreProductImageEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStoreProductVariantEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStorePromoRuleEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpdateStorePromoRulePromoCodeEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpsertStoreCustomerEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpsertStoreProductEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.requests.UpsertStoreProductVariantEcommerceRequest;
import com.mailchimp.marketing.resources.ecommerce.types.CreateStoreProductImageEcommerceResponse;
import com.mailchimp.marketing.resources.ecommerce.types.GetStoreProductImageEcommerceResponse;
import com.mailchimp.marketing.resources.ecommerce.types.ListEcommerceResponse;
import com.mailchimp.marketing.resources.ecommerce.types.ListStoreProductImagesEcommerceResponseImagesItem;
import com.mailchimp.marketing.resources.ecommerce.types.UpdateStoreProductImageEcommerceResponse;
import com.mailchimp.marketing.types.ECommerceCart;
import com.mailchimp.marketing.types.ECommerceCartLineItem;
import com.mailchimp.marketing.types.ECommerceCustomer;
import com.mailchimp.marketing.types.ECommerceOrder;
import com.mailchimp.marketing.types.ECommerceOrderLineItem;
import com.mailchimp.marketing.types.ECommerceProduct;
import com.mailchimp.marketing.types.ECommerceProductVariant;
import com.mailchimp.marketing.types.ECommercePromoCode;
import com.mailchimp.marketing.types.ECommercePromoRule;
import com.mailchimp.marketing.types.ECommerceStore;

public class EcommerceClient {
    protected final ClientOptions clientOptions;

    private final RawEcommerceClient rawClient;

    public EcommerceClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawEcommerceClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawEcommerceClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get information about the e-commerce endpoint's resources.
     */
    public ListEcommerceResponse list() {
        return this.rawClient.list().body();
    }

    /**
     * Get information about the e-commerce endpoint's resources.
     */
    public ListEcommerceResponse list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Get information about an account's orders.
     */
    public SyncPagingIterable<ECommerceOrder> listOrders() {
        return this.rawClient.listOrders().body();
    }

    /**
     * Get information about an account's orders.
     */
    public SyncPagingIterable<ECommerceOrder> listOrders(RequestOptions requestOptions) {
        return this.rawClient.listOrders(requestOptions).body();
    }

    /**
     * Get information about an account's orders.
     */
    public SyncPagingIterable<ECommerceOrder> listOrders(ListOrdersEcommerceRequest request) {
        return this.rawClient.listOrders(request).body();
    }

    /**
     * Get information about an account's orders.
     */
    public SyncPagingIterable<ECommerceOrder> listOrders(
            ListOrdersEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient.listOrders(request, requestOptions).body();
    }

    /**
     * Get information about all stores in the account.
     */
    public SyncPagingIterable<ECommerceStore> listStores() {
        return this.rawClient.listStores().body();
    }

    /**
     * Get information about all stores in the account.
     */
    public SyncPagingIterable<ECommerceStore> listStores(RequestOptions requestOptions) {
        return this.rawClient.listStores(requestOptions).body();
    }

    /**
     * Get information about all stores in the account.
     */
    public SyncPagingIterable<ECommerceStore> listStores(ListStoresEcommerceRequest request) {
        return this.rawClient.listStores(request).body();
    }

    /**
     * Get information about all stores in the account.
     */
    public SyncPagingIterable<ECommerceStore> listStores(
            ListStoresEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient.listStores(request, requestOptions).body();
    }

    /**
     * Add a new store to your Mailchimp account.
     */
    public ECommerceStore createStore(CreateStoreEcommerceRequest request) {
        return this.rawClient.createStore(request).body();
    }

    /**
     * Add a new store to your Mailchimp account.
     */
    public ECommerceStore createStore(CreateStoreEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient.createStore(request, requestOptions).body();
    }

    /**
     * Get information about a specific store.
     */
    public ECommerceStore getStore(String storeId) {
        return this.rawClient.getStore(storeId).body();
    }

    /**
     * Get information about a specific store.
     */
    public ECommerceStore getStore(String storeId, RequestOptions requestOptions) {
        return this.rawClient.getStore(storeId, requestOptions).body();
    }

    /**
     * Get information about a specific store.
     */
    public ECommerceStore getStore(String storeId, GetStoreEcommerceRequest request) {
        return this.rawClient.getStore(storeId, request).body();
    }

    /**
     * Get information about a specific store.
     */
    public ECommerceStore getStore(String storeId, GetStoreEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient.getStore(storeId, request, requestOptions).body();
    }

    /**
     * Delete a store. Deleting a store will also delete any associated subresources, including Customers, Orders, Products, and Carts.
     */
    public void deleteStore(String storeId) {
        this.rawClient.deleteStore(storeId).body();
    }

    /**
     * Delete a store. Deleting a store will also delete any associated subresources, including Customers, Orders, Products, and Carts.
     */
    public void deleteStore(String storeId, RequestOptions requestOptions) {
        this.rawClient.deleteStore(storeId, requestOptions).body();
    }

    /**
     * Delete a store. Deleting a store will also delete any associated subresources, including Customers, Orders, Products, and Carts.
     */
    public void deleteStore(String storeId, DeleteStoreEcommerceRequest request) {
        this.rawClient.deleteStore(storeId, request).body();
    }

    /**
     * Delete a store. Deleting a store will also delete any associated subresources, including Customers, Orders, Products, and Carts.
     */
    public void deleteStore(String storeId, DeleteStoreEcommerceRequest request, RequestOptions requestOptions) {
        this.rawClient.deleteStore(storeId, request, requestOptions).body();
    }

    /**
     * Update a store.
     */
    public ECommerceStore updateStore(String storeId) {
        return this.rawClient.updateStore(storeId).body();
    }

    /**
     * Update a store.
     */
    public ECommerceStore updateStore(String storeId, RequestOptions requestOptions) {
        return this.rawClient.updateStore(storeId, requestOptions).body();
    }

    /**
     * Update a store.
     */
    public ECommerceStore updateStore(String storeId, UpdateStoreEcommerceRequest request) {
        return this.rawClient.updateStore(storeId, request).body();
    }

    /**
     * Update a store.
     */
    public ECommerceStore updateStore(
            String storeId, UpdateStoreEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient.updateStore(storeId, request, requestOptions).body();
    }

    /**
     * Get information about a store's carts.
     */
    public SyncPagingIterable<ECommerceCart> listStoreCarts(String storeId) {
        return this.rawClient.listStoreCarts(storeId).body();
    }

    /**
     * Get information about a store's carts.
     */
    public SyncPagingIterable<ECommerceCart> listStoreCarts(String storeId, RequestOptions requestOptions) {
        return this.rawClient.listStoreCarts(storeId, requestOptions).body();
    }

    /**
     * Get information about a store's carts.
     */
    public SyncPagingIterable<ECommerceCart> listStoreCarts(String storeId, ListStoreCartsEcommerceRequest request) {
        return this.rawClient.listStoreCarts(storeId, request).body();
    }

    /**
     * Get information about a store's carts.
     */
    public SyncPagingIterable<ECommerceCart> listStoreCarts(
            String storeId, ListStoreCartsEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient.listStoreCarts(storeId, request, requestOptions).body();
    }

    /**
     * Add a new cart to a store.
     */
    public ECommerceCart createStoreCart(String storeId, CreateStoreCartEcommerceRequest request) {
        return this.rawClient.createStoreCart(storeId, request).body();
    }

    /**
     * Add a new cart to a store.
     */
    public ECommerceCart createStoreCart(
            String storeId, CreateStoreCartEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient.createStoreCart(storeId, request, requestOptions).body();
    }

    /**
     * Get information about a specific cart.
     */
    public ECommerceCart getStoreCart(String storeId, String cartId) {
        return this.rawClient.getStoreCart(storeId, cartId).body();
    }

    /**
     * Get information about a specific cart.
     */
    public ECommerceCart getStoreCart(String storeId, String cartId, RequestOptions requestOptions) {
        return this.rawClient.getStoreCart(storeId, cartId, requestOptions).body();
    }

    /**
     * Get information about a specific cart.
     */
    public ECommerceCart getStoreCart(String storeId, String cartId, GetStoreCartEcommerceRequest request) {
        return this.rawClient.getStoreCart(storeId, cartId, request).body();
    }

    /**
     * Get information about a specific cart.
     */
    public ECommerceCart getStoreCart(
            String storeId, String cartId, GetStoreCartEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getStoreCart(storeId, cartId, request, requestOptions)
                .body();
    }

    /**
     * Delete a cart.
     */
    public void deleteStoreCart(String storeId, String cartId) {
        this.rawClient.deleteStoreCart(storeId, cartId).body();
    }

    /**
     * Delete a cart.
     */
    public void deleteStoreCart(String storeId, String cartId, RequestOptions requestOptions) {
        this.rawClient.deleteStoreCart(storeId, cartId, requestOptions).body();
    }

    /**
     * Delete a cart.
     */
    public void deleteStoreCart(String storeId, String cartId, DeleteStoreCartEcommerceRequest request) {
        this.rawClient.deleteStoreCart(storeId, cartId, request).body();
    }

    /**
     * Delete a cart.
     */
    public void deleteStoreCart(
            String storeId, String cartId, DeleteStoreCartEcommerceRequest request, RequestOptions requestOptions) {
        this.rawClient.deleteStoreCart(storeId, cartId, request, requestOptions).body();
    }

    /**
     * Update a specific cart.
     */
    public ECommerceCart updateStoreCart(String storeId, String cartId) {
        return this.rawClient.updateStoreCart(storeId, cartId).body();
    }

    /**
     * Update a specific cart.
     */
    public ECommerceCart updateStoreCart(String storeId, String cartId, RequestOptions requestOptions) {
        return this.rawClient.updateStoreCart(storeId, cartId, requestOptions).body();
    }

    /**
     * Update a specific cart.
     */
    public ECommerceCart updateStoreCart(String storeId, String cartId, UpdateStoreCartEcommerceRequest request) {
        return this.rawClient.updateStoreCart(storeId, cartId, request).body();
    }

    /**
     * Update a specific cart.
     */
    public ECommerceCart updateStoreCart(
            String storeId, String cartId, UpdateStoreCartEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreCart(storeId, cartId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a cart's line items.
     */
    public SyncPagingIterable<ECommerceCartLineItem> listStoreCartLines(String storeId, String cartId) {
        return this.rawClient.listStoreCartLines(storeId, cartId).body();
    }

    /**
     * Get information about a cart's line items.
     */
    public SyncPagingIterable<ECommerceCartLineItem> listStoreCartLines(
            String storeId, String cartId, RequestOptions requestOptions) {
        return this.rawClient
                .listStoreCartLines(storeId, cartId, requestOptions)
                .body();
    }

    /**
     * Get information about a cart's line items.
     */
    public SyncPagingIterable<ECommerceCartLineItem> listStoreCartLines(
            String storeId, String cartId, ListStoreCartLinesEcommerceRequest request) {
        return this.rawClient.listStoreCartLines(storeId, cartId, request).body();
    }

    /**
     * Get information about a cart's line items.
     */
    public SyncPagingIterable<ECommerceCartLineItem> listStoreCartLines(
            String storeId, String cartId, ListStoreCartLinesEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .listStoreCartLines(storeId, cartId, request, requestOptions)
                .body();
    }

    /**
     * Add a new line item to an existing cart.
     */
    public ECommerceCartLineItem createStoreCartLine(
            String storeId, String cartId, CreateStoreCartLineEcommerceRequest request) {
        return this.rawClient.createStoreCartLine(storeId, cartId, request).body();
    }

    /**
     * Add a new line item to an existing cart.
     */
    public ECommerceCartLineItem createStoreCartLine(
            String storeId, String cartId, CreateStoreCartLineEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .createStoreCartLine(storeId, cartId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a specific cart line item.
     */
    public ECommerceCartLineItem getStoreCartLine(String storeId, String cartId, String lineId) {
        return this.rawClient.getStoreCartLine(storeId, cartId, lineId).body();
    }

    /**
     * Get information about a specific cart line item.
     */
    public ECommerceCartLineItem getStoreCartLine(
            String storeId, String cartId, String lineId, RequestOptions requestOptions) {
        return this.rawClient
                .getStoreCartLine(storeId, cartId, lineId, requestOptions)
                .body();
    }

    /**
     * Get information about a specific cart line item.
     */
    public ECommerceCartLineItem getStoreCartLine(
            String storeId, String cartId, String lineId, GetStoreCartLineEcommerceRequest request) {
        return this.rawClient.getStoreCartLine(storeId, cartId, lineId, request).body();
    }

    /**
     * Get information about a specific cart line item.
     */
    public ECommerceCartLineItem getStoreCartLine(
            String storeId,
            String cartId,
            String lineId,
            GetStoreCartLineEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .getStoreCartLine(storeId, cartId, lineId, request, requestOptions)
                .body();
    }

    /**
     * Delete a specific cart line item.
     */
    public void deleteStoreCartLine(String storeId, String cartId, String lineId) {
        this.rawClient.deleteStoreCartLine(storeId, cartId, lineId).body();
    }

    /**
     * Delete a specific cart line item.
     */
    public void deleteStoreCartLine(String storeId, String cartId, String lineId, RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreCartLine(storeId, cartId, lineId, requestOptions)
                .body();
    }

    /**
     * Delete a specific cart line item.
     */
    public void deleteStoreCartLine(
            String storeId, String cartId, String lineId, DeleteStoreCartLineEcommerceRequest request) {
        this.rawClient.deleteStoreCartLine(storeId, cartId, lineId, request).body();
    }

    /**
     * Delete a specific cart line item.
     */
    public void deleteStoreCartLine(
            String storeId,
            String cartId,
            String lineId,
            DeleteStoreCartLineEcommerceRequest request,
            RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreCartLine(storeId, cartId, lineId, request, requestOptions)
                .body();
    }

    /**
     * Update a specific cart line item.
     */
    public ECommerceCartLineItem updateStoreCartLine(String storeId, String cartId, String lineId) {
        return this.rawClient.updateStoreCartLine(storeId, cartId, lineId).body();
    }

    /**
     * Update a specific cart line item.
     */
    public ECommerceCartLineItem updateStoreCartLine(
            String storeId, String cartId, String lineId, RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreCartLine(storeId, cartId, lineId, requestOptions)
                .body();
    }

    /**
     * Update a specific cart line item.
     */
    public ECommerceCartLineItem updateStoreCartLine(
            String storeId, String cartId, String lineId, UpdateStoreCartLineEcommerceRequest request) {
        return this.rawClient
                .updateStoreCartLine(storeId, cartId, lineId, request)
                .body();
    }

    /**
     * Update a specific cart line item.
     */
    public ECommerceCartLineItem updateStoreCartLine(
            String storeId,
            String cartId,
            String lineId,
            UpdateStoreCartLineEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreCartLine(storeId, cartId, lineId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a store's customers.
     */
    public SyncPagingIterable<ECommerceCustomer> listStoreCustomers(String storeId) {
        return this.rawClient.listStoreCustomers(storeId).body();
    }

    /**
     * Get information about a store's customers.
     */
    public SyncPagingIterable<ECommerceCustomer> listStoreCustomers(String storeId, RequestOptions requestOptions) {
        return this.rawClient.listStoreCustomers(storeId, requestOptions).body();
    }

    /**
     * Get information about a store's customers.
     */
    public SyncPagingIterable<ECommerceCustomer> listStoreCustomers(
            String storeId, ListStoreCustomersEcommerceRequest request) {
        return this.rawClient.listStoreCustomers(storeId, request).body();
    }

    /**
     * Get information about a store's customers.
     */
    public SyncPagingIterable<ECommerceCustomer> listStoreCustomers(
            String storeId, ListStoreCustomersEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .listStoreCustomers(storeId, request, requestOptions)
                .body();
    }

    /**
     * Add a new customer to a store.
     */
    public ECommerceCustomer createStoreCustomer(String storeId, CreateStoreCustomerEcommerceRequest request) {
        return this.rawClient.createStoreCustomer(storeId, request).body();
    }

    /**
     * Add a new customer to a store.
     */
    public ECommerceCustomer createStoreCustomer(
            String storeId, CreateStoreCustomerEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .createStoreCustomer(storeId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a specific customer.
     */
    public ECommerceCustomer getStoreCustomer(String storeId, String customerId) {
        return this.rawClient.getStoreCustomer(storeId, customerId).body();
    }

    /**
     * Get information about a specific customer.
     */
    public ECommerceCustomer getStoreCustomer(String storeId, String customerId, RequestOptions requestOptions) {
        return this.rawClient
                .getStoreCustomer(storeId, customerId, requestOptions)
                .body();
    }

    /**
     * Get information about a specific customer.
     */
    public ECommerceCustomer getStoreCustomer(
            String storeId, String customerId, GetStoreCustomerEcommerceRequest request) {
        return this.rawClient.getStoreCustomer(storeId, customerId, request).body();
    }

    /**
     * Get information about a specific customer.
     */
    public ECommerceCustomer getStoreCustomer(
            String storeId,
            String customerId,
            GetStoreCustomerEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .getStoreCustomer(storeId, customerId, request, requestOptions)
                .body();
    }

    /**
     * Add or update a customer.
     */
    public ECommerceCustomer upsertStoreCustomer(String storeId, String customerId) {
        return this.rawClient.upsertStoreCustomer(storeId, customerId).body();
    }

    /**
     * Add or update a customer.
     */
    public ECommerceCustomer upsertStoreCustomer(String storeId, String customerId, RequestOptions requestOptions) {
        return this.rawClient
                .upsertStoreCustomer(storeId, customerId, requestOptions)
                .body();
    }

    /**
     * Add or update a customer.
     */
    public ECommerceCustomer upsertStoreCustomer(
            String storeId, String customerId, UpsertStoreCustomerEcommerceRequest request) {
        return this.rawClient.upsertStoreCustomer(storeId, customerId, request).body();
    }

    /**
     * Add or update a customer.
     */
    public ECommerceCustomer upsertStoreCustomer(
            String storeId,
            String customerId,
            UpsertStoreCustomerEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .upsertStoreCustomer(storeId, customerId, request, requestOptions)
                .body();
    }

    /**
     * Delete a customer from a store.
     */
    public void deleteStoreCustomer(String storeId, String customerId) {
        this.rawClient.deleteStoreCustomer(storeId, customerId).body();
    }

    /**
     * Delete a customer from a store.
     */
    public void deleteStoreCustomer(String storeId, String customerId, RequestOptions requestOptions) {
        this.rawClient.deleteStoreCustomer(storeId, customerId, requestOptions).body();
    }

    /**
     * Delete a customer from a store.
     */
    public void deleteStoreCustomer(String storeId, String customerId, DeleteStoreCustomerEcommerceRequest request) {
        this.rawClient.deleteStoreCustomer(storeId, customerId, request).body();
    }

    /**
     * Delete a customer from a store.
     */
    public void deleteStoreCustomer(
            String storeId,
            String customerId,
            DeleteStoreCustomerEcommerceRequest request,
            RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreCustomer(storeId, customerId, request, requestOptions)
                .body();
    }

    /**
     * Update a customer.
     */
    public ECommerceCustomer updateStoreCustomer(
            String storeId, String customerId, UpdateStoreCustomerEcommerceRequest request) {
        return this.rawClient.updateStoreCustomer(storeId, customerId, request).body();
    }

    /**
     * Update a customer.
     */
    public ECommerceCustomer updateStoreCustomer(
            String storeId,
            String customerId,
            UpdateStoreCustomerEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreCustomer(storeId, customerId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a store's orders.
     */
    public SyncPagingIterable<ECommerceOrder> listStoreOrders(String storeId) {
        return this.rawClient.listStoreOrders(storeId).body();
    }

    /**
     * Get information about a store's orders.
     */
    public SyncPagingIterable<ECommerceOrder> listStoreOrders(String storeId, RequestOptions requestOptions) {
        return this.rawClient.listStoreOrders(storeId, requestOptions).body();
    }

    /**
     * Get information about a store's orders.
     */
    public SyncPagingIterable<ECommerceOrder> listStoreOrders(String storeId, ListStoreOrdersEcommerceRequest request) {
        return this.rawClient.listStoreOrders(storeId, request).body();
    }

    /**
     * Get information about a store's orders.
     */
    public SyncPagingIterable<ECommerceOrder> listStoreOrders(
            String storeId, ListStoreOrdersEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient.listStoreOrders(storeId, request, requestOptions).body();
    }

    /**
     * Add a new order to a store.
     */
    public ECommerceOrder createStoreOrder(String storeId, CreateStoreOrderEcommerceRequest request) {
        return this.rawClient.createStoreOrder(storeId, request).body();
    }

    /**
     * Add a new order to a store.
     */
    public ECommerceOrder createStoreOrder(
            String storeId, CreateStoreOrderEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient.createStoreOrder(storeId, request, requestOptions).body();
    }

    /**
     * Get information about a specific order.
     */
    public ECommerceOrder getStoreOrder(String storeId, String orderId) {
        return this.rawClient.getStoreOrder(storeId, orderId).body();
    }

    /**
     * Get information about a specific order.
     */
    public ECommerceOrder getStoreOrder(String storeId, String orderId, RequestOptions requestOptions) {
        return this.rawClient.getStoreOrder(storeId, orderId, requestOptions).body();
    }

    /**
     * Get information about a specific order.
     */
    public ECommerceOrder getStoreOrder(String storeId, String orderId, GetStoreOrderEcommerceRequest request) {
        return this.rawClient.getStoreOrder(storeId, orderId, request).body();
    }

    /**
     * Get information about a specific order.
     */
    public ECommerceOrder getStoreOrder(
            String storeId, String orderId, GetStoreOrderEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getStoreOrder(storeId, orderId, request, requestOptions)
                .body();
    }

    /**
     * Delete an order.
     */
    public void deleteStoreOrder(String storeId, String orderId) {
        this.rawClient.deleteStoreOrder(storeId, orderId).body();
    }

    /**
     * Delete an order.
     */
    public void deleteStoreOrder(String storeId, String orderId, RequestOptions requestOptions) {
        this.rawClient.deleteStoreOrder(storeId, orderId, requestOptions).body();
    }

    /**
     * Delete an order.
     */
    public void deleteStoreOrder(String storeId, String orderId, DeleteStoreOrderEcommerceRequest request) {
        this.rawClient.deleteStoreOrder(storeId, orderId, request).body();
    }

    /**
     * Delete an order.
     */
    public void deleteStoreOrder(
            String storeId, String orderId, DeleteStoreOrderEcommerceRequest request, RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreOrder(storeId, orderId, request, requestOptions)
                .body();
    }

    /**
     * Update a specific order.
     */
    public ECommerceOrder updateStoreOrder(String storeId, String orderId) {
        return this.rawClient.updateStoreOrder(storeId, orderId).body();
    }

    /**
     * Update a specific order.
     */
    public ECommerceOrder updateStoreOrder(String storeId, String orderId, RequestOptions requestOptions) {
        return this.rawClient.updateStoreOrder(storeId, orderId, requestOptions).body();
    }

    /**
     * Update a specific order.
     */
    public ECommerceOrder updateStoreOrder(String storeId, String orderId, UpdateStoreOrderEcommerceRequest request) {
        return this.rawClient.updateStoreOrder(storeId, orderId, request).body();
    }

    /**
     * Update a specific order.
     */
    public ECommerceOrder updateStoreOrder(
            String storeId, String orderId, UpdateStoreOrderEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreOrder(storeId, orderId, request, requestOptions)
                .body();
    }

    /**
     * Get information about an order's line items.
     */
    public SyncPagingIterable<ECommerceOrderLineItem> listStoreOrderLines(String storeId, String orderId) {
        return this.rawClient.listStoreOrderLines(storeId, orderId).body();
    }

    /**
     * Get information about an order's line items.
     */
    public SyncPagingIterable<ECommerceOrderLineItem> listStoreOrderLines(
            String storeId, String orderId, RequestOptions requestOptions) {
        return this.rawClient
                .listStoreOrderLines(storeId, orderId, requestOptions)
                .body();
    }

    /**
     * Get information about an order's line items.
     */
    public SyncPagingIterable<ECommerceOrderLineItem> listStoreOrderLines(
            String storeId, String orderId, ListStoreOrderLinesEcommerceRequest request) {
        return this.rawClient.listStoreOrderLines(storeId, orderId, request).body();
    }

    /**
     * Get information about an order's line items.
     */
    public SyncPagingIterable<ECommerceOrderLineItem> listStoreOrderLines(
            String storeId,
            String orderId,
            ListStoreOrderLinesEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .listStoreOrderLines(storeId, orderId, request, requestOptions)
                .body();
    }

    /**
     * Add a new line item to an existing order.
     */
    public ECommerceOrderLineItem createStoreOrderLine(
            String storeId, String orderId, CreateStoreOrderLineEcommerceRequest request) {
        return this.rawClient.createStoreOrderLine(storeId, orderId, request).body();
    }

    /**
     * Add a new line item to an existing order.
     */
    public ECommerceOrderLineItem createStoreOrderLine(
            String storeId,
            String orderId,
            CreateStoreOrderLineEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .createStoreOrderLine(storeId, orderId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a specific order line item.
     */
    public ECommerceOrderLineItem getStoreOrderLine(String storeId, String orderId, String lineId) {
        return this.rawClient.getStoreOrderLine(storeId, orderId, lineId).body();
    }

    /**
     * Get information about a specific order line item.
     */
    public ECommerceOrderLineItem getStoreOrderLine(
            String storeId, String orderId, String lineId, RequestOptions requestOptions) {
        return this.rawClient
                .getStoreOrderLine(storeId, orderId, lineId, requestOptions)
                .body();
    }

    /**
     * Get information about a specific order line item.
     */
    public ECommerceOrderLineItem getStoreOrderLine(
            String storeId, String orderId, String lineId, GetStoreOrderLineEcommerceRequest request) {
        return this.rawClient
                .getStoreOrderLine(storeId, orderId, lineId, request)
                .body();
    }

    /**
     * Get information about a specific order line item.
     */
    public ECommerceOrderLineItem getStoreOrderLine(
            String storeId,
            String orderId,
            String lineId,
            GetStoreOrderLineEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .getStoreOrderLine(storeId, orderId, lineId, request, requestOptions)
                .body();
    }

    /**
     * Delete a specific order line item.
     */
    public void deleteStoreOrderLine(String storeId, String orderId, String lineId) {
        this.rawClient.deleteStoreOrderLine(storeId, orderId, lineId).body();
    }

    /**
     * Delete a specific order line item.
     */
    public void deleteStoreOrderLine(String storeId, String orderId, String lineId, RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreOrderLine(storeId, orderId, lineId, requestOptions)
                .body();
    }

    /**
     * Delete a specific order line item.
     */
    public void deleteStoreOrderLine(
            String storeId, String orderId, String lineId, DeleteStoreOrderLineEcommerceRequest request) {
        this.rawClient.deleteStoreOrderLine(storeId, orderId, lineId, request).body();
    }

    /**
     * Delete a specific order line item.
     */
    public void deleteStoreOrderLine(
            String storeId,
            String orderId,
            String lineId,
            DeleteStoreOrderLineEcommerceRequest request,
            RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreOrderLine(storeId, orderId, lineId, request, requestOptions)
                .body();
    }

    /**
     * Update a specific order line item.
     */
    public ECommerceOrderLineItem updateStoreOrderLine(String storeId, String orderId, String lineId) {
        return this.rawClient.updateStoreOrderLine(storeId, orderId, lineId).body();
    }

    /**
     * Update a specific order line item.
     */
    public ECommerceOrderLineItem updateStoreOrderLine(
            String storeId, String orderId, String lineId, RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreOrderLine(storeId, orderId, lineId, requestOptions)
                .body();
    }

    /**
     * Update a specific order line item.
     */
    public ECommerceOrderLineItem updateStoreOrderLine(
            String storeId, String orderId, String lineId, UpdateStoreOrderLineEcommerceRequest request) {
        return this.rawClient
                .updateStoreOrderLine(storeId, orderId, lineId, request)
                .body();
    }

    /**
     * Update a specific order line item.
     */
    public ECommerceOrderLineItem updateStoreOrderLine(
            String storeId,
            String orderId,
            String lineId,
            UpdateStoreOrderLineEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreOrderLine(storeId, orderId, lineId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a store's products.
     */
    public SyncPagingIterable<ECommerceProduct> listStoreProducts(String storeId) {
        return this.rawClient.listStoreProducts(storeId).body();
    }

    /**
     * Get information about a store's products.
     */
    public SyncPagingIterable<ECommerceProduct> listStoreProducts(String storeId, RequestOptions requestOptions) {
        return this.rawClient.listStoreProducts(storeId, requestOptions).body();
    }

    /**
     * Get information about a store's products.
     */
    public SyncPagingIterable<ECommerceProduct> listStoreProducts(
            String storeId, ListStoreProductsEcommerceRequest request) {
        return this.rawClient.listStoreProducts(storeId, request).body();
    }

    /**
     * Get information about a store's products.
     */
    public SyncPagingIterable<ECommerceProduct> listStoreProducts(
            String storeId, ListStoreProductsEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .listStoreProducts(storeId, request, requestOptions)
                .body();
    }

    /**
     * Add a new product to a store.
     */
    public ECommerceProduct createStoreProduct(String storeId, CreateStoreProductEcommerceRequest request) {
        return this.rawClient.createStoreProduct(storeId, request).body();
    }

    /**
     * Add a new product to a store.
     */
    public ECommerceProduct createStoreProduct(
            String storeId, CreateStoreProductEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .createStoreProduct(storeId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a specific product.
     */
    public ECommerceProduct getStoreProduct(String storeId, String productId) {
        return this.rawClient.getStoreProduct(storeId, productId).body();
    }

    /**
     * Get information about a specific product.
     */
    public ECommerceProduct getStoreProduct(String storeId, String productId, RequestOptions requestOptions) {
        return this.rawClient
                .getStoreProduct(storeId, productId, requestOptions)
                .body();
    }

    /**
     * Get information about a specific product.
     */
    public ECommerceProduct getStoreProduct(String storeId, String productId, GetStoreProductEcommerceRequest request) {
        return this.rawClient.getStoreProduct(storeId, productId, request).body();
    }

    /**
     * Get information about a specific product.
     */
    public ECommerceProduct getStoreProduct(
            String storeId, String productId, GetStoreProductEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getStoreProduct(storeId, productId, request, requestOptions)
                .body();
    }

    /**
     * Update a specific product.
     */
    public ECommerceProduct upsertStoreProduct(
            String storeId, String productId, UpsertStoreProductEcommerceRequest request) {
        return this.rawClient.upsertStoreProduct(storeId, productId, request).body();
    }

    /**
     * Update a specific product.
     */
    public ECommerceProduct upsertStoreProduct(
            String storeId,
            String productId,
            UpsertStoreProductEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .upsertStoreProduct(storeId, productId, request, requestOptions)
                .body();
    }

    /**
     * Delete a product.
     */
    public void deleteStoreProduct(String storeId, String productId) {
        this.rawClient.deleteStoreProduct(storeId, productId).body();
    }

    /**
     * Delete a product.
     */
    public void deleteStoreProduct(String storeId, String productId, RequestOptions requestOptions) {
        this.rawClient.deleteStoreProduct(storeId, productId, requestOptions).body();
    }

    /**
     * Delete a product.
     */
    public void deleteStoreProduct(String storeId, String productId, DeleteStoreProductEcommerceRequest request) {
        this.rawClient.deleteStoreProduct(storeId, productId, request).body();
    }

    /**
     * Delete a product.
     */
    public void deleteStoreProduct(
            String storeId,
            String productId,
            DeleteStoreProductEcommerceRequest request,
            RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreProduct(storeId, productId, request, requestOptions)
                .body();
    }

    /**
     * Update a specific product.
     */
    public ECommerceProduct updateStoreProduct(String storeId, String productId) {
        return this.rawClient.updateStoreProduct(storeId, productId).body();
    }

    /**
     * Update a specific product.
     */
    public ECommerceProduct updateStoreProduct(String storeId, String productId, RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreProduct(storeId, productId, requestOptions)
                .body();
    }

    /**
     * Update a specific product.
     */
    public ECommerceProduct updateStoreProduct(
            String storeId, String productId, UpdateStoreProductEcommerceRequest request) {
        return this.rawClient.updateStoreProduct(storeId, productId, request).body();
    }

    /**
     * Update a specific product.
     */
    public ECommerceProduct updateStoreProduct(
            String storeId,
            String productId,
            UpdateStoreProductEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreProduct(storeId, productId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a product's images.
     */
    public SyncPagingIterable<ListStoreProductImagesEcommerceResponseImagesItem> listStoreProductImages(
            String storeId, String productId) {
        return this.rawClient.listStoreProductImages(storeId, productId).body();
    }

    /**
     * Get information about a product's images.
     */
    public SyncPagingIterable<ListStoreProductImagesEcommerceResponseImagesItem> listStoreProductImages(
            String storeId, String productId, RequestOptions requestOptions) {
        return this.rawClient
                .listStoreProductImages(storeId, productId, requestOptions)
                .body();
    }

    /**
     * Get information about a product's images.
     */
    public SyncPagingIterable<ListStoreProductImagesEcommerceResponseImagesItem> listStoreProductImages(
            String storeId, String productId, ListStoreProductImagesEcommerceRequest request) {
        return this.rawClient
                .listStoreProductImages(storeId, productId, request)
                .body();
    }

    /**
     * Get information about a product's images.
     */
    public SyncPagingIterable<ListStoreProductImagesEcommerceResponseImagesItem> listStoreProductImages(
            String storeId,
            String productId,
            ListStoreProductImagesEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .listStoreProductImages(storeId, productId, request, requestOptions)
                .body();
    }

    /**
     * Add a new image to the product.
     */
    public CreateStoreProductImageEcommerceResponse createStoreProductImage(
            String storeId, String productId, CreateStoreProductImageEcommerceRequest request) {
        return this.rawClient
                .createStoreProductImage(storeId, productId, request)
                .body();
    }

    /**
     * Add a new image to the product.
     */
    public CreateStoreProductImageEcommerceResponse createStoreProductImage(
            String storeId,
            String productId,
            CreateStoreProductImageEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .createStoreProductImage(storeId, productId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a specific product image.
     */
    public GetStoreProductImageEcommerceResponse getStoreProductImage(
            String storeId, String productId, String imageId) {
        return this.rawClient.getStoreProductImage(storeId, productId, imageId).body();
    }

    /**
     * Get information about a specific product image.
     */
    public GetStoreProductImageEcommerceResponse getStoreProductImage(
            String storeId, String productId, String imageId, RequestOptions requestOptions) {
        return this.rawClient
                .getStoreProductImage(storeId, productId, imageId, requestOptions)
                .body();
    }

    /**
     * Get information about a specific product image.
     */
    public GetStoreProductImageEcommerceResponse getStoreProductImage(
            String storeId, String productId, String imageId, GetStoreProductImageEcommerceRequest request) {
        return this.rawClient
                .getStoreProductImage(storeId, productId, imageId, request)
                .body();
    }

    /**
     * Get information about a specific product image.
     */
    public GetStoreProductImageEcommerceResponse getStoreProductImage(
            String storeId,
            String productId,
            String imageId,
            GetStoreProductImageEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .getStoreProductImage(storeId, productId, imageId, request, requestOptions)
                .body();
    }

    /**
     * Delete a product image.
     */
    public void deleteStoreProductImage(String storeId, String productId, String imageId) {
        this.rawClient.deleteStoreProductImage(storeId, productId, imageId).body();
    }

    /**
     * Delete a product image.
     */
    public void deleteStoreProductImage(
            String storeId, String productId, String imageId, RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreProductImage(storeId, productId, imageId, requestOptions)
                .body();
    }

    /**
     * Delete a product image.
     */
    public void deleteStoreProductImage(
            String storeId, String productId, String imageId, DeleteStoreProductImageEcommerceRequest request) {
        this.rawClient
                .deleteStoreProductImage(storeId, productId, imageId, request)
                .body();
    }

    /**
     * Delete a product image.
     */
    public void deleteStoreProductImage(
            String storeId,
            String productId,
            String imageId,
            DeleteStoreProductImageEcommerceRequest request,
            RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreProductImage(storeId, productId, imageId, request, requestOptions)
                .body();
    }

    /**
     * Update a product image.
     */
    public UpdateStoreProductImageEcommerceResponse updateStoreProductImage(
            String storeId, String productId, String imageId) {
        return this.rawClient
                .updateStoreProductImage(storeId, productId, imageId)
                .body();
    }

    /**
     * Update a product image.
     */
    public UpdateStoreProductImageEcommerceResponse updateStoreProductImage(
            String storeId, String productId, String imageId, RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreProductImage(storeId, productId, imageId, requestOptions)
                .body();
    }

    /**
     * Update a product image.
     */
    public UpdateStoreProductImageEcommerceResponse updateStoreProductImage(
            String storeId, String productId, String imageId, UpdateStoreProductImageEcommerceRequest request) {
        return this.rawClient
                .updateStoreProductImage(storeId, productId, imageId, request)
                .body();
    }

    /**
     * Update a product image.
     */
    public UpdateStoreProductImageEcommerceResponse updateStoreProductImage(
            String storeId,
            String productId,
            String imageId,
            UpdateStoreProductImageEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreProductImage(storeId, productId, imageId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a product's variants.
     */
    public SyncPagingIterable<ECommerceProductVariant> listStoreProductVariants(String storeId, String productId) {
        return this.rawClient.listStoreProductVariants(storeId, productId).body();
    }

    /**
     * Get information about a product's variants.
     */
    public SyncPagingIterable<ECommerceProductVariant> listStoreProductVariants(
            String storeId, String productId, RequestOptions requestOptions) {
        return this.rawClient
                .listStoreProductVariants(storeId, productId, requestOptions)
                .body();
    }

    /**
     * Get information about a product's variants.
     */
    public SyncPagingIterable<ECommerceProductVariant> listStoreProductVariants(
            String storeId, String productId, ListStoreProductVariantsEcommerceRequest request) {
        return this.rawClient
                .listStoreProductVariants(storeId, productId, request)
                .body();
    }

    /**
     * Get information about a product's variants.
     */
    public SyncPagingIterable<ECommerceProductVariant> listStoreProductVariants(
            String storeId,
            String productId,
            ListStoreProductVariantsEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .listStoreProductVariants(storeId, productId, request, requestOptions)
                .body();
    }

    /**
     * Add a new variant to the product.
     */
    public ECommerceProductVariant createStoreProductVariant(
            String storeId, String productId, CreateStoreProductVariantEcommerceRequest request) {
        return this.rawClient
                .createStoreProductVariant(storeId, productId, request)
                .body();
    }

    /**
     * Add a new variant to the product.
     */
    public ECommerceProductVariant createStoreProductVariant(
            String storeId,
            String productId,
            CreateStoreProductVariantEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .createStoreProductVariant(storeId, productId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a specific product variant.
     */
    public ECommerceProductVariant getStoreProductVariant(String storeId, String productId, String variantId) {
        return this.rawClient
                .getStoreProductVariant(storeId, productId, variantId)
                .body();
    }

    /**
     * Get information about a specific product variant.
     */
    public ECommerceProductVariant getStoreProductVariant(
            String storeId, String productId, String variantId, RequestOptions requestOptions) {
        return this.rawClient
                .getStoreProductVariant(storeId, productId, variantId, requestOptions)
                .body();
    }

    /**
     * Get information about a specific product variant.
     */
    public ECommerceProductVariant getStoreProductVariant(
            String storeId, String productId, String variantId, GetStoreProductVariantEcommerceRequest request) {
        return this.rawClient
                .getStoreProductVariant(storeId, productId, variantId, request)
                .body();
    }

    /**
     * Get information about a specific product variant.
     */
    public ECommerceProductVariant getStoreProductVariant(
            String storeId,
            String productId,
            String variantId,
            GetStoreProductVariantEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .getStoreProductVariant(storeId, productId, variantId, request, requestOptions)
                .body();
    }

    /**
     * Add or update a product variant.
     */
    public ECommerceProductVariant upsertStoreProductVariant(String storeId, String productId, String variantId) {
        return this.rawClient
                .upsertStoreProductVariant(storeId, productId, variantId)
                .body();
    }

    /**
     * Add or update a product variant.
     */
    public ECommerceProductVariant upsertStoreProductVariant(
            String storeId, String productId, String variantId, RequestOptions requestOptions) {
        return this.rawClient
                .upsertStoreProductVariant(storeId, productId, variantId, requestOptions)
                .body();
    }

    /**
     * Add or update a product variant.
     */
    public ECommerceProductVariant upsertStoreProductVariant(
            String storeId, String productId, String variantId, UpsertStoreProductVariantEcommerceRequest request) {
        return this.rawClient
                .upsertStoreProductVariant(storeId, productId, variantId, request)
                .body();
    }

    /**
     * Add or update a product variant.
     */
    public ECommerceProductVariant upsertStoreProductVariant(
            String storeId,
            String productId,
            String variantId,
            UpsertStoreProductVariantEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .upsertStoreProductVariant(storeId, productId, variantId, request, requestOptions)
                .body();
    }

    /**
     * Delete a product variant.
     */
    public void deleteStoreProductVariant(String storeId, String productId, String variantId) {
        this.rawClient.deleteStoreProductVariant(storeId, productId, variantId).body();
    }

    /**
     * Delete a product variant.
     */
    public void deleteStoreProductVariant(
            String storeId, String productId, String variantId, RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreProductVariant(storeId, productId, variantId, requestOptions)
                .body();
    }

    /**
     * Delete a product variant.
     */
    public void deleteStoreProductVariant(
            String storeId, String productId, String variantId, DeleteStoreProductVariantEcommerceRequest request) {
        this.rawClient
                .deleteStoreProductVariant(storeId, productId, variantId, request)
                .body();
    }

    /**
     * Delete a product variant.
     */
    public void deleteStoreProductVariant(
            String storeId,
            String productId,
            String variantId,
            DeleteStoreProductVariantEcommerceRequest request,
            RequestOptions requestOptions) {
        this.rawClient
                .deleteStoreProductVariant(storeId, productId, variantId, request, requestOptions)
                .body();
    }

    /**
     * Update a product variant.
     */
    public ECommerceProductVariant updateStoreProductVariant(String storeId, String productId, String variantId) {
        return this.rawClient
                .updateStoreProductVariant(storeId, productId, variantId)
                .body();
    }

    /**
     * Update a product variant.
     */
    public ECommerceProductVariant updateStoreProductVariant(
            String storeId, String productId, String variantId, RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreProductVariant(storeId, productId, variantId, requestOptions)
                .body();
    }

    /**
     * Update a product variant.
     */
    public ECommerceProductVariant updateStoreProductVariant(
            String storeId, String productId, String variantId, UpdateStoreProductVariantEcommerceRequest request) {
        return this.rawClient
                .updateStoreProductVariant(storeId, productId, variantId, request)
                .body();
    }

    /**
     * Update a product variant.
     */
    public ECommerceProductVariant updateStoreProductVariant(
            String storeId,
            String productId,
            String variantId,
            UpdateStoreProductVariantEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .updateStoreProductVariant(storeId, productId, variantId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a store's promo rules.
     */
    public SyncPagingIterable<ECommercePromoRule> listStorePromoRules(String storeId) {
        return this.rawClient.listStorePromoRules(storeId).body();
    }

    /**
     * Get information about a store's promo rules.
     */
    public SyncPagingIterable<ECommercePromoRule> listStorePromoRules(String storeId, RequestOptions requestOptions) {
        return this.rawClient.listStorePromoRules(storeId, requestOptions).body();
    }

    /**
     * Get information about a store's promo rules.
     */
    public SyncPagingIterable<ECommercePromoRule> listStorePromoRules(
            String storeId, ListStorePromoRulesEcommerceRequest request) {
        return this.rawClient.listStorePromoRules(storeId, request).body();
    }

    /**
     * Get information about a store's promo rules.
     */
    public SyncPagingIterable<ECommercePromoRule> listStorePromoRules(
            String storeId, ListStorePromoRulesEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .listStorePromoRules(storeId, request, requestOptions)
                .body();
    }

    /**
     * Add a new promo rule to a store.
     */
    public ECommercePromoRule createStorePromoRule(String storeId, CreateStorePromoRuleEcommerceRequest request) {
        return this.rawClient.createStorePromoRule(storeId, request).body();
    }

    /**
     * Add a new promo rule to a store.
     */
    public ECommercePromoRule createStorePromoRule(
            String storeId, CreateStorePromoRuleEcommerceRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .createStorePromoRule(storeId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a specific promo rule.
     */
    public ECommercePromoRule getStorePromoRule(String storeId, String promoRuleId) {
        return this.rawClient.getStorePromoRule(storeId, promoRuleId).body();
    }

    /**
     * Get information about a specific promo rule.
     */
    public ECommercePromoRule getStorePromoRule(String storeId, String promoRuleId, RequestOptions requestOptions) {
        return this.rawClient
                .getStorePromoRule(storeId, promoRuleId, requestOptions)
                .body();
    }

    /**
     * Get information about a specific promo rule.
     */
    public ECommercePromoRule getStorePromoRule(
            String storeId, String promoRuleId, GetStorePromoRuleEcommerceRequest request) {
        return this.rawClient.getStorePromoRule(storeId, promoRuleId, request).body();
    }

    /**
     * Get information about a specific promo rule.
     */
    public ECommercePromoRule getStorePromoRule(
            String storeId,
            String promoRuleId,
            GetStorePromoRuleEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .getStorePromoRule(storeId, promoRuleId, request, requestOptions)
                .body();
    }

    /**
     * Delete a promo rule from a store.
     */
    public void deleteStorePromoRule(String storeId, String promoRuleId) {
        this.rawClient.deleteStorePromoRule(storeId, promoRuleId).body();
    }

    /**
     * Delete a promo rule from a store.
     */
    public void deleteStorePromoRule(String storeId, String promoRuleId, RequestOptions requestOptions) {
        this.rawClient
                .deleteStorePromoRule(storeId, promoRuleId, requestOptions)
                .body();
    }

    /**
     * Delete a promo rule from a store.
     */
    public void deleteStorePromoRule(String storeId, String promoRuleId, DeleteStorePromoRuleEcommerceRequest request) {
        this.rawClient.deleteStorePromoRule(storeId, promoRuleId, request).body();
    }

    /**
     * Delete a promo rule from a store.
     */
    public void deleteStorePromoRule(
            String storeId,
            String promoRuleId,
            DeleteStorePromoRuleEcommerceRequest request,
            RequestOptions requestOptions) {
        this.rawClient
                .deleteStorePromoRule(storeId, promoRuleId, request, requestOptions)
                .body();
    }

    /**
     * Update a promo rule.
     */
    public ECommercePromoRule updateStorePromoRule(String storeId, String promoRuleId) {
        return this.rawClient.updateStorePromoRule(storeId, promoRuleId).body();
    }

    /**
     * Update a promo rule.
     */
    public ECommercePromoRule updateStorePromoRule(String storeId, String promoRuleId, RequestOptions requestOptions) {
        return this.rawClient
                .updateStorePromoRule(storeId, promoRuleId, requestOptions)
                .body();
    }

    /**
     * Update a promo rule.
     */
    public ECommercePromoRule updateStorePromoRule(
            String storeId, String promoRuleId, UpdateStorePromoRuleEcommerceRequest request) {
        return this.rawClient
                .updateStorePromoRule(storeId, promoRuleId, request)
                .body();
    }

    /**
     * Update a promo rule.
     */
    public ECommercePromoRule updateStorePromoRule(
            String storeId,
            String promoRuleId,
            UpdateStorePromoRuleEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .updateStorePromoRule(storeId, promoRuleId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a store's promo codes.
     */
    public SyncPagingIterable<ECommercePromoCode> listStorePromoRulePromoCodes(String storeId, String promoRuleId) {
        return this.rawClient.listStorePromoRulePromoCodes(storeId, promoRuleId).body();
    }

    /**
     * Get information about a store's promo codes.
     */
    public SyncPagingIterable<ECommercePromoCode> listStorePromoRulePromoCodes(
            String storeId, String promoRuleId, RequestOptions requestOptions) {
        return this.rawClient
                .listStorePromoRulePromoCodes(storeId, promoRuleId, requestOptions)
                .body();
    }

    /**
     * Get information about a store's promo codes.
     */
    public SyncPagingIterable<ECommercePromoCode> listStorePromoRulePromoCodes(
            String storeId, String promoRuleId, ListStorePromoRulePromoCodesEcommerceRequest request) {
        return this.rawClient
                .listStorePromoRulePromoCodes(storeId, promoRuleId, request)
                .body();
    }

    /**
     * Get information about a store's promo codes.
     */
    public SyncPagingIterable<ECommercePromoCode> listStorePromoRulePromoCodes(
            String storeId,
            String promoRuleId,
            ListStorePromoRulePromoCodesEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .listStorePromoRulePromoCodes(storeId, promoRuleId, request, requestOptions)
                .body();
    }

    /**
     * Add a new promo code to a store.
     */
    public ECommercePromoCode createStorePromoRulePromoCode(
            String storeId, String promoRuleId, CreateStorePromoRulePromoCodeEcommerceRequest request) {
        return this.rawClient
                .createStorePromoRulePromoCode(storeId, promoRuleId, request)
                .body();
    }

    /**
     * Add a new promo code to a store.
     */
    public ECommercePromoCode createStorePromoRulePromoCode(
            String storeId,
            String promoRuleId,
            CreateStorePromoRulePromoCodeEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .createStorePromoRulePromoCode(storeId, promoRuleId, request, requestOptions)
                .body();
    }

    /**
     * Get information about a specific promo code.
     */
    public ECommercePromoCode getStorePromoRulePromoCode(String storeId, String promoRuleId, String promoCodeId) {
        return this.rawClient
                .getStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId)
                .body();
    }

    /**
     * Get information about a specific promo code.
     */
    public ECommercePromoCode getStorePromoRulePromoCode(
            String storeId, String promoRuleId, String promoCodeId, RequestOptions requestOptions) {
        return this.rawClient
                .getStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId, requestOptions)
                .body();
    }

    /**
     * Get information about a specific promo code.
     */
    public ECommercePromoCode getStorePromoRulePromoCode(
            String storeId,
            String promoRuleId,
            String promoCodeId,
            GetStorePromoRulePromoCodeEcommerceRequest request) {
        return this.rawClient
                .getStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId, request)
                .body();
    }

    /**
     * Get information about a specific promo code.
     */
    public ECommercePromoCode getStorePromoRulePromoCode(
            String storeId,
            String promoRuleId,
            String promoCodeId,
            GetStorePromoRulePromoCodeEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .getStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId, request, requestOptions)
                .body();
    }

    /**
     * Delete a promo code from a store.
     */
    public void deleteStorePromoRulePromoCode(String storeId, String promoRuleId, String promoCodeId) {
        this.rawClient
                .deleteStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId)
                .body();
    }

    /**
     * Delete a promo code from a store.
     */
    public void deleteStorePromoRulePromoCode(
            String storeId, String promoRuleId, String promoCodeId, RequestOptions requestOptions) {
        this.rawClient
                .deleteStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId, requestOptions)
                .body();
    }

    /**
     * Delete a promo code from a store.
     */
    public void deleteStorePromoRulePromoCode(
            String storeId,
            String promoRuleId,
            String promoCodeId,
            DeleteStorePromoRulePromoCodeEcommerceRequest request) {
        this.rawClient
                .deleteStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId, request)
                .body();
    }

    /**
     * Delete a promo code from a store.
     */
    public void deleteStorePromoRulePromoCode(
            String storeId,
            String promoRuleId,
            String promoCodeId,
            DeleteStorePromoRulePromoCodeEcommerceRequest request,
            RequestOptions requestOptions) {
        this.rawClient
                .deleteStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId, request, requestOptions)
                .body();
    }

    /**
     * Update a promo code.
     */
    public ECommercePromoCode updateStorePromoRulePromoCode(String storeId, String promoRuleId, String promoCodeId) {
        return this.rawClient
                .updateStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId)
                .body();
    }

    /**
     * Update a promo code.
     */
    public ECommercePromoCode updateStorePromoRulePromoCode(
            String storeId, String promoRuleId, String promoCodeId, RequestOptions requestOptions) {
        return this.rawClient
                .updateStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId, requestOptions)
                .body();
    }

    /**
     * Update a promo code.
     */
    public ECommercePromoCode updateStorePromoRulePromoCode(
            String storeId,
            String promoRuleId,
            String promoCodeId,
            UpdateStorePromoRulePromoCodeEcommerceRequest request) {
        return this.rawClient
                .updateStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId, request)
                .body();
    }

    /**
     * Update a promo code.
     */
    public ECommercePromoCode updateStorePromoRulePromoCode(
            String storeId,
            String promoRuleId,
            String promoCodeId,
            UpdateStorePromoRulePromoCodeEcommerceRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .updateStorePromoRulePromoCode(storeId, promoRuleId, promoCodeId, request, requestOptions)
                .body();
    }
}
